### PR TITLE
Spawn WIF* prefix and Doxygen fixes

### PR DESCRIPTION
**Pull request by b4n**
Closes #567.

### CODE REVIEW

**Comment by b4n** [comment]
@zhekov

**Comment by b4n** [comment]
rebased on top of #568

**Comment by eht16** [comment]
LGTM, tested generated Doxygen docs as well as compilation on Windows (just in case).

**Comment by zhekov** [comment]
OK, TNX.

Please also see my reply in the mailing list, I included information about a win32.c link error.

**Comment by zhekov** [comment]
I checked the master to be 100% sure. Seems OK.

But we really shouldn't do such things in the last moment... :)

**Comment by b4n** [comment]
Surely we shouldnt, but that happens every year, we never seem to learn :/

**Pull request merged**
