### PR TITLE
Update identifiers list for Python 3

### PR DESCRIPTION
**Pull request by b4n**
…and add a script to automate the process.  This script could be made a little cleaner, but it works just fine (and actually didn't alter anything if only including Python 2 keywords).

Part of #748.

### CODE REVIEW

**Comment by b4n** [comment]
See https://github.com/geany/geany/pull/748#issuecomment-156162645, as maybe listing everything here as we used to is not the best way to go forward -- or maybe it is.

**Comment by eht16** [comment]
LGTM, especially the script for updating is nice!

**Comment by elextr** [comment]
LGTM, except the PY3 update commit leaves the comment on the line above saying py 2.7 keywords.

**Comment by b4n** [comment]
@elextr good catch, fixed

**Comment by b4n** [comment]
…and while at it, let's update keywords as well as we can query those too.

**Comment by b4n** [comment]
(which adds missing `nonlocal` keyword)

**Pull request merged**
