### PR TITLE
Switch PO_DEPENDS_ON_POT to no

### LINKED ISSUE #3077: Translation message catalogs are always updated when building Geany
Since https://github.com/geany/geany/pull/2938 was merged, a simple `make` in the Geany source directory causes all `po/*.po` files to be updated and so listed as modified by `git status`.

@kugel- is this intended?

If there is no reason to do this, I'd consider this as rather annoying.

### PR DESCRIPTION
**Pull request by Davidy22**
Stops generating/changing masses of translation files on build

Resolves #3077

### CODE REVIEW

**Comment by Davidy22** [comment]
Surreptitious switch from --force-missing because it fails the build

**Comment by kugel-** [comment]
I think you mistakingly replaced this PR with another change.

**Comment by Davidy22** [comment]
It was a quick heavy reformation of the PR when I saw CI come back to me explaining why we use --force instead of --force-missing

**Comment by kugel-** [comment]
Well I don't fully understand the CI issue but *this* change is probably fine.

**Pull request merged**
