### PR TITLE
waf: Check and enable C99 compiler support

### LINKED ISSUE #679: Waf: Enable C99 support
Now Geany [uses](https://github.com/geany/geany/commit/131b608d5b430df6bb960ecdd63611cb5cda4be8) [C99](https://github.com/geany/geany/commit/ef331759b01a415ba4d09b4940aa052f9ceedf7c), we need Waf to check and enable it.  We currently get build errors with Waf because of this: http://nightly.geany.org/misc/build_gtk224_geany_stderr.log

This was done for Geany-Plugins in https://github.com/geany/geany-plugins/commit/cd59d3877ed2448e92b6c1ae18a7a2baace196b6

### PR DESCRIPTION
**Pull request by b4n**
Closes #679.

### CODE REVIEW

**Comment by eht16** [comment]
```from waflib.Errors import ConfigurationError``` is missing at the top, the rest looks fine.

**Comment by b4n** [comment]
@eht16 good catch.  should be fixed

**Comment by codebrainz** [comment]
Seems reasonable, though I still think sticking `-std=c99` in `CFLAGS` would cover the same compilers Geany is expected to work with :)

**Comment by eht16** [comment]
I don't mind. Since we agreed to drop Waf anyway after 1.26, it doesn't matter much I'd say. Just merge either of both ways. Colomban's variant seems safer.

**Pull request merged**
