### PR TITLE
Cancel 'MSG_TYPE_RESAVE' info bar if still open in function 'document_reload_force'.

### LINKED ISSUE #1330: Dismiss "Deleted from Disk" Infobar on Reload
When an open document's file is deleted from disk the infobar pops up to let the user know. The infobar doesn't have a Reload option (which kind of makes sense). Often I'll have a generated file open which is frequently deleted and re-created from scratch, which of course triggers the infobar. I'll then generate the file and want to reload it in Geany so I press the Reload button. Doing this should dismiss/cancel the infobar that is effectively wrong now instead of having to press Cancel manually after reloading.

A further enhancement would be for Geany to detect the file is back on disk and switch the infobar out for the one notifying of a change on disk, which does have a Reload option and is also dismissed on reload.

### PR DESCRIPTION
**Pull request by LarsGit223**
Fixes #1330.

### CODE REVIEW

**Comment by codebrainz** [comment]
Will try to test soon. Requested review from @kugel- since he worked on this code a lot.

**Comment by LarsGit223** [comment]
To what? Take the title from issue 1330?

**Comment by elextr** [comment]
@LarsGit223 Git takes the first line of the commit description as the title of the commit, so it should be a short but complete one line summary.  Full details then go on the following lines which are taken as the body of the commit.  Don't continue the title line into the body.

**Comment by LarsGit223** [comment]
I created a new PR with a different commit message, see #1628. So this can be closed.

**Comment by codebrainz** [comment]
@LarsGit223 you can also do a "force push" to your existing branch to reword it, something like these steps:

```bash
$ git checkout issue1330
$ git commit --amend # and then reword the message
$ git push <your-remote-here> +issue1330
```

**Comment by LarsGit223** [comment]
Ahh...thanks. The info that I had was that ```git commit --amend``` could only be used if the change was not pushed yet. So that info seems to be wrong.

**Comment by elextr** [comment]
@LarsGit223 its correct that you should not force push changes to public repositories that lots of people will pull from, but for a pull request in its own branch its fairly safe.

**Pull request closed without merging**
