### PR TITLE
javascript: Add support for ECMAScript 6 classes keywords

### PR DESCRIPTION
**Pull request by cjmayo**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
http://www.ecma-international.org/ecma-262/6.0/#sec-keywords
http://www.ecma-international.org/ecma-262/6.0/#sec-constructor

### CODE REVIEW

**Comment by cjmayo** [comment]
tagmanager/ctags/js.c needs updating too - for symbol explorer to work?

**Comment by elextr** [comment]
LGBI

For the tags parser, its probably better to make a pull request upstream on the re-rejuvenated ctags [project](https://github.com/universal-ctags/ctags) (if its not already done or in progress) and report back when its accepted so we can import it into Geany.

**Comment by cjmayo** [comment]
When searching I missed already reported Issue #934.

This references ctags Issue universal-ctags/ctags#780.

**Comment by ZatsuneNoMokou** [comment]
Does it mean that there will be a release soon?

**Comment by elextr** [comment]
@ZatsuneNoMokou click on the "Milestone" heading to the right to see when releases are scheduled.

**Pull request merged**
