### PR TITLE
Recognize .exp (Expect) files as Tcl

### PR DESCRIPTION
**Pull request by simark**
Expect [1] scripts filenames generally end in .exp, although the code
itself is actually in Tcl.  I find my self manually selecting Tcl quite
often, so I think it would be nice if Geany would recognize it direcly
as Tcl.

[1] http://expect.sourceforge.net/

Signed-off-by: Simon Marchi <simon.marchi@polymtl.ca>

### CODE REVIEW

**Comment by elextr** [comment]
LGBI, .exp isn't used for anything else likely to be commonly opened in Geany.

**Comment by simark** [comment]
Hmm sorry, what does LGBI stand for?

**Comment by elextr** [comment]
Sorry, our standard acronym when it looks ok, but hasn't been tested personally, "Looks Good By Inspection". :smile:

**Comment by simark** [comment]
Ah ok, thanks!

**Comment by simark** [comment]
I just noticed this is still open.  Is there anything else I should do to get it merged?

**Comment by simark** [comment]
Ping!

**Comment by codebrainz** [comment]
Merged in 13ef73d109ad6fba3189b2f69c3c88b3f30e9772

**Comment by elextr** [comment]
@simark thanks for the ping, we is just forgetful :)

**Comment by simark** [comment]
Nice, thanks!

**Pull request closed without merging**
