### PR TITLE
Adds a simple Asciidoc lexer for Scintilla

### PR DESCRIPTION
**Pull request by ancebfer**
Simple Asciidoc lexer following Asciidoctor recommended practiques:

https://asciidoctor.org/docs/asciidoc-recommended-practices/

Tested with Asciidoctor README.adoc file:

https://github.com/asciidoctor/asciidoctor/blob/main/README.adoc

With the next result:
geany

PD: Sorry but GitHub doesn't allow to create PRs from a branch (ancebfer/geany 1.38.1) to a tag (geany/geany 1.38.0) as desired.

### CODE REVIEW

**Comment by elextr** [comment]
Geany is updating from Scintilla 3.5 used in 1.38 to Scintilla 5, currently 5.1.1 but probably 5.1.4 to be released in a few days.  Your lexer needs to be built for that.

The Geany project does not maintain Scintilla or the lexers ourselves but send all issues and improvements upstream.  The lexers are now separated into the Lexilla project so you need to submit it there (in github happily) and it can be added to Geany from there.

**Comment by ancebfer** [comment]
Following your recommendations, I have create a PR to Lexilla:

https://github.com/ScintillaOrg/lexilla/pull/39

Best regards.

**Comment by ancebfer** [comment]
The Asciidoc lexer is now officially included in Lexilla 5.1.4

Please, let me now when Geany is updated to Lexilla 5.1.4 in order to update a new pull request.

**Comment by elextr** [comment]
See https://github.com/geany/geany/blob/master/scintilla/version.txt

**Comment by ancebfer** [comment]
Thanks, this is exactly what I need. I will monitor for changes in https://github.com/geany/geany/blob/master/scintilla/lexilla/version.txt

**Pull request closed without merging**
