### PR TITLE
Fix gtk-mac-integration not being used when using meson

### PR DESCRIPTION
**Pull request by techee**
I noticed that the integration library isn't used when using meson because it's not added to `deps`.

@kugel- Does the change look good to you?

### CODE REVIEW

**Comment by techee** [comment]
@kugel- Ping.

**Comment by kugel-** [comment]
Alright. Although it means plugins would also link against gtk-mac-integration, which is probably unecessary.

**Review by kugel- — APPROVED** [review]

**Comment by techee** [comment]
> Although it means plugins would also link against gtk-mac-integration, which is probably unecessary.

But does it happen when `deps_for_pc` doesn't contain `mac_integration`? (I added it only to `deps` but not to `deps_for_pc `)

**Comment by kugel-** [comment]
deps_for_pc is only used for the pkgconfig file. deps is used for everything, including geany binary, libgeany and plugins.

**Comment by techee** [comment]
OK, I changed the patch to avoid the unnecessary linking - does it still look OK?

**Comment by kugel-** [comment]
yea

**Review by kugel- — APPROVED** [review]

**Pull request merged**
