### PR TITLE
Add support for python's assignment expressions

### LINKED ISSUE #2169: Python: Assignment Expressions
With 3.8 version python get a feature called `Assignment Expressions`. It should be supported by geany's parser. (in `findVariables`)

```py
if (match := matcher.match(line)):
    print(match)
```

### PR DESCRIPTION
**Pull request by isidentical**
Add support for python's assignment expressions, i believe this resolves #2169

### CODE REVIEW

**Comment by elextr** [comment]
As the directory name hints, most parsers come from the [universal ctags](https://github.com/universal-ctags/ctags) project.  Please provide this upstream first since Geany parsers are being updated to be the same as upstream.  

@techee whats the status of updating the Python parser, there seems to be many Colomban droppings upstream that are not in Geany?

**Comment by isidentical** [comment]
> As the directory name hints, most parsers come from the universal ctags project. Please provide this upstream first since Geany parsers are being updated to be the same as upstream.

It looks like geany's python parser different from ctags' python parser.

**Comment by elextr** [comment]
> It looks like geany's python parser different from ctags' python parser.

Yes, not all of them have been updated yet, but if you make a change to the Geany parser it might get lost when the upstream is copyed to Geany.

**Comment by techee** [comment]
> @techee whats the status of updating the Python parser, there seems to be many Colomban droppings upstream that are not in Geany?

If I remember correctly, Colomban upstreamed all the changes we had so we can just copy the upstream parser. But @b4n will know more.

**Comment by techee** [comment]
So to the original pull request - yes, please create the pull request against the upstream universal ctags project, we'll get the changes when we copy the parser to Geany.

**Pull request closed without merging**
