### PR TITLE
Modify/Extend Stash Settings API

### PR DESCRIPTION
**Pull request by xiota**
General Objective: Give plugins access to Geany prefs so they can check and avoid conflicts or *temporarily* override settings, with minimal to no change to existing code that use stash settings.  Currently only the various settings appear to use stash settings consistently.  When this PR is complete, settings can be exposed to plugins by migrating them to the stash system.

* Add double key type.  [#3004](https://github.com/geany/geany/pull/3004)
* Make StashPref accessible to plugins.  [#3008](https://github.com/geany/geany/pull/3008)
  - Look up Pref by name.  Group must be known.
* Add key comments.
* Make StashGroup accessible to plugins.
  - Keep track of created StashGroup when `stash_group_new()` is called.
  - Lookup StashGroup by name and prefix.
* Override StashPref setting for bool, int, and double.
* Support separate Config and Session.

### CODE REVIEW

**Comment by xiota** [comment]
`stash-example.c` using `stash_group_add_comment()` and `stash_group_add_double()`.
```C
StashGroup *group;
gboolean porcelain_enabled;
gchar *potter_name;
gint stock;
gdouble price;
const gchar filename[] = "/path/data.conf";

/* setup the group */
group = stash_group_new("cup");
stash_group_add_boolean(group, &porcelain_enabled, "porcelain", TRUE);
stash_group_add_comment(group, "porcelain", "Is the cup made of porcelain?");

stash_group_add_string(group, &potter_name, "potter_name", "Miss Clay");
stash_group_add_comment(group, "potter_name", "Who made the cup?");

stash_group_add_integer(group, &stock, "stock", 5);
stash_group_add_comment(group, "stock", "How many do we have?");

stash_group_add_double(group, &price, "price", 1.50);
stash_group_add_comment(group, "price", "How much does the cup cost?");

/* load the settings from a file */
if (!stash_group_load_from_file(group, filename))
	g_warning(_("Could not load keyfile %s!"), filename);

/* now use settings porcelain_enabled, potter_name, stock, and price */
/* ... */

/* save settings to file */
if (stash_group_save_to_file(group, filename, G_KEY_FILE_NONE) != 0)
	g_error(_("Could not save keyfile %s!"), filename);

/* free memory */
stash_group_free(group);
```

**Comment by xiota** [comment]
Example of finding group and pref by name:
```C
StashGroup *group = stash_group_get_group_by_name("cup");
if (group) {
  StashPref *pref = stash_group_get_pref_by_name(group, "price");
  if (pref) {
    msgwin_status_add("%s.%s = %f", group->name, pref->key_name, *(gdouble *)pref->setting);
  } else {
    msgwin_status_add("pref not found");
  }
} else {
  msgwin_status_add("group not found");
}
```

Problem: Doesn't work if used after `stash_group_free()`.

In addition to reviewing memory management... Some potential solutions:
* Rewrite "free" to defer actual deallocation until Geany is being shutdown.  Pro: Minimize changes to existing code, maybe.  Con: "free" doesn't do what it says it will.
* Rewrite code to defer deallocation until Geany is being shutdown.  Pro: "free" does what it says it will.  Con: Probably will require extensive changes to existing code.
* Replace "free" with "free_later" (or some such).  Pro: "free" and "free_later" do what they say they will.  Just need to replace "free" with "free_later" in existing code.  Con: Use of "free" can still prevent the lookup from working.

**Comment by xiota** [comment]
Force push because got git branches mixed up.  `get_stash_groups()` is to make testing easier without recompiling Geany.  Probaby won't be in the final PR.  Functions to access 
```C
GPtrArray *get_stash_groups();  // To make testing easier.  Will probably be removed in final PR.

StashGroup *stash_group_get_group(const gchar *group_name, const gchar *key_name);

StashPref *stash_group_get_pref_by_name(StashGroup *group, const gchar *key_name);
```
Example - list all groups and names:
```C++
  GPtrArray *test = get_stash_groups();

  gpointer item;
  guint i;
  foreach_ptr_array(item, i, test) {
    if (item) {
      StashGroup *group = (StashGroup *)item;
      msgwin_status_add("group = %s", group->name);
    }
  }
```
Output:
```
group = geany
group = geany
group = geany
group = geany
group = geany
group = build-menu
group = geany
group = search
group = search
group = search
group = search
group = plugins
group = geany
group = VTE
```
Notably, in `keyfile.c`, groups with the same name (geany and search) are created multiple times.  Why?  Is it necessary?  Would it work if the old group with the same name is returned instead of a brand new group?

**Comment by xiota** [comment]
Example, looking up a Geany group and pref:
```C++
  StashGroup *group = stash_group_get_group("VTE", nullptr);
  StashPref *pref =
      stash_group_get_pref_by_name(group, "send_selection_unsafe");

  if (group && pref) {
    msgwin_status_add("%s.%s = %d", group->name, pref->key_name,
                      *(gboolean *)pref->setting);
  }
```
Output:
```
VTE.send_selection_unsafe = 0
```

**Comment by xiota** [comment]
Over-ride example:
```C++
  StashGroup *group = stash_group_get_group("geany", "interface");
  StashPref *pref =
      stash_group_get_pref_by_name(group, "warn_on_project_close");
  if (group && pref) {
    stash_group_pref_set_override(pref, (gpointer) true);
  }

  stash_group_pref_unset_override(pref);
```

**Comment by kugel-** [comment]
Can you please break this into multiple PRs? I'm not sure if all changes are truly useful. I would start by exposing what's currently implemented and then add functionality on-top in separate PRs.

**Comment by xiota** [comment]
@kugel- What changes are you not sure will be useful?

**Comment by xiota** [comment]
Force push because it's easier to work with a single commit when figuring out how to separate into separate PRs.

**Comment by xiota** [comment]
@kugel- first PR split from this one #3004.  Will split others as they're accepted/merged.

**Pull request closed without merging**
