### PR TITLE
Use union to store StashPref default values

### PR DESCRIPTION
**Pull request by kugel-**
This gives better type-safety than casting everything to gpointer.

### CODE REVIEW

**Comment by elextr** [comment]
LGBI

**Comment by xiota** [comment]
LGBI = local government borrowing initiative?

**Comment by elextr** [comment]
> LGBI = local government borrowing initiative?

Looks Good By Inspection, ie not actually built or tested, its an EFLA (elextr four letter acronym).

**Comment by xiota** [comment]
Need to add a new entry to [EFLA](https://acronyms.thefreedictionary.com/EFLA).

**Comment by xiota** [comment]
Built and Geany seems to run okay.  No new error messages in the terminal (only from plugin manager).  Various settings look intact.  Plugins that I use run okay.  `stash-example.c` works as expected.

**Pull request merged**
