### PR TITLE
RFC: Pre-release version bump to 2.0

### PR DESCRIPTION
**Pull request by eht16**
Since we are going towards the next release and we were thinking about a magic 2.0 version number already for some time, maybe the time is now to just do it :).

Any objections?

@elextr @kugel- @techee @b4n @frlan

### CODE REVIEW

**Review by kugel- — APPROVED** [review]

**Comment by kugel-** [comment]
I'm on the 2.0 band wagon since a long time :-)

**Comment by techee** [comment]
No objections at all.

(While I was a vocal proponent of the 1.xx release to "make Geany stable", I'm kind of neutral here. But in the spirit of linux kernel numbering "when the number behind the dot gets too big, let's bump the major version", it's a good move.)

**Comment by b4n** [comment]
I don't care actually, I'd have went with 1.23456789 until the end of times, but I'm not saying it's a good idea :smile: 
If you like 2.0, let's do it.

**Comment by eht16** [comment]
> stable", I'm kind of neutral here. But in the spirit of linux kernel numbering "when the number behind the dot gets too big, let's bump the major version", it's a good move.)

I didn't know this is the Linux kernel numbering scheme but it's pragmatic :). Actually, I happened to confused myself a few times in the past by not exactly remembering if the current version is 1.37, .38 or .39.
2.0 vs 2.1 is really easier to remember and distinguish.


> I don't care actually, I'd have went with 1.23456789 until the end of times, but I'm not saying it's a good idea 😄 If you like 2.0, let's do it.

We just need to reach 3.1 and then all following releases will give one more precision level of pi. In a few years we might have 3.141592 or so :).

**Comment by elextr** [comment]
> Actually, I happened to confused myself a few times in the past by not exactly remembering if the current version is 1.37, .38 or .39.

IIRC that was Linus's excuse for bumping the Linux major version, out of fingers and toes :-)

> In a few years we might have 3.141592 or so :).

Isn't that the Tex versioning scheme?

**Pull request merged**
