### PR TITLE
Update Nim filetype config

### LINKED ISSUE #2669: Nim configuration is broken
When open a .nim file or creating an project with a .nim file
The Build pull down menu doesn't offer the 'Compile' button.

### PR DESCRIPTION
**Pull request by ZoomRmc**
Keywords taken from official manual: https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords
Identifiers list expanded with:

1. Some basic types from the [System module](https://nim-lang.org/docs/system.html) which is always implicitly imported.

2. Additional keywords (`lent, spawn, parallel`) from Nim [experimental features](https://nim-lang.org/docs/manual_experimental.html#view-types).

Styling and build-menu settings taken from @HJarausch config in #2669

Fixes #2669

### CODE REVIEW

**Comment by elextr** [comment]
Can a nim user test and comment?

**Comment by ire4ever1190** [comment]
Nim user here, new keywords/types seem to highlight correctly :+1:

**Comment by ZoomRmc** [comment]
Current settings use Python lexer for Nim files, however Lexilla already has a [lexer for Nim](https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexNim.cxx).
This requires an additional PR, but I don't know the process of incorporating scintilla/lexilla updates Geany uses, so, please, advice.

With Python lexer multiline comments (and, perhaps, something else) don't work.

**Comment by elextr** [comment]
Probably best to wait for the new Scintilla to be merged to Geany before adding Lexilla parsers.

**Comment by ZoomRmc** [comment]
@elextr what need to be done to move forward with this?

**Comment by elextr** [comment]
I guess since another Nimist has commented this can be merged.

As for adding Lexers or parsers, that needs somebody who is interested to make a PR.

**Pull request merged**
