### PR TITLE
Set default 'search not found' dialog to 'Find'

### PR DESCRIPTION
**Pull request by crazyBaboon**
this way the user only has to press enter in the 'search not found' dialog to wrap search

### CODE REVIEW

**Comment by elextr** [comment]
please remove dialogs.c~

**Comment by crazyBaboon** [comment]
done!

**Comment by codebrainz** [comment]
Won't this affect all dialogs that use these functions, and also change the order of the buttons?

**Comment by elextr** [comment]
@crazyBaboon you are aware of `Edit->Preferences->General->Miscellaneous->Always wrap search`?

**Comment by crazyBaboon** [comment]
Yes, and IMO they should be set to default TRUE. I have managed to change their state to be checked by default, but the wrapping action was not happening. I added to line 429 of prefs.c:

`+       widget = ui_lookup_widget(ui_widgets.prefs_dialog, "check_always_wrap_search");
+       gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(widget), prefs.beep_on_errors);
`
But this change only changed the GUI state of the wrap checked button, and the actual search was still not wrapping anything. Do you guys know how to default the search action to wrapping?

**Comment by elextr** [comment]
> but the wrapping action was not happening.

So did you report that?  I can't find an issue that fits.  And it works for me with latest Geany git.

Basically it appears you made this PR that has the problems @codebrainz pointed out without reporting the problem with the existing functionality that did exactly what you wanted?

> Yes, and IMO it should be set to default TRUE.

Well, you only have to set it once and its remembered.

**Comment by crazyBaboon** [comment]
> So did you report that? I can't find an issue that fits.

I don't think it is a problem. It is just I toggled the checkbutton in the UI logic. Should this change propagate automatically into the search logic?

>  And it works for me with latest Geany git.

If you delete .config/geany does it still work? It does not for me and I am working also with the git version of Geany.

> Well, you only have to set it once and its remembered.

But why even set it once? What is the point in that? Should it not be on by default?

**Comment by elextr** [comment]
>  It is just I toggled the checkbutton in the UI logic. Should this change propagate automatically into the search logic?

I'm not sure I understand you? If you set "always wrap search" preference and apply/ok the preferences dialog then yeah it should "propagate" to the search logic so searches always wrap.

> Should it not be on by default?

So why not just open an issue to change that? :grin:

For reference the wrap option was split from a combined option [here](https://github.com/geany/geany/commit/4ffbd8f9ada26ed8d288865e910e96dbe5250bfc) as a result of the discussion in the Geany ML [thread](https://lists.geany.org/pipermail/devel/2011-December/006072.html) which basically makes the decision to keep it off as it was before, since there is no good reason for either provided, and since there are no statistics on what would be preferred.  So you need to provide some better justification than personal preference to change it, see the ML thread.

**Comment by crazyBaboon** [comment]
> For reference the wrap option was split from a combined option here as a result of the discussion in the Geany ML thread which basically makes the decision to keep it off as it was before, since there is no good reason for either provided, and since there are no statistics on what would be preferred.

Statistics can only be obtain there are lots of users - I am unsure whether Geany fits that category.

> So you need to provide some better justification than personal preference to change it, see the ML thread.

ok I can see this discussion will go nowhere, so I leave it here.

**Comment by ntrel** [comment]
Closing as changes affect multiple dialogs.

**Pull request closed without merging**
