### PR TITLE
adding FORTH ctags

### PR DESCRIPTION
**Pull request by farvardin**
this PR is adding the ctags for FORTH. It's very simple, it only detects the ":" for the beginning of a word:

image

Possible improvements:

- it could write "words" instead of "section" in the symbol list
- it could only parse the first word after the ":", and not the eventual code after it

### CODE REVIEW

**Comment by elextr** [comment]
Please have the parser accepted upstream first, even though its very simple it adds work to updating ctags to check if a change breaks it.

Also without `geany_` on the name, being a parser in Geany without an upstream, it will break `scripts/update_ctags.py` (perhaps the script could be more resilient, but on the other hand it indicates that an upstream parser has been moved or renamed, so it _should_ stop).

**Comment by farvardin** [comment]
> Please have the parser accepted upstream first, even though its very simple it adds work to updating ctags to check if a change breaks it.
> 
> Also without `geany_` on the name, being a parser in Geany without an upstream, it will break `scripts/update_ctags.py` (perhaps the script could be more resilient, but on the other hand it indicates that an upstream parser has been moved or renamed, so it _should_ stop).

I'm in the process of doing it, and the forth.c file had been converted to a forth.ctags for optlib. 

https://github.com/universal-ctags/ctags/pull/3810

There is an automated forth.c generated from the optlib code. It's located there: https://github.com/universal-ctags/ctags/blob/18f4f91fc18893a5e984bff3018e159b4e97c46f/optlib/forth.c

I have problems to compile it, this is giving me those errors:

```
parsers/forth.c:44:12: error: ‘parserDefinition’ {aka ‘struct sParserDefinition’} has no m
ember named ‘versionCurrent’
44 | def->versionCurrent= 0;
| ^~
parsers/forth.c:45:12: error: ‘parserDefinition’ {aka ‘struct sParserDefinition’} has no m
ember named ‘versionAge’ 45 | def->versionAge = 0;
```

does geany handles optlib?

https://docs.ctags.io/en/latest/optlib.html#translating-an-option-file-into-c-source-code-optlib2c

**Comment by elextr** [comment]
> does geany handles optlib?

The optlib directory of ctags is not imported to Geany, so probably not.

**Comment by techee** [comment]
Fixed by #4013.

**Pull request closed without merging**
