### PR TITLE
Autodetect .bashrc, .bash_aliases, and the like

### PR DESCRIPTION
**Pull request by bittner**
This minor change allows Bash files typically resident in a user's home directory to be detected for syntax highlighting.

### CODE REVIEW

**Comment by eht16** [comment]
@bittner would you mind squashing your commits to get it into one commit before merging?

Thanks.

**Comment by bittner** [comment]
Ahh, this is ages ago. If you really need this, okay. I'll try.

How do I do that? (Sorry, not sure how to clean up my existing commits -- except for `git push --force` after local changes.)

**Comment by bittner** [comment]
Done.
``` bash
$ git rebase -i HEAD~3
$ # Replace "pick" by "squash" in the two older commits
$ git push --force
```
Scary.

**Comment by eht16** [comment]
Thanks, merged.

**Pull request merged**
