### PR TITLE
Cast windows HANDLE to intptr_t, not long

### PR DESCRIPTION
**Pull request by zhekov**
The cast in g_warning is not fixed. It's unimportant, displaying a
handle value does not provide any meaningful information anyway.

### CODE REVIEW

**Comment by b4n** [comment]
Looks like mingw doesn't like the extra `()` around the cast.

Otherwise LGTM

**Comment by zhekov** [comment]
And (( )) are not required either, they are simply a syntax error, since I changed the branch in the last moment...

**Comment by zhekov** [comment]
The last check, GTK3=yes MINGW=yes, failed with:

curl -L -# http://win32builder.gnome.org/gtk+-bundle_3.8.2-20131001_win32.zip
curl: (7) couldn't connect to host

I had problems with http://ftp.gnome.org earlier today.

**Comment by elextr** [comment]
NOTE: the [GTK for windows](http://www.gtk.org/download/windows.php) page says "The preferred way to obtain GTK+ and its dependencies in binary form for Windows is to use the MSYS2 project."  Perhaps we should do that.

**Comment by zhekov** [comment]
msys2 has no "gtk+ bundle". You need to fetch the base msys2, so that at least bash and pacman will work, and then install gtk+ 32/64 with pacman, which will in turn install all dependencies, and execute their pre/post install scripts. I'm not sure we can package "geany with gtk+" using msys2. It's possible in theory, but practically...

**Comment by b4n** [comment]
NVM the second failure, one succeeded that's alright.  and i tried it locally cross-building and it's fine too :)
Anyway, committed a (manual) merge of the 2 patches.  Thanks!

**Pull request closed without merging**
