### PR TITLE
Rust: Rename int/uint type names to isize/usize

### PR DESCRIPTION
**Pull request by crumblingstatue**
These were renamed in rust.

### CODE REVIEW

**Comment by b4n** [comment]
I can't find no reference to those at http://doc.rust-lang.org/reference.html#suffixes yet I can find all kind of references to `int` and `uint`, so… rationale?

Also, @SiegeLord, same question, could you give your opinion on that? :)

**Comment by crumblingstatue** [comment]
@b4n: Looks like the reference wasn't updated. There is an open pull request on updating it: rust-lang/rust#21004

**Comment by SiegeLord** [comment]
Yeah, just a case of an outdated reference. In terms of highlighting suffixes, this is something that needs to be done on Scintilla's side, and it on my TODO list. I am, however, waiting for Rust 1.0 proper released, so there won't be any more syntactical changes, and would suggest for anybody thinking of making those changes to do the same.

**Comment by crumblingstatue** [comment]
@SiegeLord I've already submitted a [patch](https://sourceforge.net/p/scintilla/feature-requests/1098/) to Scintilla.

**Comment by crumblingstatue** [comment]
Closing this PR, as I'm not interested in working on it anymore.

**Pull request closed without merging**
