### PR TITLE
email to Email

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by elextr** [comment]
@scootergrisen good catch

**Comment by b4n** [comment]
Please don't merge string changes after the string freeze;  now we need to update all po files manually to keep on translating this string.
This is a good catch, but should have landed after the release or before the string freeze.

**Comment by b4n** [comment]
@frlan should we manually update all those string, hopefully being able to add the caps if it's not there? (I can probably do that for ASCII-ish languages, probably not for others).
Or should we revert the change?
Or should we just update the .po files hope that already updated translations will catch up, and that new ones will be submitted with this?

**Comment by frlan** [comment]
Please go on. I will check for this fuzzy string before finishing ciycle.

**Pull request merged**
