### PR TITLE
Add me to COMMITTERS

### PR DESCRIPTION
**Pull request by codebrainz**
Don't merge, just testing online Github editing to see if it creates a branch on Geany repo and triggers a commit mail.

### CODE REVIEW

**Comment by codebrainz** [comment]
No commit mail or branch created, closing.

**Comment by elextr** [comment]
@codebrainz thats because you edited `codebrainz:` not `geany:`.  You get commit emails & IRCs  because our bot is not smart enough to distinguish commits to master from commits to branches.

**Comment by codebrainz** [comment]
Yeah, I thought that was the normal way of doing the online editing. I do want commit mails on Geany repo branch commits, just not for random PRs.

**Comment by b4n** [comment]
@codebrainz just tell @elextr not to online-PR from the Geany repo ;)

**Comment by eht16** [comment]
> @codebrainz thats because you edited `codebrainz:` not `geany:`. You get commit emails & IRCs because our bot is not smart enough to distinguish commits to master from commits to branches.

"not smart enough" is by design in this case.
Commit mails and IRC messages are sent for any push in the Geany (and G-P as well) repository. This also includes any branches besides `master`.
In this case, the branch was `elextr-patch-4` of Lex simple change but this is also true for sub release branches like the current `1.34` branch.

IMO it is good to have commit mails also for branches besides master.

Apart from that, I completely support what Lex said above about minimizing restrictions for contributions.

**Comment by b4n** [comment]
@elextr agreed, I don't blame it, and don't particularly care for those commit emails.  I just wish it could automatically do that on the contributor's fork (or fork it automatically if need be) rather than on the main repo so things would be cleaner, but it's not a problem.

The problem last time was just me not reviewing/testing properly :grin:

**Comment by codebrainz** [comment]
To be clear, I'm not really opposed to using Github to make edits+PRs[0], I just wanted to see how it worked because I hadn't tried it before and it seemed odd that Github was messing with the main repo in order to make PRs. Now I realize it lets people with push access edit+PR directly on the main repo and doesn't force you to do it on your own fork, which is the only part I don't like much.

[0]: for small text/documentation changes. I do think PRers should at least test code changes themselves on their machine as a minimum bar though (which _was_ done last time), at which point it's no faster re-doing the changes in the online editor instead of just pushing to your fork and making a PR. From this point of view, the online editor isn't terribly useful, IMO.

**Comment by elextr** [comment]
For small text/documentation changes I totally disagree, if someone wants to make a few word changes to make docs clearer why force them to install some obscure document processing system just to make a PR.

 Thats what I mean by putting artificial restrictions in their way.  Its the job of Travis and the nightlys to check they don't do something that breaks the build.

**Comment by elextr** [comment]
@codebrainz oh, there is a full stop after "changes" in your footnote, I read it as one sentence.  We are in vociferous agreement then :)

**Pull request closed without merging**
