### PR TITLE
Correcting instructions, you still need autotools when building from release tarball

### PR DESCRIPTION
**Pull request by arthrp**
…n building from release tarball

### CODE REVIEW

**Comment by b4n** [comment]
Why would you need to run autogen (and thus need Autotools) from release tarballs?  They should be including everything you need.

Note that GitHub's "source code" automatic downloads are *not* release tarballs, release tarballs should be downloaded from https://www.geany.org/download/releases/

**Comment by arthrp** [comment]
In that case it should state that clearly IMO. Quite sure I'm not the only one confused.

**Comment by codebrainz** [comment]
> Note that GitHub's "source code" automatic downloads are not release tarballs

At first I thought you were talking about the "Clone or Download" button that lets you download the repo in a zip file, which seems obvious that it's not a "release tarball", but upon closer inspection, if you click "Releases" tab along the top and then grab the actual tarball presented for the release, it appears to just be a tarball of the VCS source, without the `configure` script and `Makefile`s and such already generated. I could see this being confusing.

I wonder if there's a way to get Github Releases page to link to the actual release tarball instead of the non-release tarball confusingly linked there?

**Comment by b4n** [comment]
@codebrainz I'm afraid that won't remove/replace the auto-generated zip/tar of the VCS tag; but yes we could upload the items there as well.  But as "incorrect" auto-generated GitHub links are still there, nothing will be solved.  I hope I'm wrong tho.

I blame GitHub here if it's not possible to disable this, because it clearly goes against a clearly implanted meaning of "release tarball", and apparently confusing users to expect this is more than a Git snapshot. Or maybe the problem is GitHub becoming the only place people look, or maybe it's our fault listing releases on GitHub… anyway, this sounds quite bad as if the OP bothered reporting this, it's highly likely there are many other people having had similar issues, that might or might not have just given up at this step because of apparently bad advertising.

**Comment by b4n** [comment]
OK I just tested uploading assets to 1.36 release: https://github.com/geany/geany/releases/tag/1.36.0
As I expected, it didn't remove the "source code" downloads.

**Comment by codebrainz** [comment]
> OK I just tested uploading assets to 1.36 release.

Actually that's still quite a bit better IMO, at least it forces people to think about which one to download. It would be nice if Github let you put a description for each file so you could put "Release tarball for all platforms", "Release bundle for Macos", "Source code snapshot", etc.

**Comment by elextr** [comment]
Seems good to me, @b4n just needs to add uploading to github it to the release script.

**Comment by b4n** [comment]
Actually apart from saving bandwidth, I'd rather have people go to https://www.geany.org/download/releases/ and all the extras, like the opportunity to check check the signatures or whatnot.  But well…

**Comment by codebrainz** [comment]
@b4n could always put something at the very top of each release description instead:

> **Note:** To download this release, please visit [the official release page](https://geany.org/download/releases/). The "Source code" downloads below are generated automatically by Github without any option to disable them, and _do not_ represent actual released source code packages.

**Pull request closed without merging**
