### PR TITLE
OS X integration

### PR DESCRIPTION
**Pull request by techee**
Alright, more of OS X (aka "The World's Most Advanced Operating System") :-).

This set of patches uses the gtk-mac-integration library here

https://git.gnome.org/browse/gtk-mac-integration/

for

1. Locating various Geany files within the app bundle.
2. Using the global menubar
3. Possibility to open Geany by right-clicking files in Finder and using "Open with" and opening projects by right-clicking them
4. Adding the possibility to open new instance of Geany from the launcher
5. Various nice-to-haves

Now get ready that without OS X you won't be able to compile the code protected by #ifdef MAC_INTEGRATION (about all the code from these patches) so it will be kind of blind review. There's some overview of the gtk-mac-integration library and the used functions in the docstring here:

https://git.gnome.org/browse/gtk-mac-integration/tree/src/gtkosxapplication.c

This should be about it regarding the OS X support, I have no more patches in my sleeve, I promise :-).

### CODE REVIEW

**Comment by techee** [comment]
I had a look at the code in gtk-mac-integration to know what's happening there and to see if things can be fixed there rather than adding hacks to Geany. Here's a quick description of how the menu thing works:

When the menu integration mode is enabled, there are actually 2 menus in the application all the time - the Gtk one (hidden) and the native OS X one and they are kept in sync. First, the osx menu is recreated based on the gtk one. All events from osx menu are passed using gdk_threads_add_idle() to the gtk menu and then processed there (the corresponding Gtk menu entry gets activated). In the opposite direction gtk->osx menu, there's a similar path for "sensitive", "visible", "active", "inconsistent", "submenu" signals of the gtk menu for which the integration library listens and performs the equivalent with the osx menu. In addition for each gtk item there's an emission hook for "parent-set" to handle additions/removals of items in the menu and syncing these changes to the osx menu.

Now there are 2 problems we hit with Geany:

1. First I thought that dynamic menu creation doesn't work but actually the only thing that doesn't work is the gtk_menu_reorder_child() function - simply for the reason that it doesn't emit any signal and the integration library is completely blind here. So for this function I'm afraid we'll need to sync the menu manually (it's used in ui_utils 3x only, we could create a single function which performs the osx menu syncing and have this at a single place there).

2. OS X doesn't have "physical" radio items in the menu - if you want them, you have to select-deselect the menu items manually in the code so just one of several is checked. This means that the usual syncing using e.g "active" signal isn't sufficient because the osx menu wouldn't know which items are in the group and which should get unchecked. So for now this isn't handled but I think there should be no problem perform the full menu resync once the radio item gets activated in the Gtk menu. I've submitted the patch here:

https://bugzilla.gnome.org/show_bug.cgi?id=744596

So hopefully if it gets merged, we won't need to do any hackery in Geany. (Even though I haven't tried, I think connecting the menu, listening there and resyncing when clicked wouldn't work properly because the Gtk menu gets the event on idle after the osx menu is already clicked.)

**Comment by techee** [comment]
One more issue - I have noticed that when using "Override Geany keybindings" in the VTE dialog doesn't return the keybindings back to Geany. The reason is the connection to the signals here

https://github.com/geany/geany/blob/master/src/keybindings.c#L1165

which don't get emitted. Why are the menu's draw and expose-event used for this? I tried the same what is done later in the code for the editor menu, i.e. just setting it back to sensitive in an idle function, and it works for me.

(Even though I haven't tried, I think also Ubuntu's global menubar would have problems with the existing code.)

**Comment by b4n** [comment]
> 1. First I thought that dynamic menu creation doesn't work but actually the only thing that doesn't work is the gtk_menu_reorder_child() function - simply for the reason that it doesn't emit any signal and the integration library is completely blind here. So for this function I'm afraid we'll need to sync the menu manually (it's used in ui_utils 3x only, we could create a single function which performs the osx menu syncing and have this at a single place there).

OK, fair enough.  BTW, although two of the use cases are legitimate, one of them already acknowledges being a hack, so I guess it's not so bad.

>  2.  OS X doesn't have "physical" radio items in the menu - if you want them, you have to select-deselect the menu items manually in the code so just one of several is checked. This means that the usual syncing using e.g "active" signal isn't sufficient because the osx menu wouldn't know which items are in the group and which should get unchecked. So for now this isn't handled but I think there should be no problem perform the full menu resync once the radio item gets activated in the Gtk menu. I've submitted the patch here:
>
> https://bugzilla.gnome.org/show_bug.cgi?id=744596

I didn't check the code, but wouldn't it be preferable to listen to the `:toggled` signal of each `GtkCheckMenuItem` and update them alone?  IIUC this one should get emitted whenever a radio item changes state, it being the selected one or the one getting deselected.  This would avoid having to rebuild the whole menu hierarchy (if the machinery behind it is able to do that, of course).

> One more issue - I have noticed that when using "Override Geany keybindings" in the VTE dialog doesn't return the keybindings back to Geany. The reason is the connection to the signals here
>
> https://github.com/geany/geany/blob/master/src/keybindings.c#L1165
>
> which don't get emitted. Why are the menu's draw and expose-event used for this? I tried the same what is done later in the code for the editor menu, i.e. just setting it back to sensitive in an idle function, and it works for me.

I really have no clue, but indeed if I understand what that code is supposed to achieve (I may not, I don't know for sure), an idle callback should be just fine (and less crazy).
If it works, I guess we can just go ahead an do it, and worry later if it actually happen to break something.

**Comment by techee** [comment]
>
>
>  I didn't check the code, but wouldn't it be preferable to listen to the
> :toggled signal of each GtkCheckMenuItem and update them alone? IIUC this
> one should get emitted whenever a radio item changes state, it being the
> selected one or the one getting deselected. This would avoid having to
> rebuild the whole menu hierarchy (if the machinery behind it is able to do
> that, of course).
>
Wonderful! I didn't know about the signal. Great to know someone who
actually knows Gtk :-)

**Comment by techee** [comment]
Here's a new set of patches:
* it uses a single function to determine the right resource path (it really makes things a lot cleaner)
* it drops the manual refreshes of radio menu entries (hopefully my patch gets merged in the integration library)
* leaves preferences in Edit
* addresses various comments raised in this thread
* drops the icon jump after long running operations (non-essential, can be added later)
* fixes the VTE keybinding problem

With osx.c/h and autoconf/waf I got a bit lazy and build them even on non-osx operating system. Inside they are protected with the MAC_INTEGRATION macros so no code from it compiles. Is it sufficient this way?

@kugel- To your comment I should include config.h in osx.h - it's actually not necessary because I'm checking the MAC_INTEGRATION macro which is defined on command-line (defined by pkg-config) and not the HAVE_MAC_INTEGRATION from config.h

**Comment by techee** [comment]
By the way, regarding the VTE keybinding issue, I think this bug might be it:

https://sourceforge.net/p/geany/bugs/1081/

**Comment by techee** [comment]
Yet another problem I didn't notice before - the File->New with template submenu didn't exist. This was because of connecting show/hide signals which don't work (more in the patch description).

For the future it would be good to keep in mind that the GtkWidget things don't work with the global menu on OS X and Ubuntu Unity so better just use methods/signals from GtkMenuItem and subclasses.

**Comment by elextr** [comment]
Reminds me to ask, do the dynamic menus (like build) work?

**Comment by techee** [comment]
> Reminds me to ask, do the dynamic menus (like build) work?
>
Yes, they work without any problem (it's thanks to the "parent-set"
emission hook I described earlier in the thread).

**Comment by b4n** [comment]
> With osx.c/h and autoconf/waf I got a bit lazy and build them even on non-osx operating system. Inside they are protected with the MAC_INTEGRATION macros so no code from it compiles. Is it sufficient this way?

yeah, who cares such a small file anyway

**Comment by b4n** [comment]
>By the way, regarding the VTE keybinding issue, I think this bug might be it:
>
>https://sourceforge.net/p/geany/bugs/1081/

As it seem to really fix it indeed, could you be so kind and link that bug in the commit as something like "Fixes https://sourceforge.net/p/geany/bugs/1081/"?  :)

**Comment by techee** [comment]
I've pushed the various fixes (hope I haven't forgotten anything) - they are separate to make them easier to review, I'll squash them later once you consider the branch ready for merging (at which point I'll also mention the bug fix in the comment).

I've also included the adaptive scrolling patch which is already in scintilla master so there's everything osx-related in Geany.

**Comment by b4n** [comment]
LGTM, unless I missed some stuff earlier -- but I prefer do a last pass just before actually merging if you don't mind, so you can squash as you wish :)

**Comment by techee** [comment]
Here are the squashed patches. 

I made one additional change to the file open callback signal implementation. For some reason, when the project was opened from commandline and the warning about project being open appeared, Geany crashed once the dialog was closed (somewhere in osx frameworks, it seemed that it couldn't free the path parameter of the callback for some reason). Interestingly, there was no crash when the same happened when clicking the project file in finder (even if the same dialog appeared). It seems there's some problem when the signal handler is blocked by this dialog so I moved this part to an idle function so the signal handler isn't blocked.

**Comment by b4n** [comment]
Apart that my compiler and I are happy :)

**Comment by techee** [comment]
Repushed with the issues addressed.

**Comment by b4n** [comment]
Looks good, merged :)

**Comment by techee** [comment]
Great! And as always, thanks for the fantastic code reviews!

**Pull request merged**
