### PR TITLE
work on adding multi-select

### PR DESCRIPTION
**Pull request by Ryan1729**
add some multiselect wrappers, set multiple selection to true and call sci_add_selection on ctrl-click

### CODE REVIEW

**Comment by Ryan1729** [comment]
This is currently not working. I've assigned adding a selection to ctrl-click, and rotating the selection, (making the nest selection the main selection, which I expected to make the selection show up in the UI,) to ctrl-right-click.

I've also had it print out how many selections there are after each of those steps. If you ctrl-click then ctrl-right-click, by the time you get to the ctrl-right-click, Scintilla says there is only 1 selection!

**Comment by elextr** [comment]
Marked `work in progress` since it simply deletes existing functionality, and that is unacceptable.

**Comment by elextr** [comment]
If Scite does what you want, look at its code for hints.

**Comment by elextr** [comment]
> This is currently not working. 

If you just want to ask a question its probably better to leave the code _in a branch_ your github fork and point to it from an issue, rather than making a pull request.

**Comment by Ryan1729** [comment]
> If you just want to ask a question its probably better to leave the code in a branch your github fork and point to it from an issue, rather than making a pull request.

Fair enough. I've seen some other projects put work in progress stuff in pull requests, but if you folks prefer pointing to branches from issues, that's fine with me.

**Comment by elextr** [comment]
Its not a hard and fast rule (Geany has relatively few of them), but if something gets to the point where its actually usable, then doing further development on a pull request is occasionally done, the problem is that anyone contributing more than just comments has to make the pull request to your repo anyway, and pull requests there are not visible on the Geany one until its merged, resulting in two places to be tracked.  Thats a failing of github.

But irrespective of the development method, making all changes in a branch is mandatory, nobody will test something if it changes their master, master should purely track upstream, ie the Geany github repo.  It also helps you too, you can sidetrack your changes simply by checking out a new branch, or back to master to pull down any changes from upstream.

**Pull request closed without merging**
