### PR TITLE
Started Sinhala Translations

### PR DESCRIPTION
**Pull request by Aruna-Hewapathirane**
First set of 10 translations. I looked at zh_CN.po and followed what they have done for accelerators strings. 
msgfmt -c --check-accelerators=_ si.po ( runs, no errors )

### CODE REVIEW

**Comment by eht16** [comment]
Friendly ping @frlan

**Comment by Aruna-Hewapathirane** [comment]
> Friendly ping @frlan

Hello, sorry been busy with life and work :-) what did you want me to do?

**Comment by elextr** [comment]
@Aruna-Hewapathirane @frlan is the Geany translations manager/expert, the ping was for him, not you ;-)

**Comment by Aruna-Hewapathirane** [comment]
> @Aruna-Hewapathirane @frlan is the Geany translations manager/expert, the ping was for him, not you ;-)

Oops! My apologies.. :-)

**Comment by frlan** [comment]
Sorry -- here also busy and got lost in GH noise ;)
Will have a review soonish

**Comment by frlan** [comment]
@Aruna-Hewapathirane  From general point of view it looks good :+1: . Would you mind to rebase your branch on current master and squash the commits into one (or at least a low number of?)

**Comment by Aruna-Hewapathirane** [comment]
> @Aruna-Hewapathirane From general point of view it looks good +1 . Would you mind to rebase your branch on current master and squash the commits into one (or at least a low number of?)

Sure, I will do so soon.

**Pull request closed without merging**
