### PR TITLE
Update Scintilla to version 4.4.5

### LINKED ISSUE #2519: Update to Scintilla 4.x
This is a RFC regarding updating to the current version of Scintilla and getting off of the "fork" of the versions 3.x series (LongTerm3 branch).

The longer we wait to update, especially with the splitting off of lexers from Scintilla itself, we're basically just accumulating technical debt. Eventually the kind fellow currently maintaining the LongTerm3 branch will stop.

As far as I know, the main platforms Geany tries to support all have modern enough compilers/C++ standard libraries by now. There may be some older legacy/LTS platforms with users who won't be able to self-update to latest Geany without more effort, but with such limited developer time/interest/contributions for Geany, I don't think it's unreasonable to make some trade-offs like this in order to ensure Geany doesn't bitrot.

I might be willing to have a look at upgrading the code and build system to work with latest Scintilla, but not if people are opposed, hence this RFC.

### PR DESCRIPTION
**Pull request by kugel-**
Starting with scintilla 4.x I would like to use a new method for import scintilla. 

We keep a side branch scintilla-import that contains just plain upstream scintilla releases, i.e. the unpacked tarballs imported to git. This is done with a helper script achieve a linear history with file deletions properly reflected.

Integrating a release is done simply by merging the specific commit from the scintilla-import branch `git merge scintilla-import`.

The only downside is that we carry the complete tarball but we don't have to track/handle individual files anymore and properly handle deletions. Any changes we make to scintilla are automatically preserved by `git merge`

Fixes #2519

### CODE REVIEW

**Comment by kugel-** [comment]
rebased onto 1.37, picked up smalltalk addition

**Comment by elextr** [comment]
@b4n now 1.37 is out, whats your thoughts on this?

**Comment by kugel-** [comment]
@b4n how to proceed? This has been sitting for a while now.

**Comment by elextr** [comment]
First thought is that for me having all Scintilla backends we don't use in the Geany repository is useless and adds to the cost of cloning and pulling updates.  There is a simple script that separates out the parts we need, why not continue to use that for now with Scintilla 4.  There will be a major upheaval with Scintilla 5 anyway with Neil separating the Lexilla and Scintilla repos, that would be the time to change the approach if neccessary, not once now and again for 5.0.

**Comment by DevynCJohnson** [comment]
@elextr , what are the current plans for upgrading to Scintilla v5? What can help accelerate the upgrade?

**Comment by elextr** [comment]
@DevynCJohnson have opened #2824 to discuss and not pollute this PR.

**Comment by kugel-** [comment]
FWIW, since we now have the Julia parser ported from 5.x (including the C++17 requirement), and because I have to completely redo the update anyway, I decided to skip v4.x and rocket-jump to 5.x. This PR is obsolete now.

**Pull request closed without merging**
