### PR TITLE
Follow up fixes for PR#1456

### PR DESCRIPTION
**Pull request by b4n**
See commits for details.

### CODE REVIEW

**Comment by kugel-** [comment]
LGTM

**Comment by elextr** [comment]
LGTM, @codebrainz?

**Comment by kugel-** [comment]
@codebrainz I think it would be good if this was merged before the release. Please do.

**Comment by codebrainz** [comment]
Looks OK to me, feel free to merge, else I'll try and find some time to test and merge "soon".

**Comment by kugel-** [comment]
Tested OK

**Pull request merged**
