### PR TITLE
Use C parser for GLSL files

### PR DESCRIPTION
**Pull request by techee**
The GLSL portion of c.c doesn't seem to do anything - it's just a synonym
for a C parser which can be used directly instead. This way we can
switch to the new cxx parser for GLSL too and reduce one more language
to care about in c.c.

For reference, the GLSL "parser" was introduced in commit

6ce421f1411060b8576bdac982cca11229b8ef96

### CODE REVIEW

**Comment by elextr** [comment]
Hmm, GLSL has more keywords than C, maybe @b4n meant to add them to the parser but never got around to it.

But in current condition seems ok to switch.  Could GLSL then be a custom filetype?

**Comment by techee** [comment]
> Hmm, GLSL has more keywords than C, maybe @b4n meant to add them to the parser but never got around to it.

Possibly. It's also possible that the other keywords of GLSL aren't so important for parsing (just for styling with scintilla) and that the output just turned out to be acceptable.

> But in current condition seems ok to switch. Could GLSL then be a custom filetype?

I'm not so familiar with scintilla styling and there seems to be done something in the C code right now. In any case, it doesn't matter much and I think it can stay the way it is.

**Comment by elextr** [comment]
WFM with GLSL code from the web.

**Comment by techee** [comment]
I used the UNUSED parser ID here like in the Ferite parser in order not to change other parser identifiers.

**Comment by techee** [comment]
There was one more problem with this pull request - when C parser was used as a dummy parser for the removed entry, there were 2 different instances of the same parser in `tm_parsers.h` and since ctags uses a hash map for the used parsers, true C tags were reported incorrectly as the `UNUSED` tags. So better to use some parser we either don't use in Geany.

However, since we also support CUDA files as an external filetype, we can use the CUDA parser from the cxx parser instead of the C++ parser for CUDA files.

**Comment by techee** [comment]
Had to rebase again because of the merge of GDScript filetype (added GDSCRIPT is alphabetically next to removed GLSL which caused the conflict).

**Pull request merged**
