### PR TITLE
Update to Scintilla 5.1.5 and Lexilla 5.1.4

### PR DESCRIPTION
**Pull request by kugel-**
Scintilla:
  - SCI_GETTEXT, SCI_GETSELTEXT, and SCI_GETCURLINE behaviorial changes
  - Autocompletion on Wayland (see #3009)

Lexilla:
  - New parsers: gdscript (see #3012) and asciidoc (see #2986) but not imported yet

### CODE REVIEW

**Comment by Davidy22** [comment]
I believe there is going to be a little enumeration conflict with the GDScript additions that would need to be resolved, are we merging this first and amending that, or some other approach?

**Comment by elextr** [comment]
If GDscript is part of upstream why is there a conflict since this comes from upstream?

**Comment by Davidy22** [comment]
In the linked PR that has the full GDScript addition that I've created here on the Geany pull request queue, the enumerations in scintilla/lexilla/include/LexicalStyles.iface and  scintilla/lexilla/include/SciLexer.h are slightly different because I set them to 134 when adding them in Geany, but the geany source doesn't have asciiidoc yet which is the one that takes enumeration 134 in upstream so part of the fixes I did when working upstream was changing it to 135.

**Comment by kugel-** [comment]
Well I suggest rebasing your PR after this is merged.

**Comment by kugel-** [comment]
I'll merge this in a week or so in absence of  impeding feedback

**Comment by techee** [comment]
@kugel- IMO it can be merged now so the GDScript pull request can be made ready for merging to Geany.

**Comment by elextr** [comment]
Havn't noticed any problems with running this PR in last couple of weeks although not heavily tested.

**Pull request merged**
