### PR TITLE
Communicate terminal dirty-ness to users in a better way

### PR DESCRIPTION
**Pull request by techee**
While we cannot fix the problem where Geany thinks VTE contains some input while there is none, I think we can at least communicate this issue better to users to avoid reports like

https://github.com/geany/geany/issues/473

1. Users don't see that Geany thinks there's some input in VTE and have no idea about some dirty-ness. I think we can do the same we do with a modified document - display the tab text in red so users see when Geany thinks there's some input in VTE.

2. Tell users what to do to clear the terminal - as I said in the commit message, when I first saw this problem I tried to clear VTE by deleting its contents using backspace which of course won't help.

### CODE REVIEW

**Comment by elextr** [comment]
Good ideas, code LGTM :)

Not related to your change, but maybe the change can make it clearer.  One thing I never understood (as a VTE non-user) what does it mean "contains a command"?  Of course it does, I just told it to execute one?  Or does it mean I have some unexecuted typing in the VTE?  I would guess that confuses others too.

**Comment by eht16** [comment]
@elextr IIRC I added this expression "contains a command". It should mean that Geany thinks there is something on the VTE command line or at least might be and so Geany cannot blindly use the prompt to execute a command from within Geany (remember the famous 'rm -rf / &&' example).
I see that "contains a command" might not be very clear. If you have any suggestions, let us know.

@techee great idea!
Just one question out of my curiosity: why do you use a timeout for setting the terminal to dirty?
Is it just to collect frequent status changes or is there another reason?

**Comment by elextr** [comment]
@eht16 I see, so what it means is the VTE command line is not empty basically?  

So maybe "The VTE command line must be empty to run a command, (press ..."?

**Comment by eht16** [comment]
@elextr exactly and your wording suggestion sounds fine to me.

**Comment by techee** [comment]
@eht16 I mention it in the commit message - it's there to avoid brief red flashes of the Terminal label when you e.g. just press enter. It happens because we set the terminal dirty in vte_commit_cb() and clean it in vte_keyrelease_cb() and there seems to be a brief moment between the two where the terminal becomes dirty.

@elextr The problem with this wording is that from the user's perspective the command line might really be empty even though Geany thinks it's not (type something in the terminal and then delete it with backspace and Geany still thinks it's not empty). So if it's possible the message should be something like "Geany thinks the command line might not be empty". I used

"File not executed because the terminal may contain a command (press Ctrl+C or Enter to clear it)."

but there might be a better way to say that.

**Comment by techee** [comment]
Maybe "may contain a command" could be changed to "may contain some input" or similar.

**Comment by elextr** [comment]
> Maybe "may contain a command" could be changed to "may contain some input" or similar.

Yes, thats better.

**Comment by techee** [comment]
Good, changed the commit to

"File not executed because the terminal may contain some input (press Ctrl+C or Enter to clear it)."

**Comment by codebrainz** [comment]
I always thought this was a bug where geany would get stuck in some bad mode and the VTE wouldn't work (I even used to restart geany when this happened). Couldn't Geany just run it's own command, leaving whatever the user typed (ex. `rm -rf`) alone?

**Comment by techee** [comment]
@codebrainz I can imagine this could be a bit dangerous especially with the automatic change directory feature. Imagine you start typing 'rm -rf *' and want to add just some extension but want to first look into e.g. some makefile what extension it is. So you switch tabs and bam, the command gets executed.

**Comment by codebrainz** [comment]
@techee no, I mean, don't run the `rm -rf` command (or whatever the user started typing), rather save the `rm -rf` command, run the change directory command and put the `rm -rf` (or whatever) back at the prompt.

**Comment by techee** [comment]
@codebrainz How? These are inside the bash process within VTE and there's no way to get them (we could be collecting what user types but we'd have to track caret movements, delete presses, backspace presses etc. and this would get too complicated and also shell-specific). And this would get completely broken if you e.g. run vi inside the shell and start editing there. Also we'd have to restart the bash process because we just can't remove what has been typed inside it which would delete all environment variables the user has used. So I don't see any realistic way to do this.

**Comment by codebrainz** [comment]
@techee I'm not super familiar with VTE, but I assumed when it's line-buffered (ex. at shell prompt) there was a way to extract the text that has been input from the UI after the text the Pty read and put there, or that you could just `write()` the change dir command direct to the Pty fd. I'll experiment with it when I get some free time, don't let my idea/comment stop this PR :)

**Comment by techee** [comment]
@codebrainz The problem is you don't need to communicate with VTE but bash - the command is inside bash and even if you change somehow what VTE displays, bash will still contain the (possibly dangerous) input.

**Comment by b4n** [comment]
LGTM, but I can still see a quick flashing when hitting Return.

**Comment by techee** [comment]
@b4n Is it when you just press enter or when you type something (e.g. 'ls') and press enter. If you type the command in more than 100ms then you will see the flashing. But it shouldn't happen just for enter alone (if so, does it happen even when you increase the value to e.g. 200?).

**Comment by b4n** [comment]
> @b4n Is it when you just press enter or when you type something (e.g. 'ls') and press enter.

just enter

> If you type the command in more than 100ms then you will see the flashing. But it shouldn't happen just for enter alone (if so, does it happen even when you increase the value to e.g. 200?).

At 150 it's already gone for me.

BTW, I tested all this both on GTK2 and GTK3, and it was the same (just to prevent @elextr from drawing the "GTK3 is slow" gun :])

**Comment by techee** [comment]
I've repushed with the changed timeout to 150ms and also change the tab color only in the case when the new clean value differs from the old one (no change needed if they are the same).

**Pull request merged**
