### PR TITLE
Fix #2599 - Save As dialog can save the wrong document

### LINKED ISSUE #2599: Save As dialog can save the wrong document
## Steps to reproduce:

1. Open a document
1. File->Save As
1. Notice an interesting file in the list of files in the dialog
1. Open interesting file from the command-line (in another program) with `geany interesting-file`. The file opens in the background underneath the Save As dialog.
1. Type a new filename and click save

The `interesting-file` document will have been saved with the new filename. The original document will still be open, unsaved.

## Cause

`handle_save_as` is dialogs.c uses `document_get_current`.

### PR DESCRIPTION
**Pull request by ntrel**
Fixes #2599.

### CODE REVIEW

**Comment by elextr** [comment]
LGBI

**Comment by ntrel** [comment]
Ideally we would error when opening a file from the command line when there's a modal dialog open to prevent issues like this. I'm not sure if there's a way of detecting that without adding cases for each dialog.

**Comment by ntrel** [comment]
There's still a case where Save As is used on the only empty new document, and the command line file replaces that document while the dialog is still open. But this fixes the other cases.

**Comment by elextr** [comment]
Well, in that unlikely situation all that is lost is a blank file so its ok, just confusing if the newly opened file is saved as/renamed.

**Comment by ntrel** [comment]
This fix is superceded by #3395, but it's probably worth merging this also for resilience.

**Comment by eht16** [comment]
Tested and works great. I agree that even with #3395, this cannot hurt. There might be more cases where the current doc differs from the doc the Save As dialog were open.

**Pull request merged**
