### PR TITLE
Add some extra Markdown extensions

### PR DESCRIPTION
**Pull request by 12345ieee**
Add two extra markdown extensions to the default.

### CODE REVIEW

**Comment by codebrainz** [comment]
[Some related info](http://superuser.com/a/285878)

Seems logical to add them if people are using these (I always use `.md` myself, out of habit), and I don't think they clash with other common file extensions.

**Comment by 12345ieee** [comment]
Well, maybe not `.text`, the rest can be easily added.

**Comment by 12345ieee** [comment]
@codebrainz Done

**Comment by elextr** [comment]
Agree it shouldn't include `.text`, we at Asciidoc own that :wink: and `.txt`.

Otherwise looks ok.

**Comment by b4n** [comment]
okay, current state LGTM

**Pull request merged**
