### PR TITLE
editor: Add auto-indent in mult-iline comments

### LINKED ISSUE #2080: Auto-indent doesn't work within multi-line C-style comments
The auto-indent doesn't work within C-style multi-line comments: it ignores the indentation of the previous line. For example (`|` is caret):
```
/**
 * Multi line comment.
 *     Indented line|
 */
```
The current indentation after pressing Enter:
```
/**
 * Multi line comment.
 *     Indented line
 * |
 */
```
The expected indentation:
```
/**
 * Multi line comment.
 *     Indented line
 *     |
 */
```

### PR DESCRIPTION
**Pull request by danpla**
Fixes #2080

### CODE REVIEW

**Comment by elextr** [comment]
You have assumed that everyone wants this feature, but, given that you are the first to raise it AFAICT, and the first to contribute a patch (thanks) its likely that its not universally wanted.  Therefore it should be protected by a setting.

Also it needs to be documented in the manual.

**Comment by danpla** [comment]
> Therefore it should be protected by a setting.

I wonder how to add such a setting in the GUI without confusing the user. The problem is that this feature depends both on "Automatic continuation of multi-line comments" and "Auto-indent". I can think of two variants. The first one is a dependent checkbox in "Completions" tab. Something like:

2019-02-07-114213_1600x900_scrot


The second is an option in "Various settings", but that still needs a meaningful variable name.

**Comment by elextr** [comment]
The dependent checkbox method is used in other places in the Geany preferences and seems to me the best solution.

We don't want to add things to various unless they are really really rarely needed, since as you noted, the only information on them is the variable name.

**Comment by codebrainz** [comment]
I'm not sure it makes sense to add a general GUI setting for something so entirely language dependent. Ideally Geany itself wouldn't be doing anything language specific and it would be left to a plugin that provides language-specific features, like one of the formatting or addon plugins.

**Comment by danpla** [comment]
I think my pull request is an enhancement of the existing feature rather than an addition of a new one.

Automatic continuation is already a language-dependent feature, because not all languages have continuation characters in block comments (for example, Lua and `{}` comments in Pascal). I don't mind if it's moved it to a plugin, but that's out of the scope of this pull request.

**Comment by elextr** [comment]
@danpla @codebrainz totally agree with both of you, special comment handling is language specific and shouldn't be in Geany core, but it is, and has been for ages, so unless "somebody"[1] wants to make a pull request removing it to a plugin[2] then this is just a change to existing functionality.

And since its a change to existing functionality, which already has a setting in prefs, @danpla has just suggested adding a sub-setting to that existing setting.  Although that prefs page is busy, there is space for another line (at least on my font size).  So it seems a reasonable solution.

@danpla havn't actually looked at your code

[1] "somebody" in quotes is an olde time convention in Geany meaning "somebody, not necessarily you, but definitely won't be me", blame @eht16 :grin:

[2] an alternative would of course be to make the in-core functionality language agnostic by using the existing and perhaps additional comment settings in filetype files, but "somebody" has to do it

**Comment by danpla** [comment]
I added checkboxes both in global and project settings. Please test.

**Pull request closed without merging**
