### PR TITLE
Add preliminary support for Dartlang syntax highlighting

### PR DESCRIPTION
**Pull request by ghost**
Preliminary support for <a href="https://dartlang.org">Dart</a> has been added to address Issue #371. Following the suggestions recieved in the issue I used Java as a base and added keywords from Javascript.

Upon comparing to Dart Editor and Chrome Dev Editor with the examples from the official site as well as those mentioned in the current <a href="http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf">ECMA spec for dart</a> it appears to follow the conventions properly. I'll be reading over the ECMA specification more throughout this week to ensure the correctness, but any assistance from experienced users would be appreciated.

This is my first merge to geany, so if I made any blunders please let me know and I will happily correct them.

### CODE REVIEW

**Comment by b4n** [comment]
@wzsk Do you still have things to review here?

The only remarks I have with the current state are:
* you might want to add a `[build-menu]` section with appropriate Dart commands;
* it would be great to squash a few commits together, at least b47e726 in 86cb751 -- but we can do that when merging that's no biggie.

**Comment by wzsk** [comment]
I'm sorry I've been neglecting to make my updates! I'll make some time this
week to clean up my mess and get it squared away, I've had a lot going on
but I didn't see anything else in the specification that I haven't added
already.

**Comment by jdw1996** [comment]
Has there been any more progress on Dart support in Geany, by any chance?

**Comment by ntrel** [comment]
I'd like to merge this work. The custom filetype file should be called filetypes.Dart.conf, otherwise it won't register AFAIK. Also the conflict needs fixing. Any volunteers?

**Comment by yangsfang** [comment]
Hey I have no experience with the Geany codebase but this looks simple enough I think I can handle [this](https://github.com/geany/geany/pull/379#issuecomment-500142931). You can close this request if you'd like and assign #371 to me.

**Comment by elextr** [comment]
@yangsfang nobody gets "assigned" things in Geany.  Since this PR has conflicts and appears to have been abandoned just make a new PR.

**Comment by elextr** [comment]
Closed since conflicting for many years

**Pull request closed without merging**
