### PR TITLE
Fix startup speed

### LINKED ISSUE #2649: Slow startup
Seems to not be an issue on Linux.

References:
https://github.com/geany/geany/issues/2639#issuecomment-723489800
https://github.com/geany/geany/issues/2639#issuecomment-723494612
https://github.com/geany/geany-osx/issues/20
https://www.mail-archive.com/users@lists.geany.org/msg02989.html

### PR DESCRIPTION
**Pull request by b4n**
Dynamic margin width computation introduced in 1.37 is "slow", and can lead to about 3× slowdowns, which is most noticeable when loading startup files.

Fixes #2649.  Probably fixes https://github.com/geany/geany-osx/issues/20 as well.

This PR is mostly FTR and to let @techee check on OSX, there has already been some review and testing (see commit comments and comments starting at https://github.com/geany/geany/issues/2649#issuecomment-774309595).  But more reviews & tests are welcome of course.

### CODE REVIEW

**Comment by b4n** [comment]
If this proves not to cause issues (it really shouldn't), it's possibly candidate for a 1.37.2.  Opinions?  @elextr @eht16 @codebrainz

**Comment by eht16** [comment]
I think releasing it is a good idea. Basically, I wouldn't mind whether we call it 1.37.2 or 1.38 except that just "ctags_sync" has landed. So yes, 1.37.2 seems sensible.
However, I personally won't be able to do the Windows builds until approx. mid of March.

**Comment by elextr** [comment]
Given the "only" other change is we have a new ctags and it sounds like mid march before release and we havn't broken GTK2 (yet) I'd say call it 1.37.2.

**Comment by b4n** [comment]
> Given the "only" other change is we have a new ctags

I don't think I'm gonna put the new ctags in a point release; although it's fairly minor from a user perspective, I'm not very comfortable pretending a +30k -7k change still is 1.37.

**Comment by elextr** [comment]
>  I'm not very comfortable pretending a +30k -7k change still is 1.37.

Well branch the 1.37.2 off the commit before ctags maybe.

**Pull request merged**
