### PR TITLE
keyfile: Output unescaped filename if session file cannot be opened

### LINKED ISSUE #779: URL encoded filename in debug messages
On Windows if a session file in the project doesn't exist when the project is opened, a message like this shows up in the debug messages:

> Could not find file 'C%3A%5CUsers%5Cme%5CProjects%5Cfoo%5Cbar.cpp'.

Maybe it needs to be [unescaped](https://developer.gnome.org/glib/stable/glib-URI-Functions.html#g-uri-unescape-string), I didn't look at the code yet.

### PR DESCRIPTION
**Pull request by LarsGit223**
Fixes #779.

### CODE REVIEW

**Comment by elextr** [comment]
LGBI

**Comment by codebrainz** [comment]
Closed in 7fd73a06a7aab8582af36891f7b2a19dbe08188b

**Comment by J-Dunn** [comment]
Does this address the secondary issue I raise here?
https://github.com/geany/geany/issues/779#issuecomment-161904655
 
to which elextra replied:

> "Technically all other filenames in config files probably should be encoded, but thats another issue."

**Comment by elextr** [comment]
Well, except that I actually meant to say "escaped" not "encoded"  on #779 no it only addresses the output to the screen/terminal, as I said, the stored filenames are __intended__ to be escaped so they do not contain characters that cause problems for keyfiles when they are part of a list of items.  In the [project] section paths are by themselves in an entry and so in practice they probably don't actually need escaping.  

Which is why I only said technically all filenames should be escaped, it allows them to contain any Unicode character without caring what the encoding is.  But since nobody seems to be doing that, its not broke, so don't fix it :)

**Comment by LarsGit223** [comment]
@J-Dunn: no, this PR only fixes the issue which #779 directly addresses. As @elextr wrote the path encoding in the config file is correct. It only would be a bug if you see such enocidng in an output.

@elextr: no, only purely changed what PR #779 addresses and won't do anything else in this PR.

**Pull request closed without merging**
