### PR TITLE
Use the short name for EOL mode in the statusbar

### PR DESCRIPTION
**Pull request by b4n**
See discussion in https://github.com/geany/geany/pull/418

---

Again I'm not sure it's worth it, but OTOH it's not very hard to implement.  So, feel free to merge if you like it :)

### CODE REVIEW

**Comment by frlan** [comment]
Looks fine to me ;)

**Comment by techee** [comment]
+1

**Comment by elextr** [comment]
LGTM

**Comment by kugel-** [comment]
Sorry I didn't realize it's already merged

**Pull request merged**
