### PR TITLE
Add the .cache directory to .gitignore

### PR DESCRIPTION
**Pull request by techee**
This is where clangd stores its precompiled files.

### CODE REVIEW

**Comment by techee** [comment]
I unintentionally pushed the same commit directly to geany-plugins without making a pull request, sorry for that. If it's a problem, it can be reverted.

**Comment by elextr** [comment]
LGBI but a question, if clangd needs a meson build to get the `compile_commands.json` why doesn't it use the `build/.cache/clangd` directory?

**Review by b4n — APPROVED** [review]
I don't see a problem with this, LGBI

**Comment by techee** [comment]
> LGBI but a question, if clangd needs a meson build to get the compile_commands.json why doesn't it use the build/.cache/clangd directory?

No idea but my guess is to preserve the cached files also when you wipe the build directory - e.g. you add a a new file to the build system. I would guess that unless you change the build options, the cached files will still be valid.

**Pull request merged**
