### PR TITLE
Add preference for backspace unindenting

### PR DESCRIPTION
**Pull request by coalsont**
Implements #3354

### CODE REVIEW

**Review by b4n — CHANGES_REQUESTED** [review]
Looks pretty great, good job! :+1: 
There's just the comment + squashing the commits and it'd look good to go from me.  Bonus points if you'd update the documentation though :wink:

**Comment by coalsont** [comment]
The doc images appear to be generated separately, with a theme I don't use, and would have to guess at.  Squash can be handled when telling github to merge, or did you want me to do it manually?

**Comment by elextr** [comment]
IIUC only @eht16 has that theme? So to avoid replacing all the images I guess should ping him ... oh I just did :smiling_imp:

**Comment by eht16** [comment]
Pong :).
Nice try, @elextr but the theme used in the current docs is some Gnome 
Ubuntu default theme or something, long time ago the screenshots were 
made with my personal theme but @b4n and me agreed to use something more 
common and unmodified.

@coalsont if you want to update the screenshots, use a common default 
theme and update all screenshots to have them in a consistent style.
But for me, it would be ok if you leave the screenshots unmodified and 
just update the text in the documentation.
We will update the screenshots then shortly before the release.

**Comment by coalsont** [comment]
I didn't notice the response from eht16, sorry.  I'd say the screenshots can wait, and I edited the text already where I thought it needed it.  Did I miss something?

Also, for the comment about needing to squash, is that referring to github's squash merge, or something I need to do manually first?

**Comment by elextr** [comment]
We have a bit if a disconnect in the project about what and when to squash and no clear policy.  

IM(NS)HO all commits should be squashed unless they make a working Geany, which means most merges can simply squash all commits with github and maybe clean up the message (remove the "fix up foo" type commit messages).

In others opinions commits should be merged to make a buildable Geany.

And others have the erroneous idea that they should be squashed to make logical change sets which may leave Geany broken, or even unbuildable.  Sadly there has been too much of this over the Geany history and now Git bisect is pretty much useless over much of the history, but that should not be an excuse to continue to break it by not squashing commits that do not at least make a valid build. [end rant]

In your case my quick glance says the four commits are a basic one and three fixups, IMO so the whole lot could be squashed and merged by github's big green button.  

But for people like @b4n who (IIUC) still insist on doing their Git from the command line, the squash and merge is of course more work, which is probably why he asked you to do it.  IMO old fashioned approaches like that just add extra barriers to contribution which we don't need.

**Pull request merged**
