### PR TITLE
Convert Nim to builtin filetype and use Scintilla Nim lexer for it

### PR DESCRIPTION
**Pull request by techee**
In addition to JSON, the other lexer we don't use yet is for the Nim language (these are the only ones I'm aware of). I'm not a Nim language user myself but I tried to modify the external filetype config file to the internal one so most of the stuff is preserved and should work correctly.

### CODE REVIEW

**Comment by techee** [comment]
In addition to https://github.com/geany/geany/pull/3171 I'd like to merge this PR too so there's a proper lexer for the Nim language. I just went through the PR and tested it a bit and all seems to work well.

Again, I'll wait for about a week for complaints and merge this afterwards.

(Misusing hot summer days where nobody pays attention to get some old patches of mine merged :-P.)

**Comment by elextr** [comment]
Conflicts need resolving.

Its meant to be long __lazy__ summer days :stuck_out_tongue:

**Comment by techee** [comment]
> Conflicts need resolving.

I'm aware of that. But because I'll introduce other conflicts by merging https://github.com/geany/geany/pull/3171, I'll wait until that one is merged.

> Its meant to be long lazy summer days 😛

Yeah, just merging stuff is lazy :-)

**Comment by elextr** [comment]
https://github.com/nim-lang/langserver

**Comment by techee** [comment]
> https://github.com/nim-lang/langserver

By the way I tried that one but it kept crashing for me and I didn't spend much time investigating what went wrong.

**Comment by elextr** [comment]
> but it kept crashing for me and I didn't spend much time investigating what went wrong.

Ok, was just a suggestion since there is no ctags parser.

**Pull request merged**
