### PR TITLE
README.rst:grammer fix (missing word)

### PR DESCRIPTION
**Pull request by andy5995**
I replaced a missing word and suggested a minor change

[skip ci]

### CODE REVIEW

**Comment by elextr** [comment]
@andy5995 but what word did you find missing?  Your committ only makes a change, did you miss something?

**Comment by b4n** [comment]
@elextr The sentence was *"There a few command line options."*.  I'd agree with @andy5995 that there's at least a missing *is*, and that the reformulation is better as well.

**Comment by elextr** [comment]
@b4n, ok, I missed the "are" that wasn't there (its "are a few" not "is a few" because the "are" refers to the multiple "few", not the singular "a", damn English) :grin:

I was checking if @andy5995 left something out because this doesn't sound right, "several" implies a low number.

Now that you made me count them, actually Geany has 21 options, in idiomatic English that is neither "a few" or "several".  In fact it is more like"quite a few" though of course it is indeed "only a few" compared to GCC (damn English) :grin:

@andy5995 maybe combine the sentences into "For the command line options see the ...." and avoid the numerative ambiguity altogether.

**Comment by elextr** [comment]
LGBI, sadly Travis doesn't build the manuals AFAICK.  I guess as soon as @b4n indicates he still approves  it can be merged and the nightly [manual build](https://www.geany.org/manual/dev/index.html) will check it.

**Comment by b4n** [comment]
@elextr I guess if Travis didn't run it's because of the `[skip ci]` annotations in the commit messages ;)

**Comment by elextr** [comment]
@b4n what I mean is that even if it did run we can't see the manual, I guess it does check rst2html doesn't object too much, but we have no way of checking it looks right from CI.

IIUC Travis artefact uploading isn't available on PR builds, so we have to wait until after merge when the nightly manual is built and uploaded to geany.org.

So here goes this one :)

**Pull request merged**
