### PR TITLE
Improve some comments in filetype conf files

### PR DESCRIPTION
**Pull request by techee**
These are two improvements of the comments discussed in #3413:

1. The indented `#command_example();` in
```ini
# set to false if a comment character/string should start at column 0 of a line, true uses any
# indentation of the line, e.g. setting to true causes the following on pressing CTRL+d
	#command_example();
# setting to false would generate this
#	command_example();
# This setting works only for single line comments
comment_use_indent=true
```
isn't a valid conf file line as `#` should be placed at the beginning of the line. This makes Scintilla to render `#command_example();` as if it weren't a comment. This  patch changes this to
```ini
# set to false if a comment character/string should start at column 0 of a line, true uses any
# indentation of the line, e.g. setting to true causes the following on pressing CTRL+d
# 		#command_example();
# setting to false would generate this
# #		command_example();
# This setting works only for single line comments
```

2. The patch replaces the not-very-English-sounding
```ini
# the following characters are these which a "word" can contains, see documentation
#wordchars=_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
```
with the following description from the documentation:
```ini
# these characters define word boundaries when making selections and searching
# using word matching options
#wordchars=_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
```

### CODE REVIEW

**Comment by b4n** [comment]
> 1. The indented `#command_example();` in
> 
> […]
> 
> isn't a valid conf file line as `#` should be placed at the beginning of the line. This makes Scintilla to render `#command_example();` as if it weren't a comment. This patch changes this to

Actually it [is valid for our purpose at least](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gkeyfile.c#L1277).

> This makes Scintilla to render `#command_example();` as if it weren't a comment. 

Yeah that's not very nice indeed, so it'd be indeed good to stick to what that lexers accepts as a comment.  However, we explicitly set `lexer.props.allow.initial.spaces=0` in *filetypes.conf*, which we probably shouldn't… setting it to `1` also fixes the highlighting in this file.

For history, the property originates from 00bc23cec4d86d5e18752dc38034978ac18f9645, which commit message confuses me, as I understand it as meaning the exact contrary to what it actually does…

It's however worth noting that the [tag parser ignores lines starting with a space regardless of what comes after](https://github.com/geany/geany/blob/master/ctags/parsers/iniconf.c#L127), e.g. `    key=value` isn't parsed as a key-value pair.

---

I'm not saying we shouldn't apply your changes here, they *do* look better to me.  I'm just trying to be (too) thorough.

**Comment by elextr** [comment]
@b4n

> Actually it [is valid for our purpose at least](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gkeyfile.c#L1277).

I already pointed that out [here](https://github.com/geany/geany/pull/3413#issuecomment-1445242422) but as I noted its _not_ documented.  Relying on undocumented features seems risky.  @techees changes remove that reliance.

> set lexer.props.allow.initial.spaces=0 in filetypes.conf, which we probably shouldn't…

Yes we should, to match the parser behaviour you note further on.

> For history, the property originates from https://github.com/geany/geany/commit/00bc23cec4d86d5e18752dc38034978ac18f9645, which commit message confuses me, as I understand it as meaning the exact contrary to what it actually does…

Well the default value in Scintilla is 1 which matches the comment, but then Geany sets it 0 which is correct (IMNAAHO).

> I'm not saying we shouldn't apply your changes here, they do look better to me. I'm just trying to be (too) thorough.

So this is ok and arguing about the lexer prop can occur on another issue/PR, then I agree and LGBI.

@techee thank you for doing a boring repetitive job

**Comment by b4n** [comment]
> Yes we should, to match the parser behaviour you note further on.

One thing I forgot to mention is that it's the same commit mentioned above that also modified the parser not to allow leading whitespaces…

> Well the default value in Scintilla is 1 which matches the comment, but then Geany sets it 0 which is correct (IMNAAHO).

You seem to have a lot against leading whitespaces here, far beyond whether we should or shouldn't use them in these specific files, why is that?
My personal *feeling* is that we shouldn't *use* them in our conffiles, but that we should support them in the file type; I don't see any reason why to limit this, is there really valid cases where it causes problem to support it?
@eht16 as the author of the mentioned commit, can you remember the reason ages later?

**Comment by elextr** [comment]
> You seem to have a lot against leading whitespaces here, far beyond whether we should or shouldn't use them in these specific files, why is that?

Not a _lot_, but you are right, the point is beyond just Geany conf files.

There were, and possibly still are, a lot of things that used ini like conf files (or has everyone gone JSON/TOML?) and a lot of different parsers, not just Glib, so who knows if they accept leading spaces.  Given that Geany does not know what parser is going to be used my feeling is that Geany should not _by default_ encourage something that might not be legal.  So 0 is the right default for Scintilla, isn't the property settable in the filetype file if the user really wants to use indents?  

Maybe the property should be in the filetype file set to 0 so users can find it to modify it (cycling neatly back to the original point ;-)

And of course 0 matches the parser (upstream is the same, having come from this one I guess).

**Comment by elextr** [comment]
> for example the parser accepts ; comments, and I didn't look again but I guess the lexer has similar extension that breaks your expectations of the highlighting being a validator or similar.

Scintilla accepts `;` as well, after all its the original comment in MS `.ini` files, not `#` these Unix come lately guys use ;-P

But leading spaces are orthogonal to `;` / `#`, IIRC there are parsers that do what the parser here does, look at the first character of the line only, be it `#` or `;` (or `[`).

As I said I don't care a _lot_ so if an import of the parser from ctags changed its behaviour and the default Scintilla was made the same thats fine.

Anyway lets stop sidetracking @techee's excellent PR.

**Review by b4n — APPROVED** [review]
Looks good, as usual

**Comment by techee** [comment]
> My personal feeling is that we shouldn't use them in our conffiles,

Agree. I think that apart from the reasons mentioned above, it just looks nicer in the conf file when all commented-out lines start with `#`.
 
> but that we should support them in the file type; I don't see any reason why to limit this, is there really valid cases where it causes problem to support it?

I don't have a strong opinion on this. There are two possible views:

1. Display all possible conf files nicely syntax-highlighted.
2. Encourage users to use the safest conf file format possible by not highlighting a possibly invalid format (the specification here https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s03.html doesn't say anything about leading or trailing spaces so it may be implementation specific).

**Pull request merged**
