### PR TITLE
plugin api: export editor_set_indent_width()

### PR DESCRIPTION
**Pull request by kugel-**
Plugins can now change the indentation width of an editor.

### CODE REVIEW

**Comment by kugel-** [comment]
@b4n @elextr @codebrainz can this be merged?

**Comment by elextr** [comment]
LGTM by inspection.

**Comment by b4n** [comment]
Declaration in the header file needs to be moved out of the `GEANY_PRIVATE` section.

Feature itself looks fine.

**Comment by kugel-** [comment]
Done

**Comment by b4n** [comment]
LGTM

**Pull request closed without merging**
