### PR TITLE
Prefix the WIF* macros with SPAWN_ and add short doc comments to them

### PR DESCRIPTION
**Pull request by zhekov**
Given the lack of time, the comments are very terse. I'm not sure how they will show up...

### CODE REVIEW

**Comment by b4n** [comment]
LGTM, now testing

**Comment by b4n** [comment]
Hum, used to be zhekov/master, but it's unknown now?  Can't find the sources :/

**Comment by b4n** [comment]
never mind I picked up the patch itself and am'd it

**Comment by zhekov** [comment]
On 12.7.2015 г. 17:20, Colomban Wendling wrote:
> never mind I picked up the patch itself and am'd it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geany/geany/pull/567#issuecomment-120724517>.
>

The proper patches are in zhekov/spawn, PR #568.

--

The current Geany does not build for me under Win~1, but that's not 
because of spawn. The latest "win32defines.h" defines WINVER 0x0501, but 
it should define _WIN32_WINNT 0x0501 (recommended) and do that before 
any other windows includes (required). Currently, win32.c includes 
win32.h -> ... -> _mingw.h, which defines WINVER to something else, and 
as a result, Geany does not link:

.../_build_/../src/win32.c:1020: undefined reference to 
`SHGetFolderPathAndSubDirW'

The simplest fix is to move #include "win32defines.h" before #include 
"win32.h" (tested it on my system).

--
E-gards: Jimmy

**Comment by b4n** [comment]
> The current Geany does not build for me under Win~1, but that's not
> because of spawn. The latest "win32defines.h" defines WINVER 0x0501, but
> it should define _WIN32_WINNT 0x0501 (recommended) and do that before
> any other windows includes (required). Currently, win32.c includes
> win32.h -> ... -> _mingw.h, which defines WINVER to something else, and
> as a result, Geany does not link:
> 
> .../_build_/../src/win32.c:1020: undefined reference to
> `SHGetFolderPathAndSubDirW'
> 
> The simplest fix is to move #include "win32defines.h" before #include
> "win32.h" (tested it on my system).

Argh.  So that means we really need to include `win32defines.h` first
thing, not only before `<windows.h>` and the like?  So maybe redundancy
in the build systems wasn't so bad after all…

Anyway, thanks for the catch, and @eht16 is on it.

**Pull request closed without merging**
