### PR TITLE
Increase the default width for the sidebar

### LINKED ISSUE #3630: Maybe the default sidebar width is too narrow
There is enough room to show everything in the picture but some of it is clipped of to the left.

billede

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.39 og GLib v2.78.0

### PR DESCRIPTION
**Pull request by eht16**
This should prevent the sidebar from being cutoff or clipped of the window. The new value is about 25% of the default window width.

Closes #3630.

### CODE REVIEW

**Comment by elextr** [comment]
Maybe a smidgen more?  I tried with the desktop set to 12 point and it needed the sidebar set to 208 pixels to avoid Document being hidden and the scroll arrows appearing.  But this system (Mint Cinnamon) doesn't have the big padding to the right of "Documents" that shows in the Adwaita example you posted to #3630 (and is in the image the OP posted).  So maybe 230 pixels to allow for it?

And when it doesn't fit why doesn't it do as I said, hide Documents and show the scroll arrows?  Is that controlled by Adwaita too?

**Comment by eht16** [comment]
> Maybe a smidgen more? I tried with the desktop font set to 12 point and it needed the sidebar set to 208 pixels to avoid Document being hidden and the scroll arrows appearing. But this system (Mint Cinnamon) doesn't have the big padding to the right of "Documents" that shows in the Adwaita example you posted to #3630 (and is in the image the OP posted). So maybe 230 pixels to allow for it?

Ok, I pushed 230.

> And when it doesn't fit why doesn't it do as I said, hide Documents and show the scroll arrows? Is that controlled by Adwaita too?

I don't know. I had guessed it's rather GTK than the theme but I really don't know.

**Comment by cwendling** [comment]
> > And when it doesn't fit why doesn't it do as I said, hide Documents and show the scroll arrows? Is that controlled by Adwaita too?
> 
> I don't know. I had guessed it's rather GTK than the theme but I really don't know.

My guess would land on the search entry that has a minimum with wider than out default value.

**Comment by b4n** [comment]
BTW, if setting this to `-1`, it'll use the minimum size so things fit, which is a bit wider than current master with the entry (I think I was right earlier).  It'll however happily hide tabs as we allow this.

Anyway, 220 or 230 look indeed better to me, and work as well if I use Adwaita on my system.

So LGTM :+1:

**Review by b4n — APPROVED** [review]
Just squash when ready

**Comment by elextr** [comment]
Perhaps the search entry minimum size @b4n identified should be shrunk too, I presume it is the cause of one of my systems no longer hideing the Document tab and shows scroll arrows as the sidebar size is shrunk.  1.38 on the same system does.

**Comment by eht16** [comment]
I merged it because this PR was only about to increase the default sidebar width for only the default window size.
As most users probably will resize and use a bigger window size after all, I'm not sure if the efforts are worth to also modify the entry's minimal size.

**Pull request merged**
