### PR TITLE
COBOL: Import new upstream candidate parser

### PR DESCRIPTION
**Pull request by b4n**
This fixes support for COBOL symbols after the recent breakage of regex
parsers, as well as introducing additional features and bug fixes.

Also import some of the tests.

https://github.com/universal-ctags/ctags/pull/2076

Part of #2119.

### CODE REVIEW

**Comment by b4n** [comment]
@DansLeRuSH (and @swconnolly if still have interest in Geany COBOL support), could you give this a test?  It should bring back COBOL symbols, and improve it a bit.

Note that if you'd like to help to get it even further with actual COBOL insight, please comment on https://github.com/universal-ctags/ctags/pull/2076.

**Comment by elextr** [comment]
WFM, compiles, runs, `make check`s, shows symbols for bits of cobol found in wikipedia.

**Comment by b4n** [comment]
> didn't review the parser itself as the only Cobol I ever did was one assignment in Uni [mumble] years ago.

Still better than me who wrote the parser, with zero COBOL experience :)

**Comment by elextr** [comment]
> Still better than me who wrote the parser, with zero COBOL experience :)

Yesterday @b4n couldn't spell COBALL, now he am an expert :)

**Comment by elextr** [comment]
> > Still better than me who wrote the parser, with zero COBOL experience :)

> Yesterday @b4n couldn't spell COBALL, now he am an expert :)

In fact probably _the_ expert in the Geany team I suspect.

**Comment by codebrainz** [comment]
Nice work @b4n.

**Comment by b4n** [comment]
> @b4n See? This is how you do commit reviews. You should learn from me, it's trivial :-)

Wow, why did I use to put so much effort and time if it's so easy!  thanks :smile:

**Comment by DansLeRuSH** [comment]
Truly I work with this (and no, I do not only code in COBOL) and adjust it every time I could. @b4n told me interesting suggestions and I'll do upgrades later

**Comment by b4n** [comment]
@DansLeRuSH don't hesitate to mention any issue you find, I'm happy to try and fix them or review a patch.  If you can, ideally you'd report it what can be against universal-ctags, but don't worry if it's against Geany I can forward what need be just fine as well.

**Comment by swconnolly** [comment]
Hello all. Sorry for arriving late, I was on vacation. Parsing sure looks different from previously. The new parser looks good, especially multi-level data items. Attached is a patch with a few tweaks . They deal with binary data items that do not have either a PIC or VALUE clause and special keywords showing up as procedures. 
At we work mostly with free format files. Is there a way to switch from FIXED to FREE? Otherwise I will code the change and recompile.
[geany_cobol.patch.txt](https://github.com/geany/geany/files/3132890/geany_cobol.patch.txt)

**Pull request merged**
