### PR TITLE
Splitwindow2

### PR DESCRIPTION
**Pull request by kugel-**
Initial PR for multiple document notebooks. Seems to work pretty stably now.

Please ignore c73a066 (Fix geany crash on start.) for review, it's needed to fix a crash on my machine with gtk 3.10.2.

### CODE REVIEW

**Comment by b4n** [comment]
BTW, I see some of the discussions we had a long time ago isn't here --and may have only be on IRC.

From the top of my head, one practical issue I had with this was that when not enabled the slit window still wasted screen space for the DnD target area.  And disrupting the UI when the feature is not used is unacceptable IMO.
Apart that I guess I can get over the "not the best implementation I'd wish for" problem (as I can easily admit that a perfect impl would be a *lot* of work rewriting many many things).

**Comment by kugel-** [comment]
I'll open or re-open when I think it's ready again

**Comment by kugel-** [comment]
FWIW, I did *not* stop working on it, quite the contrary. The code is still open in my frok (https://github.com/kugel-/geany/tree/splitwindow2)

**Comment by buserror** [comment]
I use geany all day long, and that's really a must have BTW. I tried for a while using two windows, but it's nowhere near as useful..

**Comment by kugel-** [comment]
You can use the branch I linked above, I update it more or less regularly. But I may force push.

I just closed this PR because the current implementation is not ready for geany core so I don't want to waste the reviewers precious time.

**Pull request closed without merging**
