### PR TITLE
updated lithuanian trasnlation

### PR DESCRIPTION
**Pull request by gymka**

### CODE REVIEW

**Comment by frlan** [comment]
Would you mind to rebase the branch on current master? Would be awesome ;)

**Comment by gymka** [comment]
it's based on current master... first pull request was bad, so i closed it, updated my local copy, updated translation, created new pull request but now it shows my first request too

**Comment by gymka** [comment]
i can't delete pull request, only close it. then i open new it updates this one, but not creates new

**Comment by frlan** [comment]
Well.. Actually I was thinking about running a git rebase against upstream branch to get rid of e.g. the merge commit. Anyway, going to merge it like this. Won't hurt anybody beside the little noise causing it. And I'm happy for the translation update so users can use geany in their mother language maybe.

**Pull request merged**
