### PR TITLE
#2459: Add Geany to Category TextEditor

### PR DESCRIPTION
**Pull request by dmaphy**

### CODE REVIEW

**Comment by frlan** [comment]
LGTM

**Comment by codebrainz** [comment]
Weird, I thought this was already merged so didn't comment, since I got a commit mail about it. I guess it's because the branch was made on the main repo instead of a fork?

Anyway, if we do this, committer or merger should delete the branch after so we don't have too many useless branches clogging up the Githubs.

**Comment by eht16** [comment]
> Weird, I thought this was already merged so didn't comment, since I got a commit mail about it. I guess it's because the branch was made on the main repo instead of a fork?

Yes. You can see the branch in the top of the body of the mail.
Usually this is master but when the branch is in the main repo instead of a fork, commit mails are sent as well.

> Anyway, if we do this, committer or merger should delete the branch after so we don't have too many useless branches clogging up the Githubs.

Agreed.

**Comment by elextr** [comment]
I left the branch on merge since it was someone elses branch, it would be rude to delete it.

It would be nice if github didn't make these in the main repo just because the user has commit rights, but anyway thats the way it is.

PS Did remind me to delete a couple of my olde branches :grin:

**Comment by codebrainz** [comment]
> It would be nice if github didn't make these in the main repo just because the user has commit rights, but anyway thats the way it is.

It only does that when you edit files on the main repo instead of your own fork.

**Pull request merged**
