### PR TITLE
Add basic Dockerfile syntax highlighting

### PR DESCRIPTION
**Pull request by pestadieu**
Add basic Dockerfile syntax highlighting using C lexer.

### CODE REVIEW

**Comment by eht16** [comment]
Cool.
Though we cannot add all arbitary file type variants to Geany itself, at some point it gets pretty crowded.
Would mind adding a page on https://wiki.geany.org/config/start in the "Custom Filetypes" section?
That way, interested people will still find it and we don't need to integrate it hard in Geany.

**Comment by pestadieu** [comment]
Thanks for your answer.

How can I edit the wiki ?

Le dim. 25 nov. 2018 à 14:56, Enrico Tröger <notifications@github.com> a
écrit :

**Comment by LarsGit223** [comment]
You need to click on "Log In" and then on "Register". Create an account and login with it. Then you get the option to edit a page.

**Comment by pestadieu** [comment]
The Dockerfile wiki entry has been created [here](https://wiki.geany.org/config/dockerfile).

I am closing this now.

**Pull request closed without merging**
