### PR TITLE
Fix geany icon handle

### PR DESCRIPTION
**Pull request by techee**
The handle of the lamp icon looks strange. While
the image of the lamp itself is taken from top,
the handle looks it's taken from bottom.

Fix this by moving the wide part of the handle
down and moving the "shine" line to copy the
outer edge.

### CODE REVIEW

**Comment by techee** [comment]
Old:

old

New:

new

If this change is OK, I'll regenerate the png icons and add them to the patch.

**Comment by codebrainz** [comment]
OT: @eht16 do you where this icon came from? did you make it? I always wondered

As for the change, I have no comment, the size I ever see it, it's indistinguishable :)

**Comment by elextr** [comment]
TBH I like the tapering handle better, thats how many "real" magic lamps look, but like @codebrainz I will only ever see it at a resolution where it doesn't matter :)

**Comment by eht16** [comment]
OT: @codebrainz : http://lists.geany.org/pipermail/users/2007-June/001198.html

On topic: I'd prefer Jiří's version but would agree that probably the change is not visible in most cases because of much smaller sizes of the icon.

**Comment by techee** [comment]
@elextr I could probably adjust the icon with the existing shape too, will try how it looks. 

My main problem is the perspective thing - the lamp image is taken from the top but with the "shine" line copying the outer edge of the handle the back part of the widened handle must be its bottom part -something you could never see if the camera is above the lamp. So now it looks the handle is somehow strangely curved backwards.

**Comment by techee** [comment]
About visibility at small sizes: one doesn't see all the lines at small icon sizes but already at 32x32px I see the bottom part of the widened handle as being in the shadow which shouldn't be physically possible (unless the genie inside the lamp uses some really powerful magic :-)

**Comment by techee** [comment]
@elextr How about this (very quickly made, I can probably make it a bit nicer for the merge):

top-wide

The handle proportions should be about the same but this time you see the top part of the handle, not its bottom.

**Comment by elextr** [comment]
LGTM :)

**Comment by techee** [comment]
I have just uploaded a new version of the icon. I've tuned the handle a bit and also fixed the weirdness around the bottle neck (compare the part in the red circle with the previous versions to see what has changed). For this I needed to be able to show/hide some objects while editing so I created some layers and moved different bits of the lamp to different layers.

Finally I regenerated the png icons and added the 32x32px png size (see the commits for more info).

geany

**Comment by b4n** [comment]
Handle LGTM (as @elextr I prefer to keep the wide part on top, so I prefer this version)

Indeed the bottleneck was weird.  I just wonder whether it wasn't better to see some of the non-highlighted parts in it though?  But that's nitpicking.

**Comment by techee** [comment]
Good point, how about this (had to make the bottleneck a bit wider):

geany

If it's OK this way, I'll repush the svg and png's.

**Comment by b4n** [comment]
LGTM :)

**Comment by techee** [comment]
Here are the latest changes. 

I've noticed that previously I forgot to update the windows ico file - I did it now. The 16 color palette icon from the ico file looks suspiciously good compared to the previous image, I hope I did everything correctly (I used the icotool commandline tool to generate the ico file and "icotool -l geany.ico" lists the same icon sizes and color depths as before so hopefully everything is correct).

**Comment by b4n** [comment]
About the .ico file: I didn't check on Windows or anything, but when I open it with Gimp, I see there are 8 versions:

* 3 are 16×16 (1 with alpha, 2 different ones without)
* 3 are 32×32 (1 with alpha, 2 different ones without)
* 2 are 48×48 (1 with alpha, 1 without)

Having the alpha/non-alpha might make sense (and of course the ones with alpha are better), but I'm not quite sire why the 16×16 and 32×32 have another additional (uglier) version?  Are those the previous icons and you would only have added new ones?

**Comment by techee** [comment]
I kept the same icon sizes / color depth which were present in the original icon. When listing the icons inside the original geany.ico, I get:

```
$ icotool -l geany.ico 
--icon --index=1 --width=32 --height=32 --bit-depth=4 --palette-size=16
--icon --index=2 --width=16 --height=16 --bit-depth=4 --palette-size=16
geany.ico: clr_important field in bitmap should be zero
--icon --index=3 --width=48 --height=48 --bit-depth=8 --palette-size=256
geany.ico: clr_important field in bitmap should be zero
--icon --index=4 --width=32 --height=32 --bit-depth=8 --palette-size=256
geany.ico: clr_important field in bitmap should be zero
--icon --index=5 --width=16 --height=16 --bit-depth=8 --palette-size=256
--icon --index=6 --width=48 --height=48 --bit-depth=32 --palette-size=0
--icon --index=7 --width=32 --height=32 --bit-depth=32 --palette-size=0
--icon --index=8 --width=16 --height=16 --bit-depth=32 --palette-size=0
```

I get the same output with the new icon version as well (without the warnings). I replaced all the icons (the original low-color-depth ones were much uglier than now, there were black dots inside them).

I just tried to replicate the previous icon types without thinking why the various types are present inside the ico file - I assumed the palette ones are used when 16/256 bit colors are used by the system (on the other hand, who uses such a setting these days).

**Comment by b4n** [comment]
@techee Oh, they are 4bpp.  OK, sorry for not having checked the current version -- indeed if we have it like this let's keep it, there probably was a reason it was like that.

**Comment by b4n** [comment]
@techee LGTM, but maybe you want to remove the `inkscape:export-filename` property?

**Comment by techee** [comment]
> @techee LGTM, but maybe you want to remove the inkscape:export-filename property?

Done (I've just removed the diff so the original path is there).

**Comment by b4n** [comment]
Perfect, thanks!

**Pull request merged**
