### PR TITLE
Add file-extensions for Clojure

### PR DESCRIPTION
**Pull request by trizen**
The extensions are from Wikipedia: https://en.wikipedia.org/wiki/Clojure

### CODE REVIEW

**Comment by elextr** [comment]
Are you sure .edn is a source file? I couldn't find it in the clojure docs (at least not quickly :)

Otherwise its a good idea since we already distribute a Clojure filetype.

**Comment by trizen** [comment]
I'm not sure if it's standard in Clojure, but this is what I've found: https://github.com/edn-format/edn

**Comment by codebrainz** [comment]
IMO it's a bug that we have a Clojure filetype but have not associated any extensions with it (judging by the changes in this PR).

**Comment by elextr** [comment]
@trizen so .edn is not Clojure, its another filetype that just ahppens to be used by Clojure (and others) so it should not invoke the Clojure filetype.

But the other 3 are fine, and as @codebrainz says, not having them looks like an oversight :)

**Comment by b4n** [comment]
Two commits should be squashed together, but LGTM otherwise

**Comment by b4n** [comment]
Squashed the commits together and committed as f3a5dd609a51cbb0921d020b32a3778e24bf52e4, thanks.

**Pull request closed without merging**
