### PR TITLE
Update HTML keywords

### PR DESCRIPTION
**Pull request by vfaronov**
To enable highlighting them as keywords in HTML documents, add the following elements [defined in W3C HTML 5.1](https://www.w3.org/TR/html51/fullindex.html#index-elements):

- `menuitem`
- `picture`
- `rb`
- `rtc`
- `template`

as well as the following elements [defined in WHATWG HTML Living Standard](https://html.spec.whatwg.org/multipage/indices.html#elements-3):

- `math`
- `slot`
- `svg`

### CODE REVIEW

**Comment by elextr** [comment]
@vfaronov looks ok by inspection, though whatwg looks [like](https://xkcd.com/927/).

Could I ask you to clean the list up while you are making changes, there seems to be repeated stuff (which is bad) and its out of alphabetical order (which is possibly why stuff got repeated).

**Comment by vfaronov** [comment]
Sure, see updated PR. I also realized this list contains attributes as well, so added those too.

As for WHATWG, as far as I understand, the major browser vendors follow that standard, so we shouldn’t ignore it.

**Comment by elextr** [comment]
Thanks, as I am not a HMTList (I am widely acknowledged as allergic to `<>`s) will wait for a bit to see if anybody objects before commit.

**Comment by eht16** [comment]
I had a look and think this is OK even though I'm no HTML expert either.
But it probably won't hurt.

Fine to merge for me.

**Comment by elextr** [comment]
Merged, since its a data file if its badly wrong users can edit it if needed.

**Pull request merged**
