### PR TITLE
Linkage cleanup

### PR DESCRIPTION
**Pull request by kugel-**
Superseeds #358

To summarize again: This implements geany as libgeany.so, so that only select symbols are exported to plugins. Symbols now have to be marked explicitely with GEANY_API_SYMBOL

### CODE REVIEW

**Comment by b4n** [comment]
Hum, it's a bit complex to check because you added changes to some existing commits, so they don't stand out…  for example 3df5b2b now changes the way it links to *libuuid*, while original fdf957a6b54668b23e4f9ca59e0a084eb3a52d39 did not (I did it in a followup branch, 8193031a3bd5a533397b6e27c7baf5010c05d09d).  The change is good, but it's harder to check the differences.

I get that you rebased the changes above a more recent master so that some changes soem from there.  On that matter, apparently the changes to Scintilla's makefile.win32 from f8c6adc9d1593cbdf69650534193c0cf2900d43e (d331936fbf382cbd8d640c8bd95ec82884e651f1 now) seem to have been lost.

I checked the diff from `codebrainz/wip/linkage-cleanup` (on branch `kugel-/linkage-cleanup`) and it seem to be all that changed.

**Comment by b4n** [comment]
This script:
```shell
#!/bin/sh

set -e
#~ set -x

OLD=$(tempfile)
NEW=$(tempfile)

trap 'rm -f "$OLD" "$NEW"' EXIT QUIT TERM INT

# get the old list of plugin functions
git grep -h -P '^ *# *define [a-zA-Z0-9_]+' master -- plugins/geanyfunctions.h | \
sed 's/^ *# *define \([a-zA-Z0-9_]\+\).*$/\1/' | \
grep -v GEANY_FUNCTIONS_H |
sort \
> "$OLD"

# get the new list of plugin functions
git grep -h -A2 '^ *GEANY_API_SYMBOL' | \
sed -n '/^ *GEANY_API_SYMBOL/{
  :next
  n
  /^--$/{b break}
  s/^\(.*[^a-zA-Z0-9_]\|\) *\([a-zA-Z0-9_]\+\) *(.*$/\2/p
  # we try next line in case of no match, e.g. if the type is split on its own line
  T next
  :break
}' | \
sort \
> "$NEW"

diff -u0 "$OLD" "$NEW" | tail -n+3 | grep ^[+-]
# just to output with error code on differences
diff -q "$OLD" "$NEW" >/dev/null
```
shows that the function `project_write_config()` misses it export flag.

**Comment by b4n** [comment]
Apart that, diff looks good I guess.

Needs testing, and the merge conflicts will have to be fixed at some point (possibly when merging if they are reasonable -- though if it's already rebased, it can be again)

**Comment by b4n** [comment]
@techee could you try on OSX and see if there are further issues?  (before or after the merge conflicts are fixed)

**Comment by techee** [comment]
I get this when compiling:

```
Making all in src
( \
		echo '/* This file is auto-generated, do not edit. */' && \
		/usr/bin/sed -n '/@callback_map@/q;p' "./signalconn.c.in" && \
		/usr/bin/sed -n 's/^.*handler="\([^"]\+\)".*$/\tg_hash_table_insert(hash, (gpointer) "\1", G_CALLBACK(\1));/p' "../data/geany.glade" \
			| /usr/bin/sort | /usr/bin/uniq && \
		/usr/bin/sed -n '/@callback_map@/{:l;n;p;b l}' "./signalconn.c.in" \
	) > signalconn.c || { rm -f signalconn.c && exit 1; }
sed: 1: "/@callback_map@/{:l;n;p ...": unexpected EOF (pending }'s)
```

It looks the ;'s don't quite work

http://stackoverflow.com/questions/15467616/sed-gives-me-unexpected-eof-pending-s-error-and-i-have-no-idea-why

But when I replace them with newlines I get

```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

Yeah and waf seems not to generate signalconn.c at all.

```
../src/callbacks.c:1912:10: fatal error: 'signalconn.c' file not found
#include "signalconn.c"
         ^
1 error generated.
Waf: Leaving directory `/Users/jhbuild/geany/_build_'
```

**Comment by b4n** [comment]
@techee gosh, OSX's sed (yeah, I already fought it relatively recently -- and when you don't have it to test, it's even funnier).  OK, I'll try and see.

**Comment by b4n** [comment]
@techee what if you simply add a `;` before the `}`? (`'/@callback_map@/{:l;n;p;b l;}'`)
The problem is that it's quite hard to write literal newlines in a make rule…

**Comment by techee** [comment]
@b4n The same error I'm afraid.

**Comment by techee** [comment]
Maybe it would be worth putting all these sed commands to a separate script so it can also be used by waf without duplicating the code in wscript.

**Comment by b4n** [comment]
@techee what about `sed -n -e '/@callback_map@/{:l' -e ';n;p;b l' -e '}'`?  works with the sed from FreeBSD which seem to have the same behavior.

**Comment by kugel-** [comment]
I have another solution, replace the whole signalconn stuff in Makefile.am with this


signalhashes: $(top_srcdir)/data/geany.glade
	$(AM_V_GEN)$(SED) -n 's/^.*handler="\([^"]\+\)".*$$/\tg_hash_table_insert(hash, (gpointer) "\1", G_CALLBACK(\1));/p' \
		$< | $(SORT) | $(UNIQ) > $@

signalconn.c: signalhashes

CLEANFILES += signalhashes

Also need to rename signalconn.c.in to signalconn.c and change @callback_map@ in it to #include "signalhashes"

**Comment by b4n** [comment]
@techee OK, I found another probably less crazy way to do it that pleases FreeBSD's sed: `sed  -n '/@callback_map@/,${//n;p;}'`.  I'm not fond of the rematch, but using the range is a lot better than manually looping :)

**Comment by b4n** [comment]
@kugel- yeah it might be simpler indeed.  BTW, if we do that we might want to just put lines like that in the generated file (`signallist.i`):

```
ITEM(some_handler_name)
```

and in *signalconn.c* do something like this:

```c
#define ITEM(n) g_hash_table_insert(hash, (gpointer) #n, G_CALLBACK(n));
#include signallist.i
#undef ITEM
```

like in the good ol' times :)

**Comment by b4n** [comment]
@kugel- here it is https://github.com/b4n/geany/commit/bc3fbd0e0a11d193bbac5a6019bf16af7ed6a857

**Comment by techee** [comment]
@b4n The first sed you suggested "works", the other doesn't with

```
sed: 1: "/@callback_map@/,": expected context address
``` 

@kugel- Your solution "works" too.

Now what "works" means. In

```
's/^.*handler="\([^"]\+\)".*$$/\tg_hash_table_insert(hash, (gpointer) "\1", G_CALLBACK(\1));/p'
```

the OS X sed doesn't recognize the \+ so it doesn't match anything. I used

```
's/^.*handler="\([^"][^"]*\)".*$$/\tg_hash_table_insert(hash, (gpointer) "\1", G_CALLBACK(\1));/p'
```

instead. The second thing is that the \t isn't recognized either

http://stackoverflow.com/questions/5398395/how-can-i-insert-a-tab-character-with-sed-on-os-x

One has to use the real tabulator character. Yeah, osx sed is really funny...

Afterwards I got it compiled just fine and it seems to work alright too. The branch is created on top of a commit before the osx-integration branch merge so I didn't test the integration stuff but I expect it will work once these patches get merged into master.

The only thing I have noticed is this warning during compilation:

```
  CXXLD    libgeany.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libgeany.a(prefix.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libgeany.a(prefix.o) has no symbols
  CXXLD    geany
```

Not quite sure what it means.

**Comment by b4n** [comment]
> the OS X sed doesn't recognize the + so it doesn't match anything.

A right, crap.  But yeah, your solution is OK, so is `[^"]\{1,\}`.

> The second thing is that the \t isn't recognized either

Indeed.  Anyway if we use the new solution, this one at least shouldn't be an issue anymore :)

> The only thing I have noticed is this warning during compilation:
> 
> ```
>  CXXLD    libgeany.la
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: > file: .libs/libgeany.a(prefix.o) has no symbols
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: > file: .libs/libgeany.a(prefix.o) has no symbols
>  CXXLD    geany
> ```
>
> Not quite sure what it means.

Well, it is very possible that prefix.c doesn't have any symbol because it is `#ifdef`ed out as a whole.  If it's a problem I guess we could avoid building `prefix` when we don't use binary relocation.

**Comment by b4n** [comment]
@techee what about https://github.com/b4n/geany/commit/a10bbd08e82bde874ba0e8fce9473e220f9401fa in addition to the previous commit I mentioned?  (the branch is at https://github.com/b4n/geany/commits/kugel-/linkage-cleanup-followup)

**Comment by techee** [comment]
@b4n Works fine, good work :-).

**Comment by b4n** [comment]
More stuff: https://github.com/b4n/geany/commits/kugel-/linkage-cleanup_v2_followup (some commits come with comments)

The Waf changes might be totally abusive, but they work.  The extraction logic is based on https://github.com/codebrainz/geany/commit/da146499e9aabeb499971901fee6e6ac617031cb#diff-f6b01a20e664330cd1efdad6081eb4b7

@eht16 Waf build doesn't work for me on my 64 bits machine: apparently the objects generated for libscintilla (at least) are not PIC, and so can't be used in the shared library:

```
/usr/bin/ld: ./libscintilla.a(ScintillaGTK.cxx.4.o): relocation R_X86_64_32S against `_ZTV12ScintillaGTK' can not be used when making a shared object; recompile with -fPIC
./libscintilla.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

Any idea how to fix this?

**Comment by kugel-** [comment]
I failed at rebase, sorry :(

**Comment by b4n** [comment]
@eht16 @kugel- found a solution that seem to work on x86_64 Linux: apparently if you list features *stlib* **and** *shlib* (in that order), Waf generates a static library out of objects built with options for shared libraries.  I don't know if this is portable though (libtool issues warnings when one tries to link static libraries against shared ones about it not being portable, but maybe it's just that it is afraid the static library's objects are not built with the appropriate options?)

However, https://groups.google.com/forum/#!topic/waf-users/7mGdmNj9riA suggests we should use the "implib" feature, but adding it complains that "feature 'implib' does not exist - bind at least one method to it".  Do you know something about this?

**Comment by eht16** [comment]
@b4n sorry, I have no clue about 'implib'. The docs don't mention it and also after checking the Waf source code I got no clue what exactly 'implib' does and how it should be used.
Since the 'cshlib' hack seems to work, I think it is ok for now.

In the long-term we should drop Waf support anyway.

**Comment by kugel-** [comment]
@eht16 @codebrainz @b4n @ntrel @elextr @frlan I think this ready, would someone like to merge it? The earlier the better (more time for testing). Unless anyone still has specific issues with it?

Pretty please :)

**Comment by techee** [comment]
I agree. The patch is quite wide-spread and has a potential to create merge conflicts (either to other patches or other patches to this one) and the longer the situation lasts, the more unnecessary conflict-resolving work has to be done.

**Comment by elextr** [comment]
Just before its merged, can someone confirm that *all* geany-plugins plugins still work on Linux and Windows?

**Comment by kugel-** [comment]
@eht16 Can you please check native compile on windows? I'm having trouble here, but perhaps my setup is bad

**Comment by kugel-** [comment]
Nevermind, I got it to compile natively on windows using waf (autotools also kind of works but there are also some issues, partly not related to linkage-cleanp).

2 issues with waf:
- the cshlib workaround does not work there, it creates an unworkable ar.exe command line. I suggest going back and -fPIC to the CFLAGS where needed (not needing this was the motivation for this workaround)
- geany.dll is not installed into the bin directory, but to lib. how to fix this in wscript?
- lots of exported headers are not installed

Other than that: I tested geany & geany-plugins (of course, freshly compiled against the linkage-ceanup version of Geany), and it executes fine.

**Comment by codebrainz** [comment]
I haven't really followed this PR since it got forked off the first one for whatever reason, but I guess at least make sure all the discussions/issues from the original PR are addressed. It's too hard to tell for me with massive comment threads spread across two PRs.

**Comment by kugel-** [comment]
With these added commits linkage cleanup compiles and runs fine on windows and linux, including building and running g-p

**Comment by kugel-** [comment]
Sorry, I must have made some mistake when testing g-p on Linux, not all of g-p compiled. The above fix is needed in Geany, and I opened https://github.com/geany/geany-plugins/pull/206 which contains minor fixes so that g-p fully compiles against this branch.

Once compiled, all plugins run fine, though  (but I didn't test every single one to be honest).

**Comment by elextr** [comment]
On 2 April 2015 at 06:16, Thomas Martitz <notifications@github.com> wrote:

> Sorry, I must have made some mistake when testing g-p on Linux, not all of
> g-p compiled. The above fix is needed in Geany, and I opened
> geany/geany-plugins#206 <https://github.com/geany/geany-plugins/pull/206>
> which contains minor fixes so that g-p fully compiles against this branch.
>
> Once compiled, all plugins run fine, though (but I didn't test every
> single one to be honest).
>

​Given that you had to make patches for a couple, probably they should all
be tested, and ​extensively.

**Comment by kugel-** [comment]
Come on, testing *all* plug-ins, *extensively*? That's unreasonable. If you look at the patches you see they only affect their build, not runtime. And given that g-p compiles with -z defs all symbols could be linked (which is everything this PR affects). Plus, the changes are not dependent on this PR. they should be done regardless because they are good anyway. 

I briefly tested the ones I changed,  but testing all plug-ins as a prerequisite for merging this PR is just not justified. It's actually unrealistic for any kind of change. Besides I don't even know how to use most of the plug-ins.

**Comment by elextr** [comment]
On 2 April 2015 at 15:50, Thomas Martitz <notifications@github.com> wrote:

> Come on, testing *all* plug-ins, *extensively*? That's unreasonable. If
> you look at the patches you see they only affect their build, not runtime.
> And given that g-p compiles with -z defs all symbols could be linked (which
> is everything this PR affects). Plus, the changes are not dependent on this
> PR. they should be done regardless because they are good anyway.
>
> I briefly tested the ones I changed, but testing all plug-ins as a
> prerequisite for merging this PR is just not justified. It's actually
> unrealistic for any kind of change. Besides I don't even know how to use
> most of the plug-ins.


​Thomas,

Sorry, I wasn't suggesting that you personally should test them all, just
that they should be tested (as I said in previous posts) by "somebody".
That could be several somebodies a few each.

And "extensively" is necessary because Geany binds symbols lazily, so IIUC
any symbols missing won't show up until they are used, so at least some
attempt to exercise a few of the code paths is needed for a reasonable
confidence, not just that they load since that only calls the plugin init.

No I don't call it unreasonable to test all plugins before a commit which
has the express purpose of modifying the way the plugin interface works in
a significant way​.  But in the end I guess its @b4n's call if he is happy
to do it.

Cheers
Lex

**Comment by kugel-** [comment]
PS: I activated all plug-ins to see if they load OK, of course

**Comment by elextr** [comment]
PS: I'm saying I don't trust the plugins, not this PR :)

**Comment by kugel-** [comment]
Geany doesn't use BIND_LAZY, exactly for the reason that (bad) plugins don't crash the whole process due to undefined symbols. See https://github.com/kugel-/geany/blob/linkage-cleanup/src/plugins.c#L368

**Comment by elextr** [comment]
In that case then, if all Geany-plugins build (I commend your patience getting all the damn dependencies), and load, then it should be fine.  @b4n commit away :)

**Comment by kugel-** [comment]
@eht16 @codebrainz @b4n @ntrel @elextr @frlan I double-checked win32 and Linux know, both compile and run fine, and g-p also compiles and runs fine with https://github.com/geany/geany-plugins/pull/206 against this branch.

What can I do more to get this finally merged? I really think it's ready now, and it probably received more-than-usual testing

**Comment by b4n** [comment]
> and g-p also compiles and runs fine with geany/geany-plugins#206 against this branch.

We should probably make sure this is not needed for GP to build.  Those are (mostly) good changes to GP, yes, but it seem really easy for us not to *require* these and keep compatibility with all plugins.  All should be needed is making sure the API functions are available from the same headers they were before -- probably including *geany.h* in *geanyfunctions.h* would do, wouldn't it?

**Comment by kugel-** [comment]
Am 4. April 2015 15:59:22 MESZ, schrieb Colomban Wendling <notifications@github.com>:
>> and g-p also compiles and runs fine with geany/geany-plugins#206
>against this branch.
>
>We should probably make sure this is not needed for GP to build.  Those
>are (mostly) good changes to GP, yes, but it seem really easy for us
>not to *require* these and keep compatibility with all plugins.  All
>should be needed is making sure the API functions are available from
>the same headers they were before -- probably including *geany.h* in
>*geanyfunctions.h* would do, wouldn't it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geany/geany/pull/429#issuecomment-89582326

Sure we could change the includes in our headers to keep them compiling. But that would be mostly academic, because the plug-ins should include geanyplugin.h anyway, i.e. that PR would land anyway. Regarding non-g-p, yes we can't fix them, but assuming they follow the recommendations they should be fine.

But at the end of the day I don't feel strong about it. However the COMMONLIBS change is absolutely necessary isn't it?

**Comment by b4n** [comment]
> Sure we could change the includes in our headers to keep them compiling. But that would be mostly academic, because the plug-ins should include geanyplugin.h anyway, i.e. that PR would land anyway. Regarding non-g-p, yes we can't fix them, but assuming they follow the recommendations they should be fine.

Yeah that would just be a compatibility thing for broken plugins, they should still get fixed.  And yeah, a plugin following the guidelines should work just fine, but as we saw even GP plugins don't do it right, I can't imagine all others would, so given how easy it is I'd say we do it.  (I have a patch for this).

> However the COMMONLIBS change is absolutely necessary isn't it?

Yes, I guess so.  Here the problem is that a plugin don't link to libgeany, right?  There's not much we can do, and every plugin should be using pkg-config results anyway… but ok, as there seem to be one that don't, maybe some don't -- but we can't do anything for compatibility here.

**Comment by b4n** [comment]
OK, I just tested on FreeBSD (for the first time ever).  First, generic facts *before* this branch:

* Geany works just fine;
* GP has some issues:
  * Debugger and Scope don't build because of incorrect header for `openpty()`;
  * The AT build system has some unportable things that don't work with FreeBSD's default shell (works fine if explicitly using e.g. Bash though).

This suggests not everybody is using GP on FreeBSD… anyway, I have prepared fixes for all of those.

Anyway.  Apart from these small unrelated things, all seem good with the AT build system on FreeBSD after the changes in this PR (of course, altering the include issues discussed above).  I successfully build all plugins, and they all load fine.

**Comment by b4n** [comment]
With Waf (either on FreeBSD or Linux), the Geany core plugins (non-GP) don't work: I get *plugin "xxx" has no plugin_version_check() - ignoring plugin!*.  If I check with `nm` I see that core plugins have all entry points as local symbols (`t`), while GP ones correctly have them global (`T`).  Comparing AT and Waf builds:

```console
$ nm _build_lib_gtk2/__install/lib/geany/export.so | grep plugin_version
0000000000003e60 T plugin_version_check
$ nm _build_waf2/__install/lib/geany/export.so | grep plugin_version
0000000000003c20 t plugin_version_check
```

I don't really know what to look for here though…

**Comment by kugel-** [comment]
@eht16 Do you know a better solution than e90e108 to avoid passing -fvisiblity=hidden to plugins as well?

But the commit gets the job done (I checked that cross-compiled windows also works still)

**Comment by b4n** [comment]
I think I found a cleaner fix for both intermediate object building (67fa81a70435de005a98247f1d8f1621123553f6) and passing export flags (cc61cd03a49c30cb875cddb396106cf0fc5bda43): https://github.com/b4n/geany/commits/kugel-/linkage-cleanup_v3_followup_waf-cleanup

While I think 67fa81a70435de005a98247f1d8f1621123553f6 really look good, maybe cc61cd03a49c30cb875cddb396106cf0fc5bda43 abuses [the `uselib` feature](http://docs.waf.googlecode.com/git/book_16/single.html#_foreign_libraries_and_flags), I'm not sure.

Regardless of whether we use cc61cd03a49c30cb875cddb396106cf0fc5bda43 for this or not, I think that we should just not be putting the `-fvisibility` in the base flags but give the explicitly to the parts needing it just like we do with AT.

Opinions @kugel- @eht16 ?

Tested on both Linux (x86_64) and Windows (x86), and it work, and seem to just do what we want.

**Comment by kugel-** [comment]
Neat! I haven't test yet, but assuming it works it looks a lot better than what I managed with my poor waf knowledge

**Comment by kugel-** [comment]
I tried b4n's latest commits on Windows. Building native with waf went fine, g-p too (though not all plug-ins compiled due to missing dependencies). And geany started successfully and loaded all the plug-ins

@b4n let's go for it :-)

**Comment by eht16** [comment]
@b4n @kugel- To be honest I'm not sure what is best to do with -fvisibility. @b4n's suggestion to only set it where necessary sounds most reasonable to me.

Apart from that, the rest looks fine to me, to that extend one can justify in this huge PR. Exactly for that reason I would also suggest to try to get this PR merged into master to get wider and easier testing. And fix remaining issues afterwards.

**Comment by kugel-** [comment]
Yes! Agreed :)

**Comment by kugel-** [comment]
Regarding comdlg32, perhaps it depends on the mingw fork/version. The one that I use on Linux for cross compiling and the one on Windows both seem to require it on my systems

**Comment by b4n** [comment]
> Why is comdlg32 suddenly necessary? Windows version? Build environment?
On Windows 7 with mingw32 from the Strawberry Perl distribution, it is not necessary.

@eht16 I'm not sure, but if I cross-compile (with autotools) on my Debian GNU/Linux box, if I remove it I get this:
```
  CXXLD    libgeany.la
.libs/libgeany_la-win32.o: In function `win32_show_font_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:633: undefined reference to `_imp__ChooseFontA@4'
.libs/libgeany_la-win32.o: In function `win32_show_color_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:661: undefined reference to `_imp__ChooseColorA@4'
.libs/libgeany_la-win32.o: In function `win32_show_project_open_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:389: undefined reference to `_imp__GetOpenFileNameW@4'
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:393: undefined reference to `_imp__CommDlgExtendedError@0'
.libs/libgeany_la-win32.o: In function `win32_show_document_open_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:450: undefined reference to `_imp__GetOpenFileNameW@4'
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:454: undefined reference to `_imp__CommDlgExtendedError@0'
.libs/libgeany_la-win32.o: In function `win32_show_document_save_as_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:543: undefined reference to `_imp__GetSaveFileNameW@4'
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:547: undefined reference to `_imp__CommDlgExtendedError@0'
.libs/libgeany_la-win32.o: In function `win32_show_file_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:596: undefined reference to `_imp__GetOpenFileNameW@4'
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:600: undefined reference to `_imp__CommDlgExtendedError@0'
.libs/libgeany_la-win32.o: In function `win32_show_pref_file_dialog':
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:719: undefined reference to `_imp__GetOpenFileNameW@4'
/home/ban/progs/geany/_build_cross/src/../../src/win32.c:723: undefined reference to `_imp__CommDlgExtendedError@0'
collect2: error: ld returned 1 exit status
Makefile:623: recipe for target 'libgeany.la' failed
```

And according to https://msdn.microsoft.com/en-us/library/windows/desktop/ms646916%28v=vs.85%29.aspx we need to link `comdlg32` as we use `CommDlgExtendedError()` (and some others).  Maybe it sometimes isn't required just because something else brings it in?

But indeed, on my Windows XP machine I don't need it (Waf build fine without it too).
So I can't tell for sure.  @kugel-?

**Comment by b4n** [comment]
Merged via f3078ebbc60b9747683029df0fa283d8f3e762a5

Thanks everyone for the hard work and patience!

**Comment by eht16** [comment]
Regarding comdlg32: ok fine. I was mostly just curious because on my system/setup I don't need it. But since it's a default Win lib, it probably doesn't matter at all to link against.

And big thanks @b4n too.

**Pull request closed without merging**
