### PR TITLE
Windows: Include "Prof-Gnome" GTK theme from geany-osx

### LINKED ISSUE #3063: New UI on windows is bloated and scaled up
I just upgraded geany from 1.36 to 1.38 (Windows 10, version 1909), and the new UI is very bloated and greyscale and borderless. It looks pretty, but its hard to read. It also takes up WAY to much space, far more than it ever did. And its mostly wasted whitespace. On 1.36, its about 29 pixels between each open file on the left (about the height of the font, plus a small margin), on an 1.38, its 38 pixels between. Thats a 30% increase, but the font doesn't scale to justify the bloat. It makes it a lot harder to have a lot of open files, since the entire file pane is wasted whitespace

In addition, theres no border lines between open files, and everything is SUPER greyed out when it loses keyboard focus. Its pretty! But not very functional. 

Is there any way to turn this off? I always liked geany as a "poweruser" editor. Functional, lightweight, and to the point

### PR DESCRIPTION
**Pull request by eht16**
Closes #3063.

### CODE REVIEW

**Comment by kugel-** [comment]
NAK from my side. Prof-Gnome might be an improvement over adwaita but it's still a bad default theme in my view. Everyone is free to chose a theme to their liking but the default theme should integrate into the target platform. I hate all those GTK apps on windows that look like alien.

That said, I don't use Windows, I only start Geany their for testing specific issues. So in the end of the day I won't block this becuase it doesn't affect *me*. I just don't agree with this PR and IMO it's the wrong direction for Geany on Windows.

**Comment by kugel-** [comment]
I NAK'd the theme but I don't want to block any Adwaita-replacement so please go for it.

**Comment by techee** [comment]
If this PR is going to get merged, I'd just suggest also applying the following patch on top of the theme.

https://github.com/geany/geany-osx/blob/master/prof_gnome_windows_changes.patch

It changes text colors to #000000 instead of the slightly gray which is native for macOS, and also reduces the size of the status bar.

**Comment by eht16** [comment]
> I NAK'd the theme but I don't want to block any Adwaita-replacement so please go for it.

Alright.
https://www.geany.org/documentation/faq/#how-to-change-the-gtk-theme provides users with instructions on how to change the theme and there are also alternatives linked. I guess this is all an improvement over Adwaita, as you also say.

> If this PR is going to get merged, I'd just suggest also applying the following patch on top of the theme.

I added the patch.

Will squash the commits before merge and merge tomorrow if nobody objects.

**Pull request merged**
