### PR TITLE
Added keybindings for custom commands 4-9

### PR DESCRIPTION
**Pull request by tsahlin**
Added additional keybindings so that one can have up to 9 custom editor commands.

Split from previous pull request https://github.com/geany/geany/pull/792

### CODE REVIEW

**Comment by tsahlin** [comment]
Could you point me to some guide or info on how to update the docs?

**Comment by elextr** [comment]
`docs/geany.txt` its in [restructured text](http://docutils.sourceforge.net/rst.html) format.  You would need docutils if you wanted to build the html.

**Comment by eht16** [comment]
Just to make it clear: you don't need to build the HTML from geany.txt for this PR. Just modify the doc/geany.txt file.
However, if you want to build it to test your changes or so, just run `make -C doc geany.html` in the top source directory of Geany. Ideally, do not include the modified geany.html into this PR.

**Comment by elextr** [comment]
It would be good if you could fix the merge conflict as well.

**Comment by b4n** [comment]
Apart from the missing manual update and merge conflict (easy to fix), untested but looks good.

**Comment by b4n** [comment]
Hum, however, do we want to have default bindings for these?  Remember that a binding in Geany overrides one in a plugin, so if a user already had mapped one of those to a plugin it will override the user choice. (AFAIK)

**Comment by b4n** [comment]
https://github.com/b4n/geany/tree/tsahlin/more-cc-kb rebases this on top of matser (fixing the conflict), and updates the documentation

**Comment by eht16** [comment]
I agree with @b4n: we should not add defaults for the new keybindings. Btw, I'm actually one of the users @b4n described: I've bound Ctrl-4 and -5 to the GeanyVC plugin.

**Comment by elextr** [comment]
Since we recommend plugins not set default bindings we probably should not trample all over users existing bindings with Geany itself.  That of course means we can never add any default bindings to Geany evermore.

**Comment by codebrainz** [comment]
It seems like a bug (if true) that adding new default keybinding overrides those set explicitly by the user, for plugins. We should be able to add new keybindings and they should only have effect if the user hasn't customized them like they does for core keybindings.

@b4n any idea where/why this bug exists for the case of plugin keybindings?

**Comment by elextr** [comment]
@codebrainz I believe its because the Geany keybindings are searched before the plugin ones.

**Comment by codebrainz** [comment]
> because the Geany keybindings are searched before the plugin ones

If you mean it searches _default_ Geany keybindings before _customized_ plugin ones, then yeah, that's definitively a bug then. It should do:

1. Customized core keybindings
2. Customized plugin keybindings
3. Default core keybindings
4. Default plugin keybindings

One could argue whether core or plugin keybindings should be used first, but nothing the user has customized (ie. the stuff in home dir) should ever be overridden by system defaults, IMO.

**Comment by elextr** [comment]
> If you mean it searches default Geany keybindings before customized plugin ones, then yeah, that's definitively a bug then. 

IIRC it doesn't differentiate etween customised and default after startup and loading of the config files.

**Comment by eht16** [comment]
Apart from the discussion about Geany's handling of core and plugin keybindings which seem to be an issue on its own, I'd like to get this one ready.

@tsahlin would you mind incoporating b4n's changes (resolved merge conflict & doc update) into this PR and remove the default values for the keybindings? Then we could merge this PR.

**Comment by tsahlin** [comment]
Sorry to say I won't have any time to fix this for another 6 weeks. I'm also really a newbie at git/github so it's not straightforward.

If anyone is willing and can spare the time, feel free to modify the PR to better fit the project.

**Comment by eht16** [comment]
@b4n could you just merge your branch with the resolved conflicts and remove the defaults for the new keybindings? I guess this would least work and we would get this one done.

**Comment by b4n** [comment]
@eht16 done

**Pull request closed without merging**
