### PR TITLE
session.conf split follow-up #2

### PR DESCRIPTION
**Pull request by kugel-**
Also store some UI-related prefs in the new session.conf, that is:

Related to #1392

treeview_position=156
msgwindow_position=593
geometry=0;57;1176;825;0;

Up for discussion:
Move msgwin_orientation as well
-> might be machine dependant, e.g. if you have larger displays at your
workstation compared to your laptop.

### CODE REVIEW

**Comment by kugel-** [comment]
@elextr @abmorris what do you think?

**Comment by abmorris** [comment]
I would add these too:
```
[search]
position_find_x
position_find_y
position_replace_x
position_replace_y
position_fif_x
position_fif_y
```

**Comment by kugel-** [comment]
@abmorris I have prepared that change but it's more involved so I would prefer a separate PR.

**Comment by kugel-** [comment]
@elextr @eht16  @b4n  I'll just merge this into the staging branch if there is no further feedback.

**Comment by elextr** [comment]
Should the settings that select saving window size and window position also be part of the session with these settings they control?

**Comment by kugel-** [comment]
@elextr I don't thin so. Wether to save window positions or not is a a perfectly fine (i.e. conventional) user setting IMO

**Pull request merged**
