### PR TITLE
Basic support for Nimrod language

### PR DESCRIPTION
**Pull request by kamilchm**

### CODE REVIEW

**Comment by scriptum** [comment]
Nimrod was renamed in Nim: http://nim-lang.org/

**Comment by kamilchm** [comment]
Unfortunately, I won't have time to take care of it :(
But if some want to make it happen, It's worth to see http://nim-lang.org/docs/idetools.html and decide if this is not a better solution than this PR.

**Comment by scriptum** [comment]
I just use Python lexer :smile: Works well.

**Comment by MagaTailor** [comment]
All the while, `Nimrod` has been renamed `Nim` :) It would be nice to have native `nim` support in geany.

**Comment by eht16** [comment]
Nim filetype was added in #2085.

**Pull request closed without merging**
