### PR TITLE
Ctags update to p5.9.20211031.0

### PR DESCRIPTION
**Pull request by techee**
This pull request replaces https://github.com/geany/geany/pull/2830 with the latest tagged ctags version.

### CODE REVIEW

**Comment by eht16** [comment]
Tested on Windows: compiles fine and symbol parsing still works. I did not perform more testing than this.
Will test on Linux in daily use from now on.

Also did a short code review on the non-ctags core changes and they are fine to me.
I'd vote for quickly merging this PR, to get more testing by having it in master.

@techee could you squash some commits or re-push the last commit, e.g. with: `git ci --amend --no-edit && git push origin ctags_updatep5.9.20211031.0 --force` to trigger Travis CI (it is working again).

**Comment by techee** [comment]
@eht16 Done. I actually made these commits from a new VM where I forgot to set up .gitconfig so repushed with corrected committer.

**Comment by techee** [comment]
@eht16 Any idea what's wrong with the MINGW build?
```
In file included from /home/travis/build/geany/geany/ctags/main/parse_p.h:17:0,
                 from /home/travis/build/geany/geany/src/tagmanager/tm_ctags.c:18:
/home/travis/build/geany/geany/ctags/main/lregex_p.h:27:10: fatal error: regex.h: No such file or directory
 #include <regex.h>
          ^~~~~~~~~
compilation terminated.
```
I think regex.h was included also before these patches, how was it handled on MINGW?

**Comment by eht16** [comment]
> I think regex.h was included also before these patches, how was it handled on MINGW?

It was included before but only in `ctags/main/lregex.c`.
On Windows, we use the bundled regex library in `ctags/gnu_regex` and this is added to `AM_CPPFLAGS` in `ctagsMakefile.am` but not in `src/tagmanager/` where it is now **also** included because the `regex-h` include itself is now in a header file.

One solution could be:
```
diff --git a/src/tagmanager/Makefile.am b/src/tagmanager/Makefile.am
index 066192b95..53759db0d 100644
--- a/src/tagmanager/Makefile.am
+++ b/src/tagmanager/Makefile.am
@@ -3,6 +3,12 @@ AM_CPPFLAGS = \
 	-I$(top_srcdir)/ctags/main \
 	-DGEANY_PRIVATE \
 	-DG_LOG_DOMAIN=\"Tagmanager\"
+
+if USE_BUNDLED_REGEX
+noinst_LTLIBRARIES += libgnu_regex.la
+AM_CPPFLAGS += -I$(srcdir)/gnu_regex
+endif
+
 AM_CFLAGS = \
 	$(GTK_CFLAGS) \
 	@LIBGEANY_CFLAGS@
```

I'll try this tomorrow on my Windows machine and see if it'll suffice.

**Comment by eht16** [comment]
@techee I opened https://github.com/techee/geany/pull/3 to fix the `regex.h` issue. Corresponding build: https://app.travis-ci.com/github/geany/geany/jobs/547414665.

**Comment by techee** [comment]
@eht16 Thanks!

**Comment by techee** [comment]
> If nobody stops me...

I won't :-).

**Comment by techee** [comment]
Thanks!

What do you think about #2990 (which from my perspective could be merged too) and #2991?

**Pull request merged**
