### PR TITLE
Implement Erlang ctags.

### PR DESCRIPTION
**Pull request by bengtan**
Continued from a previous pull request

https://github.com/geany/geany/pull/437

### CODE REVIEW

**Comment by bengtan** [comment]
Hi,

I've just re-done the previous attempt, with a view to later also adding a unit test in and making changes upstream as well etc.

For now, I've just copied erlang.c from fishman-ctags but there are two points of discussion. 

The first is that I needed to comment out the "include routines.h" in erlang.c because there is no such file for geany. If you want to maintain 100% sync with fishman/ctags, either we'll need to also have an empty routines.h file, or we have to modify upstream to remove the include. 

Secondly, I believe this breaks the existing ctag unit tests. There is an existing file tests/ctags/maze.erl which is a valid erlang file, but tests/ctags/maze.erl.tags looks like it was generated by treating maze.erl as a default text file or something. 

Shall I just re-generate maze.erl.tags?

**Comment by elextr** [comment]
The existing tag test is of course for not having a tag parser :)

So definitely include a correct replacement tags file with the PR.  Naturally you should check that its right as well as just re-generate it :)

A quick search showed that none of our parsers have a "routines.h" include, whereas many (but not all) of the Fishman Ctags ones do, so probably best to be consistent with the rest of Geany, and leave it out.

**Comment by bengtan** [comment]
> The existing tag test is of course for not having a tag parser :)

Good. I thought the same thing but having confirmation is nice. 

When I regenerate (and "make check-TESTS" is successful), maze.erl.tags has about 11 symbols but when I load maze.erl into geany, geany shows about 19 symbols. 

It seems the generated *.tags files don't have all the symbols that geany shows in the IDE editor, and have different information (ie. no line numbers). I'm unfamiliar with the *.tags file format. Is this expected?

**Comment by elextr** [comment]
> When I regenerate (and "make check-TESTS" is successful), maze.erl.tags has about 11 symbols but when I load maze.erl into geany, geany shows about 19 symbols.

> It seems the generated *.tags files don't have all the symbols that geany shows in the IDE editor, and have different information (ie. no line numbers). I'm unfamiliar with the *.tags file format. Is this expected?

I wouldn't have expected it, but maybe there are Erlang symbol types that the tags format can't store, but unfortunately the tagmangler format isn't documented ... and its binary ... and Unicode is a problem and ... long ongoing list of complaints.  @b4n is the expert.

**Comment by bengtan** [comment]
Yeah, same. I don't really know what's going on (I'm just hacking things to make it work). I'll pretend it's okay and just carry on for now. 

I've just made a new commit to re-generated maze.erl.tags and also added a new test.erl unit test. 

Would someone please check the infrastructure is okay so far? If so, then I'll turn my attention to improving erlang.c.

**Comment by b4n** [comment]
> The first is that I needed to comment out the "include routines.h" in erlang.c because there is no such file for geany. If you want to maintain 100% sync with fishman/ctags, either we'll need to also have an empty routines.h file, or we have to modify upstream to remove the include.

If the include really is useless upstream too, sure, but otherwise don't.  I know the infrastructure changed a bit, and I need to update stuff (which is less trivial than it might seem, because some stuff have moved and other have diverged, from the time where CTags was mostly dead).
So, just removing the include in the Geany import for the moment is OK.

> Secondly, I believe this breaks the existing ctag unit tests. There is an existing file tests/ctags/maze.erl which is a valid erlang file, but tests/ctags/maze.erl.tags looks like it was generated by treating maze.erl as a default text file or something.

As @elextr pointed out the old results were just wrong.  I guess I imported the tests from CTags because we had the filetype, and I didn't realize we didn't have the parser.  And it's known that some tests might be just wrong: when [I imported them](https://github.com/geany/geany/commit/8037fa5d10c83d85946ec90c009148a9262f3a71) I generated the results automatically as a basis for checking, but knowing some output might be wrong because of bugs in the parsers (or here, missing parser altogether :))

> Shall I just re-generate maze.erl.tags?

Yes (and you did, perfect)

> It seems the generated *.tags files don't have all the symbols that geany shows in the IDE editor, and have different information (ie. no line numbers). I'm unfamiliar with the *.tags file format. Is this expected? 

It's something we should fix (ideally I'd like to switch to the CTags extended format at some point), but yes it's known.  The generated .tags files prunes duplicate tag, and as the Erlang parser here does not report function signature, the overloading (or whatever it's called in Erlang) will be seen as duplicates -- well, technically they are.

Also, to report tags Geany has to know their types, and it maps CTags kind names to internal generic types (allowing us not to have much language-specific logic around those).  This means that for a tag to be reported in Geany, the CTags kind name has to match one known by Geany (see [tagmanager/src/tm_tag.c](https://github.com/geany/geany/blob/master/tagmanager/src/tm_tag.c#L114-L131)).  And while we have plans to have a separate mapping, you currently need to alter the kind names in the parser itself, like this:

```diff
diff --git a/tagmanager/ctags/erlang.c b/tagmanager/ctags/erlang.c
index 6d51dc8..472ffdf 100644
--- a/tagmanager/ctags/erlang.c
+++ b/tagmanager/ctags/erlang.c
@@ -31,9 +31,9 @@ typedef enum {
 static kindOption ErlangKinds[] = {
     {TRUE, 'd', "macro",    "macro definitions"},
     {TRUE, 'f', "function", "functions"},
-    {TRUE, 'm', "module",   "modules"},
-    {TRUE, 'r', "record",   "record definitions"},
-    {TRUE, 't', "type",     "type definitions"},
+    {TRUE, 'm', "package",  "modules"},
+    {TRUE, 'r', "struct",   "record definitions"},
+    {TRUE, 't', "typedef",  "type definitions"},
 };
 
 /*
```

(with the above you see modules, records and types in the symbol tree and generated .tags file)
Of course you should use the known kind that has the closest semantic, and my example above might be wrong as I don't know Erlang :)

If you want filetype-specific heading in the symbol pane (e.g. to display "Module" and not "Namespace") you can add a special handling for Erlang in [src/symbols.c](https://github.com/geany/geany/blob/master/src/symbols.c#L596).

**Comment by bengtan** [comment]
Thanks for explaining. It was actually a bit more detail than I needed :)

It's good to know that the "baseline" infrastructure is correct (as much as it can be) so far. 

Next, I'll look into the actual parsing code in erlang.c and see if it can be expanded upon.

**Comment by bengtan** [comment]
Hi,

I've finally got around to looking at this again. 

The parsing code is sufficient. The only change I would suggest is the following: 

```
diff --git a/tagmanager/ctags/erlang.c b/tagmanager/ctags/erlang.c
index 6d51dc8..07a77ea 100644
--- a/tagmanager/ctags/erlang.c
+++ b/tagmanager/ctags/erlang.c
@@ -32,8 +32,8 @@ static kindOption ErlangKinds[] = {
        {TRUE, 'd', "macro",    "macro definitions"},
        {TRUE, 'f', "function", "functions"},
        {TRUE, 'm', "module",   "modules"},
-       {TRUE, 'r', "record",   "record definitions"},
-       {TRUE, 't', "type",     "type definitions"},
+       {TRUE, 'r', "struct",   "record definitions"},
+       {TRUE, 't', "typedef",     "type definitions"},
 };
 
 /*
```

so that the tags appear in Geany. You were right all along. 

Compared to your suggestion in the previous comment, I have omitted the change of "module" to "package". I'm not a fan of this change because it makes Geany display the symbols in a nested tree. Since there is only one "namespace" per Erlang file and hence only one entry at the first level, the nesting is redundant.

Do you agree with this change? If so, I'll go ahead and commit to my geany tree.

**Comment by b4n** [comment]
@bengtan sure, go ahead.

**Comment by bengtan** [comment]
Done. Ready for review and pull (I think).

If there are any issues with it, please let me know. Thanks.

**Comment by b4n** [comment]
Merged, thanks!

**Comment by bengtan** [comment]
Hi,

No problem. Glad to be of assistance. Thank you too for maintaining Geany.

Beng

**Pull request merged**
