### PR TITLE
Use python parser from uctags

### LINKED ISSUE #357: Python tags error message
In 1.24.1 I intermittently get errors when editing Python "geany: Warning: ignoring null tag in <the filename>".

Of course being intermittent they never show when I am watching the terminal, only when it is covered by the Geany window. :(

So I can't add any information on what the buffer needs to contain to trigger it.

This issue is just a placeholder so hopefully anyone else who notices will add more info.

### LINKED ISSUE #612: incorrectly detecting keyword method arguments as variables in Python
This has annoyed me for a long time now so I should probably report it...  The screenshot is from 1.24.1 but it's also an issue in 1.25.

example python code:

```
import colander

class DeviceSchema(colander.MappingSchema):
    resourceType = colander.SchemaNode(
        colander.String(),
        description='ResourceType informs the parser which resource type this is',
        missing='Device',
        default='Device',
        validator=colander.Function(lambda x: x == 'Device', msg="resourceType can't be changed")
    )
    identifier = colander.SchemaNode(
        colander.String(),
        description='Instance id from manufacturer, owner and others',
        missing=colander.drop,
        default=colander.drop,
    )
    type = colander.SchemaNode(
        colander.String(),
        description="What kind of device this is",
        missing=colander.required,
    )
    manufacturer = colander.SchemaNode(
        colander.String(),
        description='Name of device manufacturer',
        missing=colander.drop,
    )
```

What it shows:
image

What it should be showing:
image

### LINKED ISSUE #1337: Symbols with non-ASCII Unicode names are not detected by "Symbols"
# Abstract
When naming a variable something that isn't ASCII, but is still a valid Python3 identifier, the variable doesn't show up in the symbols list.

### Test case:

```python
#!/usr/bin/env python3
# coding: utf-8

correct = bool()
对不对='对' if correct else '错'
```
Load up that file in Geany, then open the Symbols tab.

### What I expected to see

"correct" and "对不对" both show up in the Symbols list.

### What happened

Only "correct" shows up in the Symbols list.

## Extra info

1. <output>geany 1.27 (built on 2016-04-17 with GTK 2.24.30, GLib 2.48.0)<output>
2. OS: Ubuntu 16.04.1 LTS

### LINKED ISSUE #1390: Python triple quoted strings that end in a newline escape do not show up in the variables list.
This code adds the name "HEADER_TEMPLATE" to the variables list in the side bar: 

```
HEADER_TEMPLATE = '''
==============
|{:^15}|   {}
==============
'''
```

However this code does not:

```
HEADER_TEMPLATE = '''\
==============
|{:^15}|   {}
==============
'''
```

Running Linux Mint, Geany 1.29, Python mode.

Thanks for all your work! Keep it up!

### LINKED ISSUE #1417: multiline function arguments showing up as variables on the sidebar
Using python, this code should only report 1 variable. 

```
data = dict(
	en = "beer",
	de = "bier",
	es = "cerveza"
)
```

But 4 variables are reported in the sidebar: 

geany

Thanks for all your work!

### LINKED ISSUE #1943: Does not See Python Symbols with PEP484 Type Hints
When applying [PEP484](https://www.python.org/dev/peps/pep-0484/) (Type Hints) to variables, the list of "symbols" in the current file no longer displays the variables using type hints. The parser should be modified to recognize Python symbols using the format `VARIABLE: TYPE = VALUE`, rather than just `VARIABLE = VALUE`.

### LINKED ISSUE #1996: python: method shown as function in symbol tree
The following code results in every method after the first one being shown as a top level function:

```python
class A:
    def method1(self):
        foo = (
)
    def method2(self):
        pass
```

screenshot from 2018-11-25 14-30-51

### PR DESCRIPTION
**Pull request by techee**
This pull request updates the python parser to the uctags version. The most interesting things are from the following commit messages from the pull request:

tm_ctags update:
```
The new parser generates 2 tags for import statements like

from A import B

For A tag of the 'i' kind is generated, for B, tag of the kind 'x' is
generated. B includes A in its scope and when we omit generation of
'i', imports are printed in the sidebar with the full scope information
like

Imports
    django.views.decorators.csrf.csrf_exempt
    django.views.decorators.csrf.csrf_exempt2
    django.views.decorators.http.require_POST

When we generate 'i' and map it to something (I used tm_tag_externvar_t
like for the imports themselves, there's nothing in the tag types
we have that would be a good semantic candidate here), the result
in the sidebar is

Imports
    django.views.decorators.csrf
        csrf_exempt
        csrf_exempt2
    django.views.decorators.http
        require_POST

which is more readable IMO.
```

cython unit test updates:
```
I'm not sure if cython is officially supported by uctags and there's a
slight problem where the new parser omits space between type and
function argument name. E.g. it produces

method(self,inti)

instead of

method(self,int i)
```

Not sure if we should worry about the cython output much - we could also drop the cython unit tests if desired.

Fixes #357, fixes #612, fixes #1337, fixes #1390, fixes #1417, fixes #1943, fixes #1996.

### CODE REVIEW

**Comment by eht16** [comment]
Looks great.
I already fell in love with the new import parsing, just to show my enthusiasm:
Screenshot_2021-11-28_14-07-33
😄 

I'm also not sure about Cython but if it was ok for uctags, it's probably also ok for us.

**Comment by techee** [comment]
Great, happy you like it!

**Comment by techee** [comment]
I created a bug report for the cython problem here https://github.com/universal-ctags/ctags/issues/3216 and added a patch in #2991 that allows us to disable certain kinds in ctags ('z' in this case) which resolves the problem for us.

**Comment by techee** [comment]
Just tested and the new parser fixes these issues: #357, #612, #1337, #1390, #1417, #1943, #1996.

**Comment by techee** [comment]
@eht16 @elextr OK if I merge this PR together with my other open "ctags parser" PRs? This has been open for 3 months and I don't think maturing PRs like a fine wine helps anything. I guess nobody is against using upstream parsers in general, the changes on the Geany side are pretty minimal, mostly just Makefile updates and kind mapping updates and there's not much  to review IMO. I'd really like 2022 to be the year when the ctags sync and TM stuff gets finished, we are pretty close I believe and these open PRs block me from other work.

**Comment by eht16** [comment]
Yes, please. I'm fine with it!

**Comment by elextr** [comment]
Since I had a Python (the snake) in the back yard last weekend its clearly an omen that this should go ahead :smile:

@eht16 is our best snake catcher, so if he is happy its fine.

**Comment by kugel-** [comment]
I'm fine. Please make sure to rebase your branch in order to remove the back-merges before merging.

**Comment by techee** [comment]
OK, done.

@kugel- With the merges I probably introduced some changes that should be addressed in your meson build branch. It should be easy to fix though - it's mainly the removal of the `ctags_` prefix from some parser files and also some parsers now have the corresponding header file which wasn't present before.

**Pull request merged**
