### PR TITLE
Privatize global and publicize docs

### LINKED ISSUE #964: documents_array not exported
My [Code-Format plugin](https://github.com/codebrainz/code-format) uses the `documents_array` symbol, but this symbol is not exported to plugins anymore. Got an undefined symbol error for this in the Debug Messages. Adding `GEANY_API_SYMBOL` macro to `documents_array` in `document.c` fixes the issue.

This was always broken on Windows, and since the `linkage-cleanup` changes, on Linux too.

### PR DESCRIPTION
**Pull request by codebrainz**
Closes #964

### CODE REVIEW

**Comment by codebrainz** [comment]
I should note that I only tested that Geany still builds.

**Comment by elextr** [comment]
Does G-P build against this Geany?

**Comment by codebrainz** [comment]
Dunno see above comment.

I suspect they will though. This can only break plugins which never worked on Windows and haven't worked on Linux/etc for a couple of releases. What's more, with GP build system, these plugin's wouldn't have even linked since it doesn't allow undefined symbols IIRC.

**Comment by elextr** [comment]
Sounds fair.

**Comment by b4n** [comment]
This introduces some Doxygen warnings because references broke.  This fixes them:
```diff
diff --git a/src/document.c b/src/document.c
index 902c2d4..f3de37c 100644
--- a/src/document.c
+++ b/src/document.c
@@ -3273,9 +3273,9 @@ const GdkColor *document_get_status_color(GeanyDocument *doc)
 }
 
 
-/** Accessor function for @ref documents_array items.
+/** Accessor function for @ref GeanyData::documents_array items.
  * @warning Always check the returned document is valid (@c doc->is_valid).
- * @param idx @c documents_array index.
+ * @param idx @c GeanyData::documents_array index.
  * @return @transfer{none} @nullable The document, or @c NULL if @a idx is out of range.
  *
  *  @since 0.16
diff --git a/src/document.h b/src/document.h
index 16316f4..9ecf3fb 100644
--- a/src/document.h
+++ b/src/document.h
@@ -75,7 +75,7 @@ GeanyFilePrefs;
  **/
 typedef struct GeanyDocument
 {
-	/** Flag used to check if this document is valid when iterating @ref documents_array. */
+	/** Flag used to check if this document is valid when iterating @ref GeanyData::documents_array. */
 	gboolean		 is_valid;
 	gint			 index;		/**< Index in the documents array. */
 	/** Whether this document supports source code symbols(tags) to show in the sidebar. */
@@ -118,7 +118,7 @@ typedef struct GeanyDocument
 }
 GeanyDocument;
 
-/** Wraps @ref documents_array so it can be used with C array syntax.
+/** Wraps @ref GeanyData::documents_array so it can be used with C array syntax.
  * @warning Always check the returned document is valid (@c doc->is_valid).
  *
  * Example: @code GeanyDocument *doc = documents[i]; @endcode
@@ -135,7 +135,7 @@ GeanyDocument;
 
 /** Iterates all valid document indexes.
  * Use like a @c for statement.
- * @param i @c guint index for @ref documents_array.
+ * @param i @c guint index for @ref GeanyData::documents_array.
  *
  * Example:
  * @code
```

**Comment by b4n** [comment]
All GP seem to build fine indeed.

**Comment by b4n** [comment]
Otherwise, looks good.

**Pull request merged**
