### PR TITLE
Implement sidebar tree

### PR DESCRIPTION
**Pull request by scriptum**
This would be very handy for projects. Currently adds new tree view in addition to current path view.

It differs from most IDE tree sidebar because it can keep long path like /a/b/c without unnecessary splitting.

Known bugs: 
- folding a dir also folds all nested dirs. Maybe this is GTK treeview feature... 
- after path splitting it doesn't merge parent path back while closing documents but it is concerned with recursive closing (touching tree while closing multiple documents will cause crash).

Screenshot:
sidebar

### CODE REVIEW

**Comment by scriptum** [comment]
What about including in 1.25? It's disabled by default and shouldn't hurt much. Also I'm testing it for more than 1 year without issues.

**Comment by elextr** [comment]
Needs documentation.  What does this do, and why?  Needs to change or add to the manual.

IIUC the original post this changes the behaviour of the existing sidebar without any option, that needs justification.

**Comment by scriptum** [comment]
@elextr yes, first commit was without option, but now it configurable. I updated description.

**Comment by elextr** [comment]
I'm still not sure what it does differently?  Also which tab does it affect?  What does it do differently to filebrowser?  Why not add it to filebrowser instead?

In general (and not a comment on the quality of your patch specifically) I'm not in favour of adding code to Geany to support second rate file system manipulation and browsing jammed in the sidebar, when I have a full featured file manager as part of my desktop, that uses the whole screen, and has no code to maintain in Geany.

On the patch, you said you have an option?  Where is the documentation describing it?

**Comment by kugel-** [comment]
I think you misunderstood this PR. This really just changes the sidebar document list (which exists in Geany) to display as a tree according to the file location. It doesn't implement a browser in anyway.

**Comment by kugel-** [comment]
Oh, and FWIW, I've been using this PR for a while and it's great.

**Comment by elextr** [comment]
@kugel- thanks, I read it as adding a tab, does it just change the documents tab?  I'm still asking what it does differently though :)

**Comment by scriptum** [comment]
> This really just changes the sidebar document list (which exists in Geany) to display as a tree according to the file location. It doesn't implement a browser in anyway.

It is. @elextr I'm sorry for poor description. I'll add docs about it over time.

Patch adds three radio buttons instead of old checkbox "Show Paths":
* Documents only
* Show paths
* Show tree

**Comment by elextr** [comment]
@scriptum ok, now it makes sense, what do you mean "support for projects" ?

How far up the tree does it go to find a common directory, I sometimes open a test file in /tmp, does that mean all paths will then be shown up to the root?

**Comment by kugel-** [comment]
Why don't you just try it man...

**Comment by scriptum** [comment]
> How far up the tree does it go to find a common directory, I sometimes open a test file in /tmp, does that mean all paths will then be shown up to the root?

No, it is clever enough. Better to see once:

**Comment by scriptum** [comment]
And compare:

**Comment by elextr** [comment]
@kugel- if I can't understand it neither can a user, which reflects the fact it is undocumented.  Its not acceptable to tell users, try it and see.  By describing it here @scriptum then knows what to put in the manual.

@scriptum what is it actually doing, I'm afraid the picture doesn't tell me why it decided to show /tmp, /etc and ~ as separate things.

And what did you mean when you said "support for Geany projects"?

**Comment by scriptum** [comment]
> And what did you mean when you said "support for Geany projects"?

It makes a tree of project documents inside project name. But I don't remember exactly, maybe this was old GProject plugin.

**Comment by scriptum** [comment]
> then knows what to put in the manual

I hope there was a manual about sidebar:)

**Comment by elextr** [comment]
> > then knows what to put in the manual

> I hope there was a manual about sidebar:)

Its mentioned in the manual, but not much, thats why its necessary to have an annoying person like me reminding you :)

**Comment by scriptum** [comment]
> Its mentioned in the manual
Like this:
```
* An optional sidebar that can show the following tabs:
  * Documents - A document list, and <=== this is a part we talking about
  * Symbols - A list of symbols in your code.
```
`Documents` section has nothing about paths and context menu.

**Comment by elextr** [comment]
Yes it doesn't say anything, but then in the past it didn't do much. :)

But, if its behaviour now changes depending on having a project open or not, then that needs to be mentioned, probably in a new subsection [here](http://www.geany.org/manual/current/index.html#documents) which can also describe when it displays separate trees (the "smarts" as you called it).

Also I was thinking about the part in preferences [here](http://www.geany.org/manual/current/index.html#sidebar) where you would describe your options and what they do.

I was hoping the questions would get you to describe the behaviour, so you could then just use that as a basis for the manual changes.

**Comment by scriptum** [comment]
> But, if its behaviour now changes depending

Upstream's sidebar depends on having a project too, but it didn't described - now it should be?

> Also I was thinking about the part in preferences

Patch doesn't add preferences and upstream doesn't have preferences too.

I think adding description about context menu items into "Documents" should be enough. But not sure that full tree subdivision algorithm should be in user documentation (at least there is nothing about how "show paths" works internally).

I'll prepare a text for documentation but it will need to be carefully reviewed.

**Comment by elextr** [comment]
On 28 June 2015 at 10:22, RPG <notifications@github.com> wrote:

> But, if its behaviour now changes depending
>
> Upstream's sidebar depends on having a project too, but it didn't
> described - now it should be?
>

​If you are offering (didn't know it did depend on the project)​ you can
add it too.



>  Also I was thinking about the part in preferences
>
> Patch doesn't add preferences and upstream doesn't have preferences too.
>
> I think adding description about context menu items into "Documents"
> should be enough. But not sure that full tree subdivision algorithm should
> be in user documentation (at least there is nothing about how "show paths"
> works internally).
>

​Ok, sure, I thought when you said "option" it went in prefs, but if its
only in the context menu then ok.  Feel free to add show paths description
as well. :)​



> I'll prepare a text for documentation but it will need to be carefully
> reviewed.
>

​No problem.​

**Comment by kugel-** [comment]
Reviewed the whole diff. LGTM apart from the two minor remarks.

Oh, and I love the feature :>

**Comment by scriptum** [comment]
> Just export this function instead of creating a copy. 

Yes I did rewrite some things and there was a little bug I fixed with home directory handling. Now it exported.

> However, since the caller only ever deals always with path names isn't it guaranteed that the input strings are valid utf8, thus g_utf8_strdown() can be used directly?

I'm not sure, so I just followed existing code for path comparison (see `utils_filenamecmp`). I think this may have negative effect in Winodws with non-UTF8 path names.

And docs still in progress.

**Comment by scriptum** [comment]
Fixed. Old commit with comments: https://github.com/scriptum/geany/commit/95dbacff1ed8f5367e0c900d3885eac97117ca7b

**Comment by scriptum** [comment]
Looks like this zero-initialization unnecessary: https://github.com/geany/geany/blob/master/src/sidebar.c#L65

It just could be:
```C
static struct
{
	GtkWidget *close;
	GtkWidget *save;
	GtkWidget *reload;
	GtkWidget *show_paths;
	GtkWidget *find_in_files;
	GtkWidget *expand_all;
	GtkWidget *collapse_all;
}
doc_items;
```
Statics are always zeroed. I can fix that in this PR.

**Comment by scriptum** [comment]
Please, check documentation.

**Comment by scriptum** [comment]
@b4n @elextr ping

**Comment by Frodox** [comment]
@b4n friendly ping:)
Love this feature! I'm using it every day

**Comment by kugel-** [comment]
@b4n @frlan @elextr @codebrainz I would like to merge this, and additionally enable the new tree view by default. Please add your input and review.

**Comment by elextr** [comment]
@scriptum, ooops, sorry this fell through the cracks.

@kugel- can you or @scriptum make a version without conflicts and I will try to find time to test it since I now use the documents list instead of notebook tabs all the time.

From a quick look at the code its ok, but I noticed there are a number of `/**` comments that IIUC doxygen will find and add to the API manual which we don't want, needs fixing.

@scriptum The documentation looks understandable which is fine.

@kugel- I don't care which is the default option.  Do you use the feature? On gtk2 or 3?

**Pull request closed without merging**
