### PR TITLE
Go ctags parser, Scintilla lexer and Geany support improvements

### PR DESCRIPTION
**Pull request by techee**
See the individual patches for more info.

The cpp lexer fix has been submitted to Scintilla here

https://sourceforge.net/p/scintilla/bugs/1711/

but hasn't been reviewed yet.

### CODE REVIEW

**Comment by techee** [comment]
The scintilla patch is in scintilla master now.

**Comment by b4n** [comment]
Apart maybe missing parser tests, LGTM.

Not being able to upstream 2148ba815bd5780b5b678238b75afa12bdf5f552 is sad, but well, it's not yet done on their side.

**Comment by b4n** [comment]
Are the keywords added in #238 relevant?

**Comment by techee** [comment]
> Are the keywords added in #238 relevant?

Yes, they are:

https://golang.org/ref/spec#Predeclared_identifiers

I just didn't know whether to add the functions or not. How is it with other filetypes - do some of them syntax-highlight builtin functions too? And if so, should they be in the primary or the secondary group?

**Comment by elextr** [comment]
> How is it with other filetypes - do some of them syntax-highlight builtin functions too? And if so, should they be in the primary or the secondary group?

One of my pogroms has been to take out anything in the C/C++ filetypes that can be found in tags, so the only things in the filetypes list are the fundamental types like int that won't show up in tags.  Remember the types in the filetypes list may get styled differently, so the fundamental types show up with different sytling :(  No functions are fundamental in C/C++ so there should be none in the filetype list (though people keep trying to sneak types and functions back in :)

But really its up to you how you handle the language you are adding, just remember filetype list items may style differently from tags, do you really want those functions in a different style?  Of course if those functions are never declared anywhere tags can see them then you may have no choice but to include them in the filetypes list.

**Comment by techee** [comment]
I think I'll keep it without the functions - they don't fit neither to the primary category (real keywords) nor to the secondary category (types) so I think it will be better to keep it as it is.

**Comment by techee** [comment]
I have rebased the patches on top of master to pick the latest scintilla, added/updated the tests and changed the lexer_properties to inherit from C.

The last missing piece in the go parser is the variable types - I plan to do it later (when I have time). It will be a bit annoying because for something like

```
var a, b, c, d string
```

it will be necessary to remember the variable names and generate the tags only after we know the type.

**Comment by b4n** [comment]
> I just didn't know whether to add the functions or not. How is it with other filetypes - do some of them syntax-highlight builtin functions too? And if so, should they be in the primary or the secondary group?

I agree with @elextr, I wouldn't include them here, and rather have them in a "stdlib"-like tag file.

**Comment by b4n** [comment]
otherwise LGTM -- tests passing and all :)

**Comment by techee** [comment]
I have squashed the ctags <- fix into the "sync with fishman-ctags" commit, recreated the tags file in the test with the right output and after some thinking also reverted the lexer settings inheritance from C (better not to use it if someone adds something into C settings which doesn't play well with Go).

**Comment by b4n** [comment]
Thanks!

**Pull request merged**
