### PR TITLE
Add 64 and 256 icon sizes to geany.ico

### PR DESCRIPTION
**Pull request by techee**
On Windows with HiDPI screen the Geany ico is really blurry and hopefully
this fixes it. The icon was generated with the following commands:
```
inkscape -w 64 -h 64 -e 64.png scalable/geany.svg
inkscape -w 256 -h 256 -e 256.png scalable/geany.svg
convert 16x16/geany.png 32x32/geany.png 48x48/geany.png 64.png 256.png geany.ico
```
(requires inkscape and imagemagick installed)

Based on

https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons

Microsoft recommends 16, 32, 48, 256 sizes of ico files and 64 for
"classic mode" so the generated sizes should cover all of them.

Note that Thunar on xfce apparently doesn't like the 256 icon size and
displays a preview that looks like a noise but the icon is displayed
correctly on macOS (and I assume Windows too).

I didn't make a Windows build with this icon so I actually haven't
tested it myself if it fixes the problem.

### CODE REVIEW

**Comment by eht16** [comment]
I can confirm the Thunar behavior but don't consider as a too big problem.

I can't or don't know how to test on Windows because I don't have a HiDPI screen in a VM but here a recent GIT master binaries:
https://download.geany.org/snapshots/geany-1.39git20220109_setup.exe
https://download.geany.org/snapshots/geany-plugins-1.39git20220109_setup.exe

**Comment by techee** [comment]
Seems to work (this is from the "start menu" on Windows 11):

image

Unfortunately I can't post a screenshot of the previous state as Windows seems to cache the icon somehow but it was way more blurry.

What's interesting though is that I still don't get the SVG resources rendered correctly and still get the red squares instead even though librsvg is included.

**Comment by techee** [comment]
Ah, but now after installing the plugins, it seems to work.

**Comment by techee** [comment]
Yeah, it seems there's something in the plugins that is necessary for the theme to work. Whan I uninstall the plugins, it doesn't work again.

**Comment by eht16** [comment]
Ok, I will check it later (read: might be also a few days).

Btw, reminder for anyone of us: when we replaced the icon here, we should ideally update the icon in G-P as well (https://github.com/geany/geany-plugins/blob/master/build/geany-plugins.ico). It is an exact copy of the icon here.

**Comment by techee** [comment]
> Btw, reminder for anyone of us: when we replaced the icon here, we should ideally update the icon in G-P as well 

If the PR is considered OK, I can prepare the pull request.

By the way, I just "fixed" the Thunar problem by passing the png's to `convert` in reverse order. I just repushed with this version.

**Comment by eht16** [comment]
> > Btw, reminder for anyone of us: when we replaced the icon here, we should ideally update the icon in G-P as well
> 
> If the PR is considered OK, I can prepare the pull request.

I think pushing it directly to master is ok in this case.

> By the way, I just "fixed" the Thunar problem by passing the png's to `convert` in reverse order. I just repushed with this version.

Great!

Since the mentioned SVG issue is independent of this PR, this one can be merged, right?

**Comment by techee** [comment]
> Since the mentioned SVG issue is independent of this PR, this one can be merged, right?

Sure.

**Comment by intact** [comment]
> By the way, I just "fixed" the Thunar problem by passing the png's to `convert` in reverse order. I just repushed with this version.

Looks like compressed icon (in this case that 256*256 one) can not be last in .ico file, otherwise gdk-pixbuf can not properly read that file (because that libarary  still don't support copressed icons).
[.ICO files are displayed as noise](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/86)

**Comment by eht16** [comment]
> Yeah, it seems there's something in the plugins that is necessary for the theme to work. Whan I uninstall the plugins, it doesn't work again.

"xz" was missing in the Geany installer. Sorry for that.

New installers:
https://download.geany.org/snapshots/geany-1.39git20220110_setup.exe
https://download.geany.org/snapshots/geany-plugins-1.39git20220110_setup.exe

Related PRs:
https://github.com/geany/geany/pull/3082
https://github.com/geany/geany-plugins/pull/1153

**Comment by techee** [comment]
> "xz" was missing in the Geany installer. Sorry for that.

Yes, works great now.

> Looks like compressed icon (in this case that 256*256 one) can not be last in .ico file, otherwise gdk-pixbuf can not properly read that file (because that libarary still don't support copressed icons).
.ICO files are displayed as noise

Thanks for the info. I actually assumed it was the size of the icon that was the problem and that by reversing the order Thunar would find the smaller icons first. In any case, the problem is solved.

**Comment by kugel-** [comment]
LGTM

**Pull request merged**
