### PR TITLE
c++: Properly parse C++11 overrides, finals and noexcepts

### PR DESCRIPTION
**Pull request by b4n**
Based on a Universal CTags patch by Miklos Vajna.

See https://github.com/universal-ctags/ctags/pull/405

---
@elextr please review as the C++ expert ;)

### CODE REVIEW

**Comment by elextr** [comment]
It looks like this treats "override" as a keyword everywhere, but it is in fact only special immediately after a function declaration, elsewhere it can be a normal identifier.  Same applies to "final".

This was done to avoid breaking existing code using "override" or "final" as variable or member or function names.

Making them keywords will likely break symbols parsing for any code that uses them as global variables or class members or functions.

**Comment by elextr** [comment]
Note that final can also be used on classes:

    class fred final {...};

**Comment by b4n** [comment]
> It looks like this treats "override" as a keyword everywhere, but it is in fact only special immediately after a function declaration, elsewhere it can be a normal identifier. Same applies to "final".
> 
> […]
>
> Making them keywords will likely break symbols parsing for any code that uses them as global variables or class members or functions.

Fixed in afa4a9a6afae3ad2306dae6c2df76db81ee97013

> Note that final can also be used on classes:
> 
>     class fred final {...};

This was already (incorrectly) supported, starting with f04df056cdd96be7c3319993d71b8dc36fdd397c.  I fixed handling not to break other uses of `final` as an identifier in 641863c2647c21abb36aedc40ac93e6cc478f920

**Comment by elextr** [comment]
Looks like it will work right AFAICT.

**Comment by b4n** [comment]
you could even give it a try maybe, and try being mean to it? :)

**Comment by codebrainz** [comment]
Don't forget about `noexcept` :)

**Comment by codebrainz** [comment]
Lovely C++ syntax:

```c++
struct Foo final {
  static constexpr auto bar() noexcept { return 1; }
  auto baz() const override final throws {...}
};

**Comment by b4n** [comment]
> Don't forget about `noexcept` :)

Easy enough as it seems to be a real keyword.  Though, this would probably be a separate PR :)

**Comment by b4n** [comment]
> Lovely C++ syntax:
> 
> […]

```console
$ g++ -std=c++11 /tmp/b.cpp -c -o /tmp/b.o
/tmp/b.cpp:2:31: error: ‘bar’ function uses ‘auto’ type specifier without trailing return type
   static constexpr auto bar() noexcept { return 1; }
                               ^
/tmp/b.cpp:2:31: note: deduced return type only available with -std=c++1y or -std=gnu++1y
/tmp/b.cpp:3:29: error: ‘baz’ function uses ‘auto’ type specifier without trailing return type
   auto baz() const override final throws {...}
                             ^
/tmp/b.cpp:3:29: note: deduced return type only available with -std=c++1y or -std=gnu++1y
/tmp/b.cpp:3:29: error: expected ‘;’ at end of member declaration
/tmp/b.cpp:3:35: error: ‘throws’ does not name a type
   auto baz() const override final throws {...}
                                   ^
/tmp/b.cpp:3:8: error: ‘auto Foo::baz() const’ marked final, but is not virtual
   auto baz() const override final throws {...}
        ^
/tmp/b.cpp:3:8: error: ‘auto Foo::baz() const’ marked override, but does not override
```
GCC doesn't seem to love it :)  Okay, let's try C++14:
```console
$ g++ -std=c++14 /tmp/b.cpp -c -o /tmp/b.o
/tmp/b.cpp:3:29: error: expected ‘;’ at end of member declaration
   auto baz() const override final throws {...}
                             ^
/tmp/b.cpp:3:35: error: ‘throws’ does not name a type
   auto baz() const override final throws {...}
                                   ^
/tmp/b.cpp:3:8: error: ‘auto Foo::baz() const’ marked final, but is not virtual
   auto baz() const override final throws {...}
        ^
/tmp/b.cpp:3:8: error: ‘auto Foo::baz() const’ marked override, but does not override
```
Better, but still not so happy :)

**Comment by elextr** [comment]
its `throw(list of exceptions)` not `throws`

yeah function type deduction is c++14

**Comment by b4n** [comment]
okay, this GCC likes:
```C++
struct Base {
  virtual void baz() const throw() = 0;
};

struct Foo final : public Base {
  static constexpr auto bar() noexcept { return 1; }
  virtual void baz() const throw() final override;
};
```
and handling `noexcept` (in addition to `final` and `override` here) makes us parse it OK too :)

**Comment by elextr** [comment]
LGTM :+1:

**Comment by b4n** [comment]
Tiny update adding a missing `isLanguage(lang_cpp)`.

**Pull request merged**
