### PR TITLE
Update c.c

### PR DESCRIPTION
**Pull request by peter-scholtens**
To enable debugging with the option:
CFLAGS='-DDEBUG_C' ./autogen.sh
I needed to modify this file. It now compiles again, but segfaults, any suggestions are welcome.

### CODE REVIEW

**Comment by elextr** [comment]
`scopeKind` is not a string.

Why do you think you need to make this change?  It doesn't make sense.  What has it got to do with `-DDEBUG`?

**Comment by codebrainz** [comment]
> What has it got to do with -DDEBUG?

The code in question is guarded with a `DEBUG_C` preprocessor macro, but judging by the comment I doubt anyone since the original TM author has ever used it.

**Comment by elextr** [comment]
The original code should compile fine, all arguments to the `printf` are `char*` matching the `%s`.  So why does it need to be changed?  @peter-scholtens please describe the actual original problem, not the problem caused by your erroneous "fix".

**Comment by elextr** [comment]
@codebrainz is probably right it hasn't been used since Tyrannosaurs programmed in assembler.  So describing the original problem would allow people to assist with the actual problem.

**Comment by codebrainz** [comment]
@elextr well he did mention it didn't compile with that `DEBUG_C` defined, but it would be helpful to give the resulting compile error so everyone doesn't have to re-compile themselves to see it.

```
parsers/c.c: In function ‘printTagEntry’:
parsers/c.c:555:7: error: ‘tagEntryInfo {aka const struct sTagEntryInfo}’ has no member named ‘kindName’; did you mean ‘name’?
  tag->kindName, tag->extensionFields.implementation, tag->extensionFields.scope[1],
       ^~~~~~~~
       name
parsers/c.c:555:75: error: ‘const struct <anonymous>’ has no member named ‘scope’; did you mean ‘scopeKind’?
  tag->kindName, tag->extensionFields.implementation, tag->extensionFields.scope[1],
                                                                           ^~~~~
                                                                           scopeKind
```

**Comment by peter-scholtens** [comment]
My original plan was to solve https://github.com/geany/geany/issues/728, and to study the root cause of that, so I thought it maybe handy to use this debug option. But if it is out-of-date then it is not quite useful. Then please ignore/remove the pull request and give me a hint how to solve it.

**Comment by elextr** [comment]
>  Then please ignore/remove the pull request and

You can always close your own pull requests and issues.

> give me a hint how to solve it.

On #728 would be the best place.

**Pull request closed without merging**
