### PR TITLE
Lithuanian translation modified

### PR DESCRIPTION
**Pull request by zygimantus**

### CODE REVIEW

**Comment by frlan** [comment]
I needed to solve a few conflicts manually but finally merged it. Please, if you have the chance, get a recent checkout and run make update-po inside po folder and recheck your translation. This would be awesome.

**Comment by zygimantus** [comment]
Hi! Can you give the complete set commands to do that `make update-po`? Because I am failing to do that.

**Comment by frlan** [comment]
For unix-like systems:

1. git checkout of Geany sources
2. cd path/to/geany/sources
3. ./autogen.sh 
4. cd po
5. make update-po

**Comment by zygimantus** [comment]
Thanks 1-4 worked like a charm, but no 5. gives error: make: *** No rule to make target 'update-po'.

**Comment by frlan** [comment]
Do you have gettext and intltool installed on your system? If not, please do so and rerun autogen.sh. More debugging would need detailed information e.g. complete output from autogen-run.

**Comment by frlan** [comment]
You could also use lt.po provided on http://i18n.geany.org which is updated every night from recent master

**Pull request merged**
