### PR TITLE
Corrected a Russian translation of the word Appearance in Preferences

### PR DESCRIPTION
**Pull request by dmitryunruh**

### CODE REVIEW

**Comment by frlan** [comment]
@dmitryunruh Thanks for the suggestion, but I'm not certain the new translation is fitting better. Maybe we could use "Вид" only
@scriptum What do you think?

**Comment by dmitryunruh** [comment]
Hello Frank!

The word "Appearance" has several translations into Russian language,
include "Вид" and "Появление" depending on the context.
The word "Вид" is synonym for the word "View".
The word "Появление", in our case, is synonym for the word "Order".
The Appearance option in the Preferences means that functions in the
symbol list will be shown in order by appearance. So the word
"Появление" in this case is more suitable.
Additionally, ru.po already contains the similar translation:
msgid "Sort by _Appearance"
msgstr "Сортировать по _появлению"

Sincerely,
Dmitry Unruh.

**Comment by dmitryunruh** [comment]
@frlan Can someone else help us to put an end to this issue?

**Comment by Skif-off** [comment]
I'm use Geany and I like Geany, so my fifty cents: I'm not a professional translator, but "Внешний вид" is not correct, "Вид" too. I think, in this case "Появление" is good solution.

I think, maybe would be nice to replace names of sort method on "by name" and "by appearance" (or maybe "by order" will be better): it will be looks more accurate.

**Comment by frlan** [comment]
OK. After talking with a friend of mine I'll merge this -- Thanks for the input (I also learned something for myself ;)). 

Rephrasing should be done in another pr/issue IMHO -- actually not much opinion about ;)

**Pull request merged**
