### PR TITLE
Create file.md

### PR DESCRIPTION
**Pull request by peter-scholtens**
A small set of examples as reminders of how to use Markdown.
Simply uploading this file is not sufficient, but it is unclear to me how the file ```data/Makefile``` can be generated to include the template, please help!

### CODE REVIEW

**Comment by elextr** [comment]
I think you only need to add it to the list [here](https://github.com/geany/geany/blob/d6ce258cec790da1e81db48476507bb114c7e482/data/Makefile.am#L109).  IIUC meson copies the [whole directory](https://github.com/geany/geany/blob/d6ce258cec790da1e81db48476507bb114c7e482/data/meson.build#L1) without listing explicit contents.

**Comment by peter-scholtens** [comment]
I tried that, but it fails with:
```make[2]: *** No rule to make target 'templates/files/main.md', needed by 'all-am'.  Stop.```

**Comment by elextr** [comment]
Did you miss a trailing backslash?

**Comment by peter-scholtens** [comment]
Locally I have the trailing backslash, and no space after that, git diff report:
```
@@ -103,6 +103,7 @@ template_files = \
        templates/files/main.cxx \
        templates/files/main.d \
        templates/files/main.java \
+       templates/files/main.md \
        templates/files/main.py \
        templates/files/main.vala \
        templates/files/module.erl \
```

**Comment by elextr** [comment]
Do you still have the main.md file in that directory?

**Comment by peter-scholtens** [comment]
Yes, that was there. But I had renamed it from an earlier trial as `file.md` to `main.md`. No I see a Markdown template item in the pulldown menu, which however contains both of them `main.md` and `file.md`!? Like a kind of memory effect.

**Comment by eht16** [comment]
Nice idea.

If there are no objections, I'll merge this in a few days.

**Pull request merged**
