### PR TITLE
go files should use tabs

### PR DESCRIPTION
**Pull request by bontibon**

### CODE REVIEW

**Comment by b4n** [comment]
Why?  we should not enforce a setting like that unless it's absolutely necessary.  And even, default indent settings are to use tabs.

**Comment by bontibon** [comment]
@b4n Go developers expect Go code to be indented with tabs, as that is what the `go fmt` tool dictates. I would wager that having tabs as default is what the majority of Go programmers would prefer.

**Comment by b4n** [comment]
Similarly, Python prefers spaces, and that's what PEP8 does.  Though, we don't have it in the filetype file.

The reason is probably that changing this is relatively easy if you know the setting, but quite hard to discover; and IMO everything should follow the general settings (by default) unless doing so would break something (like e.g. Makefiles, where tabs are *required*, not just as style but as syntax).

**Comment by bontibon** [comment]
I understand the point you are making, @b4n. The reason I proposed the change is that my default indent type is spaces, and I find myself clicking "Document -> Indent Type -> Tabs" every time I open a new Go file.  I suppose having per-language style overrides as part of the GUI would be nice, but that's an entirely different issue.

Closing.

**Comment by techee** [comment]
@b4n Just to explain - the "recommendation" to use tabs instead of spaces is much stronger in go than in python because of the (fantastic) 'go fmt' tool. The recommendation is to have 'go fmt' run as a git commit hook so all commits are formatted with it (so whitespace changes basically disappear from the diffs) and have go fmt applied automatically e.g. on file save in editor [1]. Go also enforces having the '{' on the same line as while/if/... and anything else is a syntax error so go itself is pretty strict about formatting. I love this strict whitespace/indentation approach - I used to be working on a project developed over decades by many different companies and whitespace tends to be a complete mess (I've seen indents of 2,3,4,5,6,8 in a single file using both tabs and spaces).

That said, yes, the right solution would probably be having some user-visible per-file settings.

[1] In longer term I plan making a plugin that would be a generalization of  Geany's "Send selection to" feature (I might use the MiniScript plugin as a start point) that would behave more like TextMate bundles. In the config part one could specify what stdin becomes (selection, whole file), the plugin would export various Geany settings (project base path, current file name, other open file names, indentation used, etc.) as environment variables so these would be accessible from the started process/script. One could also specify what happens with stdout (replaces current document, opens a new tab with it, writes it to messages window, etc.) and one of the options would be also automatically performing the given action on file save (based on the current document satisfying given file pattern).

**Comment by elextr** [comment]
> That said, yes, the right solution would probably be having some user-visible per-file settings.

menu->document->indent type->tabs/spaces/utter stupidity

(well ok the last is "spaces and tabs" but I like my name better :)

Whilst the document remains part of a session file the setting is remembered for the document.

I always make a new filetypes.python in every config with a [indentation] type=0 setting.  I still don't understand why we cannot have a default setting in the system filetypes file that matches PEP8, the user can still override it with their own filetype file or a per file setting as above.

**Comment by techee** [comment]
@elextr I understand Colomban's point about the filetype configuration to be hard to discover as it's not accessible from the editor. But maybe one way could be having it e.g. in filetype_extensions.conf and have something like

# 0 is spaces, 1 is tabs, 2 is tab & spaces
[Indentation]
C=0
Python=1
Go=1

**Comment by elextr** [comment]
So its hard to discover, so we will make it impossible to do it at all :( 

Doesn't make sense to me.

**Comment by codebrainz** [comment]
IMO, the best is to use the most expected/useful default, if there is one (like Python or Go has).

**Comment by b4n** [comment]
@codebrainz I agree the best default is the recommendation for the language, but we also have a setting supposed to chose the global default, and that's where I find it a bit problematic, as if we have per-filetype settings the global one will not apply to those.  And as the per-filetype thing is not very discoverable but in the docs, it's a bit questionable whether we should use it by default.
If we had a way to easily change the setting per-filetype, why not.  Also, it could be considered an incompatible change, since someone with one setting will get another one.  This could be particularly annoying if people have specifically create projects to have different settings depending on the source tree.

But anyway, if you all seem to have a strong opinion for having them as default, I don't mind so much, I'm just afraid it will annoy people with broken defaults, and confuse people wanting to change the setting.

**Comment by b4n** [comment]
> So its hard to discover, so we will make it impossible to do it at all :( 

Definitely not, you're welcome to change that on you installs of course :)
And I'd welcome a way of having specific settings that are easily discoverable and editable.

**Comment by elextr** [comment]
> And I'd welcome a way of having specific settings that are easily discoverable and editable.

What about just adding some text to the preferences->editor->indentation page saying "To set defaults per filetype edit the filetype configuration files" or similar.

**Pull request closed without merging**
