### PR TITLE
Add po/*.po~ to gitignore

### PR DESCRIPTION
**Pull request by Davidy22**
After recent progress update messages in other pull requests I checked out the shiny latest to make sure all is still well and ready to pave the way for the one pr I have that depends on it, and after building I found a bunch of junk in the git status. Added a line to gitignore to hide the compile time generated junk.

### CODE REVIEW

**Comment by eht16** [comment]
This would only hide the real cause without fixing it.
The problem is already reported in https://github.com/geany/geany/issues/3077.

**Comment by Davidy22** [comment]
oh, missed that, well nice to see it looks like we have an idea of a fix in there

**Comment by kugel-** [comment]
I think we might still need this.

**Comment by Davidy22** [comment]
Well I'll undelete my branch then, if you want it you can reopen and merge

**Pull request closed without merging**
