### PR TITLE
WIP: Drop GTK2 support

### PR DESCRIPTION
**Pull request by b4n**

### CODE REVIEW

**Comment by b4n** [comment]
As we're talking about dropping GTK2, here's a shot at cleaning things up.  I intentionally kept some of the infrastructure to support more than one version for when we'll start GTK4 support (even though I don't yet know how that would look like) so it's a little easier; but all GTK2-related stuff should be gone.

One noteworthy thing that isn't completely gone is *gtkcompat.h* header: I dropped all actual use from Geany itself, but for the moment I have been conservative on removing it from anywhere plugins could be reaching it from.

**Comment by b4n** [comment]
BTW, feel free to take over if/when needed, as I am famous for lack of time lately :wink:

**Comment by codebrainz** [comment]
> BTW, feel free to take over if/when needed, as I am famous for lack of time lately

If you lack time, then why spend all that time completely re-creating #2602 instead of just requesting or pushing changes to it?

**Comment by b4n** [comment]
@codebrainz Oops.  Probably because I didn't see it, and didn't think about looking for it even -- which is stupid on my part.  Well, so I'll try and see if there's anything worth in here for yours.

**Comment by codebrainz** [comment]
@b4n the GDK keysyms stuff for sure, and making the CI work. I allowed commits by maintainers on that branch and I think you have push rights on my fork anyway, feel free to just push anything you think is useful.

**Pull request closed without merging**
