### PR TITLE
Adding more/missing file extensions and beginning manpage support

### PR DESCRIPTION
**Pull request by DevynCJohnson**
I added some file extensions. I do a lot of programming and I noticed that some files are not auto-detected by Geany. For instance, Assembly source code files for the 8051 use the *.a51 file-extension which is not included in Geany. This should help fix some of those issues.

I also added "Manpage" and "README". In my opinion, highlighting features for manpages should be added. My commit should help to start adding support, if my commit is accepted.

### CODE REVIEW

**Comment by elextr** [comment]
Please separate this out so the manpage filetype and its extensions are a separate request from the extra extensions.  Also please separate the extra extensions into multiple commits so you can explain what the extensions are for.  Just saying "I added lotsa extensions" won't help some poor sod in five years who looks back to see why *that* was added :smile: 

IRO the manpage filetype, does it work? In particular it has no lexer specified so the list of keywords will have no effect.  AFAICT Scintilla has no manpage lexer so you would need that first for highlighting to work.

**Comment by DevynCJohnson** [comment]
Okay, I will work on that.

Sorry, I should have been more clear. The manpage highlighting may not work because I do not know how to add the Scintilla lexer. I added the file extensions and keywords so that it would be easier for someone to add the lexer.

Sorry again. Other GitHub projects I have helped with liked all my changes to come as one commit. I will redo the changes to comply with Geany's project standards.

**Comment by DevynCJohnson** [comment]
Okay, I did two commits so far. I will do the rest after I know that I am performing the commits in a more acceptable way.

By the way, should I use the "ci skip" flag when committing changes to the filetype_extensions.conf file?

**Comment by elextr** [comment]
> Sorry, I should have been more clear. The manpage highlighting may not work because I do not know how to add the Scintilla lexer. I added the file extensions and keywords so that it would be easier for someone to add the lexer.

Lexers are written in C++, and AFAICS Scintilla doesn't have a manpage one, so you would need to write it.  You could try an existing lexer to see if it works "well enough", though to be honest I don't know which one to suggest.  Without a lexer or parser the filetype doesn't do much, so I don't know if we would add it.

> Other GitHub projects I have helped with liked all my changes to come as one commit. I will redo the changes to comply with Geany's project standards.

NP, the idea is that separate things be separate PRs so any questionable things can be discussed without holding up things that could be accepted immediately.

Splitting up the extensions is simply so they can be described in the commit message "Added extensions for XXX, see (some reference that its a valid extension)" without the commit message getting too long by describing lots in the one message.

> By the way, should I use the "ci skip" flag when committing changes to the filetype_extensions.conf file?

Since nothing is built from `filetype_extensions.conf` and no tests use it then it is probably nice to save a few Travis compute cycles.

**Comment by DevynCJohnson** [comment]
@elextr , thanks for the pointers. I will be sure to use the "ci skip" flag for non-coded commits and pull-requests.

I intend on being a long-term and regular team member (if that is okay with the team), so any tips are greatly appreciated.

**Comment by elextr** [comment]
Welcome, some tips:

1) read HACKING
2) read HACKING
3) read HACKING
4) don't worry about mistakes, we (almost) never bite although we can bark loudly sometimes :smile: 
5) ask about things on the ML, or Issue or PR before committing lots of work is usually a good idea, and do be patient, everyone is a volunteer

**Comment by DevynCJohnson** [comment]
@elextr , thanks for the tips. I had read the HACKING file after I had submitted those first few commits and PRs (better late than never). That is why I am now on the mailing list and sharing my ideas and listening to everyone's feedback.

Oh, I just noticed that you must be Lex Trotman. (^u^)

**Comment by DevynCJohnson** [comment]
I will close this PR due to
- Scintilla does not yet support Man-pages
- GitHub says "This branch has conflicts that must be resolved"

**Pull request closed without merging**
