### PR TITLE
Doxygen fixes

### PR DESCRIPTION
**Pull request by kugel-**
Various fixups for better plugin api docs and in preparation to generating gtkdoc from the doxygen xml output.

### CODE REVIEW

**Comment by kugel-** [comment]
The follow-up effort to this can be found at https://github.com/kugel-/geany/tree/doxygen2gtkdoc

There is the script to generate the gtkdoc and to create a .vapi, .gir and .typelib automatically for the plugin API.

**Comment by b4n** [comment]
Before going further, apart from (some) actual documentation changes, I don't see no use outside your automatic generation thing, in which case it should be part of it.

**Comment by kugel-** [comment]
The changes are various enough, I think it would be preferable to make one PR each.

**Comment by b4n** [comment]
This one can be closed, right?  Feel free to reopen otherwise.

**Pull request closed without merging**
