### PR TITLE
Rewrite PHP tag creation script using up to date upstream tag definit…

### LINKED ISSUE #584: Missing PHP functions in code hints
I noticed `mysqli_connect()` is missing from the PHP hint/completion list. I don't know if there are other functions missing, but the other mysqli_* functions seem to be there...

### PR DESCRIPTION
**Pull request by eht16**
…ions

Fixes #584.

### CODE REVIEW

**Comment by b4n** [comment]
Good start!

But there are some things that don't appear in the output.  Basically filtering on `id` prefix doesn't seem like a great idea, as members generally don't start with `function` but with the parent name.

Here are changes I made playing with your script, which I think give better results:

Some of the changes:
* escape the `tag_name` in the RE match, so it can match variable (`$`) and namespaces (`\`)
* split out the scope in the `scope` field
* don't filter on `id` (as the list already should contain only interesting stuff)
* better tag type selection (member, variable, method or function)
* class tags (based on their `__construct()`)
* restore `# format` header

```diff
diff --git a/scripts/create_php_tags.py b/scripts/create_php_tags.py
index 43ae70b..31d5252 100644
--- a/scripts/create_php_tags.py
+++ b/scripts/create_php_tags.py
@@ -16,19 +16,40 @@ import re
 
 
 UPSTREAM_TAG_DEFINITION = 'http://doc.php.net/downloads/json/php_manual_en.json'
-TAG_TEMPLATE = '{tag_name}{TA_TYPE:c}{TYPE_FUNCTION}{TA_ARGLIST:c}{arg_list}{TA_VARTYPE:c}{return_type}\n'
 PROTOTYPE_RE = r'^(?P<return_type>.*) {tag_name}(?P<arg_list>\(.*\))$'
 
 # (from tagmanager/src/tm_tag.c:90)
 TA_NAME = 200
 TA_TYPE = 204
 TA_ARGLIST = 205
+TA_SCOPE = 206
 TA_VARTYPE = 207
-# TMTagType (tagmanager/src/tm_tag.h:58)
-TYPE_FUNCTION = 128
+# TMTagType (tagmanager/src/tm_tag.h:49)
+TYPE_CLASS = 1
+TYPE_FUNCTION = 16
+TYPE_MEMBER = 64
+TYPE_METHOD = 128
+TYPE_VARIABLE = 16384
 
 
 #----------------------------------------------------------------------
+def normalize_name(name):
+    """ Replace namespace separator with class separators, as Geany only
+        understands the latter """
+    return name.replace('\\', '::')
+
+
+def split_scope(name):
+    """ Splits the scope from the member, and returns (scope, member).
+        Returned scope is None if the name is not a member """
+    name = normalize_name(name)
+    sep_pos = name.rfind('::')
+    if sep_pos < 0:
+        return None, name
+    else:
+        return name[:sep_pos], name[sep_pos+2:]
+
+
 def parse_and_create_php_tags_file():
     # download upstream definition
     response = urlopen(UPSTREAM_TAG_DEFINITION)
@@ -43,28 +64,38 @@ def parse_and_create_php_tags_file():
     # generate tags
     tag_list = list()
     for tag_name, tag_definition in definitions.items():
-        if tag_definition['id'].startswith('function.'):
-            prototype_re = PROTOTYPE_RE.format(tag_name=tag_name)
-            match = re.match(prototype_re, tag_definition['prototype'])
-            if match:
-                return_type = match.group('return_type')
-                arg_list = match.group('arg_list')
-                tag_list.append((tag_name, return_type, arg_list))
+        prototype_re = PROTOTYPE_RE.format(tag_name=re.escape(tag_name))
+        match = re.match(prototype_re, tag_definition['prototype'])
+        if match:
+            return_type = normalize_name(match.group('return_type'))
+            arg_list = match.group('arg_list')
+
+            scope, tag_name = split_scope(tag_name)
+            if tag_name[0] == '$':
+                tag_type = TYPE_MEMBER if scope is not None else TYPE_VARIABLE
+            else:
+                tag_type = TYPE_METHOD if scope is not None else TYPE_FUNCTION
+            tag_list.append((tag_name, tag_type, return_type, arg_list, scope))
+            # Also create a class tag when encountering a __construct()
+            if tag_name == '__construct' and scope is not None:
+                scope, tag_name = split_scope(scope)
+                tag_list.append((tag_name, TYPE_CLASS, None, arg_list, scope))
 
     # write tags
     script_dir = dirname(__file__)
     tags_file_path = join(script_dir, '..', 'data', 'php.tags')
     with open(tags_file_path, 'w') as tags_file:
-        for tag_name, return_type, arg_list in sorted(tag_list):
-            tag_line = TAG_TEMPLATE.format(
-                tag_name=tag_name,
-                arg_list=arg_list,
-                return_type=return_type,
-                TA_TYPE=TA_TYPE,
-                TYPE_FUNCTION=TYPE_FUNCTION,
-                TA_ARGLIST=TA_ARGLIST,
-                TA_VARTYPE=TA_VARTYPE)
-            tags_file.write(tag_line)
+        tags_file.write('# format=tagmanager\n')
+        for tag_name, tag_type, return_type, arg_list, scope in sorted(tag_list):
+            tag_line = '{}'.format(tag_name)
+            for attr, type in [(tag_type, TA_TYPE),
+                               (arg_list, TA_ARGLIST),
+                               (return_type, TA_VARTYPE),
+                               (scope, TA_SCOPE)]:
+                if attr is not None:
+                    tag_line += '{type:c}{attr}'.format(type=type, attr=attr)
+
+            tags_file.write(tag_line + '\n')
     print(u'Created: {} with {} tags'.format(tags_file_path, len(tag_list)))
 
 
```


---

While playing with this, I found http://doc.php.net/downloads/sqlite/ which might (or might not) be interesting.  It seems more to be accurate (like `mysqli_affected_rows` has its two entries, `mysqli_affected_rows` (procedural) and `mysqli.$affected_rows` (OO)), and to be better split, like it has separate `return_type` -- but also has separate arguments, which is less handy for us, as we need to rebuild the displayable arglist.

**Comment by eht16** [comment]
Woohoo, looks great.
I just pushed your changes and updated the php.tags file.

**Comment by eht16** [comment]
Do we want to merge this for 1.27?

**Comment by b4n** [comment]
@eht16 if it still works, sure :)

**Comment by eht16** [comment]
I've just ran the script to generate an up2date php.tags file and then squashed the commits together in case we want to merge it.

It would have been cool if we got any feedback from some PHP users in #584. After my quick tests the new list is better but I don't know PHP well enough to really judge.

**Comment by b4n** [comment]
@eht16 IIRC when I tested and provided improvements, I saw it was pretty good, but missed a few things (i.e. the `mysqli_affected_rows` thing), but it wasn't our fault but an improper source.  Maybe they fixed it, I don't know.
IMO it's fine to merge, we can always improve it later on.

**Comment by b4n** [comment]
It might miss the header `# format=tagmanager`, which is useful to avoid guessing the format.  Will check later if nobody beats me to it

**Comment by eht16** [comment]
Er, the header should be there. See https://github.com/geany/geany/pull/603/files#diff-ff00621c6c43bedd4ccb380be0dcecdcR90 and https://github.com/eht16/geany/blob/create_php_tags_update/data/php.tags#L1 or do I miss something?

**Comment by b4n** [comment]
@eht16 indeed, my bad I was looking at an old diff, sorry

**Pull request merged**
