### PR TITLE
Minor README updates

### PR DESCRIPTION
**Pull request by techee**
The end of README isn't rendered very nicely on github - fix that.

Plus minor updates like punctuation, "new" macOS name and sending patches through  github.

### CODE REVIEW

**Comment by b4n** [comment]
LGBI too, same remarks.

**Comment by codebrainz** [comment]
Or just call it "Mac OS" which is the same name as ever and works for all versions, not just macOs Sierra.

**Comment by techee** [comment]
@codebrainz (and others): Yeah, "Mac OS" sounds most universal - will use that.

**Comment by b4n** [comment]
for me "Mac OS" (and all typographies of it, "macOS" included) make me think of that old, well, MacOS (9 and older) :)

**Comment by techee** [comment]
Yeah:

till 2001: Mac OS
2001-2012: Mac OS X
2012-2016: OS X
2016: macOS

In any case, "Mac" and "OS" seem to be the most frequent words across releases:

OS - 4x (i.e. all the time)
Mac - 3x (and missing in the OS name just for 4 years)
X - 2x

So the numerical analysis suggests some form of "Mac" and "OS" is the most universal name :-).

**Comment by elextr** [comment]
Lies damn lies and statistics ... :smile: 

But anything that doesn't suggest it _only_ runs on the (still in beta IIUC) macOS or the olde OSX is fine IMHO. Unless it does in fact only run on one or the other of course.

**Pull request merged**
