### PR TITLE
Add batch file ctags parser

### PR DESCRIPTION
**Pull request by techee**

### CODE REVIEW

**Comment by elextr** [comment]
Does `.bat` still exist on a supported version of Windows?

**Comment by techee** [comment]
Haven't booted a Windows machine but I'd be surprised if it were dropped by Microsoft. (@eht16 am I right?)

**Comment by elextr** [comment]
I asked because it didn't work on the Windows 11 tablet, but maybe thats a tablet thing?

**Comment by eht16** [comment]
windows_batch

On my old Windows 7 it still works. I cannot anything newer, I never will use any Windows version beyong 7.

I guess our issue tracker will tell us when Batch files are not supported any longer, each time a user uses @elextr's great build system commands, a Windows batch file is created and executed (https://github.com/geany/geany/blob/master/src/geany-run-helper.bat) :D.

And since we already have the filetype and @techee did already the work, why not adding it?

**Comment by elextr** [comment]
> I guess our issue tracker will tell us when Batch files are not supported any longer, each time a user uses @elextr's great build system commands, a Windows batch file is created and executed 

Hmmm, written by @b4n and merged by @eht16 ... not my fault ;-)

But yes, if `.bat` flew away we would hear about it  (bat, flew away ... ok, I'll see myself out :-)

> And since we already have the filetype and @techee did already the work, why not adding it?

Ok

**Pull request merged**
