### PR TITLE
Update Scintilla to version 3.21.1

### PR DESCRIPTION
**Pull request by eht16**

### CODE REVIEW

**Comment by zhirshya** [comment]
eht16:scintilla/update-3-20-0 solved problem[#2518](https://github.com/geany/geany/issues/2518).
Thanks everyone.

**Comment by Skif-off** [comment]
@eht16, maybe you can try to update up to 3.21.0?

**Comment by eht16** [comment]
Yeah, will do soon. Thanks for the reminder.

**Comment by eht16** [comment]
Updated this PR to contain the update to Scintilla 3.21.0.

**Comment by Skif-off** [comment]
Thanks! I tried yesterday, works fine.

**Comment by elextr** [comment]
WFM LM20 GTK3.

**Comment by elextr** [comment]
Oh, 3.21.1 just released and is probably the last 3.x, maybe just jump straight to it.

**Comment by kugel-** [comment]
FWIW i have a local branch with scintilla 4, looking good

**Comment by elextr** [comment]
> FWIW i have a local branch with scintilla 4, looking good

Since Scintilla 5 with API changes is likely the next release, it is probably best for Geany itself to skip version 4 and go straight to version 5 since (IIUC) there will be no changes of dependencies or required compiler versions between those two.  And any changes you have made for version 4 will hopefully be useful for Scintilla version 5.

**Comment by kugel-** [comment]
Not sure why we should skip 4 just because 5 comes soon. That doesn't mean we have to make a release containing 4 though, but we can gather experience in preparation for 5.

In my local branch scintilla 4 required no changes to Geany itself so it's a no-brainer.

On the other hand, nobody knows for sure when 5 will be released, so why artificially wait?

**Comment by eht16** [comment]
> On the other hand, nobody knows for sure when 5 will be released, so why artificially wait?

I don't mind if we wait for 5 or just upgrade to 4.
But we should still update Scintilla 3.x in current master and get it released. Afterwards, an upgrade to 4 or 5 is perfectly fine. I just want to get a new release with the current 3.x release for users with old compilers (if there are any at all).

**Comment by kugel-** [comment]
That's fine with me

**Comment by eht16** [comment]
Updated this PR to contain the update to Scintilla 3.21.1.

**Comment by elextr** [comment]
Agree with @eht16 that we should merge this PR, and since I just installed a new Linux version and had to rebuild Geany, I also tested this PR and posted that it WFM, but then noticed 3.21.1 was released.  So I suggest updating this to 3.21.1 if its to be the last "old compiler" release [Note: @eht16 pushed 3.21.1 while I was typing :) ].

There should be a release containing 3.21.1 so any old compiler users left have a defined last version and tarballs etc

@kugel- if Scintilla version 4 actually needs no changes to Geany then I agree that if a PR for it materialises after the release with Scintilla 3.21.1 but before stable Scintilla 5 (Neil has said some early releases of 5 will be unstable IIRC) is available then for sure Scintilla 4 can be included.  I just didn't think it was a good use of our limited resources if Scintilla 4 needed work and then Scintilla 5 needed work.

**Comment by eht16** [comment]
If there are no objections, I will merge on September 26th.

**Pull request merged**
