### PR TITLE
Added small description of G_GNUC_UNUSED macro.

### PR DESCRIPTION
**Pull request by LarsGit223**
Nothing more to say.

### CODE REVIEW

**Comment by elextr** [comment]
LGTM.  Thanks.

**Comment by codebrainz** [comment]
Might be better to link [directly to the macro](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#G-GNUC-UNUSED:CAPS), and also use [external hyperlink target](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#external-hyperlink-targets) to improve the readability, as [explained in the manual](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#embedded-uris-and-aliases):

> **Caution!**
> This construct offers easy authoring and maintenance of hyperlinks at the expense of general readability. Inline URIs, especially long ones, inevitably interrupt the natural flow of text. For documents meant to be read in source form, the use of independent block-level hyperlink targets is **strongly recommended**. The embedded URI construct is most suited to documents intended only to be read in processed form.

I might update if I get bored.

**Comment by elextr** [comment]
Seems to me that `HACKING` is half Rest and half plain text, some time somebody might like to make it entirely one or the other.

**Comment by elextr** [comment]
Or github markdown because everybody knows that, or Asciidoc because its the best (paid political advertisement).

**Comment by codebrainz** [comment]
Not to defend Rst, but hacking.html looks not terrible.

**Pull request merged**
