### PR TITLE
Geany spawn module - initial release

### PR DESCRIPTION
**Pull request by zhekov**
See PR 274 for a discussion

### CODE REVIEW

**Comment by b4n** [comment]
I'll check this out later today, but I just found two leaks in spawn (sorry it's only now…):

```diff
diff --git a/spawn.c b/spawn.c
index d8d2434..031a2fe 100644
--- a/spawn.c
+++ b/spawn.c
@@ -504,8 +504,7 @@ gboolean spawn_async_with_pipes(const gchar *working_directory, const gchar *com
                if (argv)
                        for (argc = 0; argv[argc]; argc++);
 
-               full_argv = g_new(gchar *, cl_argc + argc + 1);
-               memcpy(full_argv, cl_argv, cl_argc * sizeof(gchar *));
+               full_argv = g_renew(gchar *, cl_argv, cl_argc + argc + 1);
                memcpy(full_argv + cl_argc, argv, argc * sizeof(gchar *));
                full_argv[cl_argc + argc] = NULL;
        }
@@ -708,7 +707,10 @@ static void spawn_finalize(SpawnWatcherData *sw)
                sw->exit_cb(sw->pid, sw->exit_status, sw->exit_data);
 
        if (sw->main_loop)
+       {
                g_main_loop_quit(sw->main_loop);
+               g_main_loop_unref(sw->main_loop);
+       }
 
        g_spawn_close_pid(sw->pid);
        g_slice_free(SpawnWatcherData, sw);
```

**Comment by b4n** [comment]
Looks good (but for the 2 aforementioned leaks), and build system changes look good.

Only one detail: we prefer commit messages following the "kernel" form:

> One line summarizing the changes without punctuation
> 
> And as many paragraphs as you like after a blank line, to mention
> anything worth mentioning.  Anything the patch itself doesn't make
> clear, or that is important enough to the reader, or anything worth
> talking about (implementation choices, tests, anything).
> 
> Ideally no line should not be longer than 72 characters.

(e.g. here add a blank line after the summary line)

**Comment by zhekov** [comment]
> - full_argv = g_new(gchar *, cl_argc + argc + 1);
> - memcpy(full_argv, cl_argv, cl_argc * sizeof(gchar *));
> + full_argv = g_renew(gchar *, cl_argv, cl_argc + argc + 1);

This is indeed correct. 
(Unlike realloc(3), g_new() does not state explicitly that the memory will be preserved, but any other implementation simply does not make sense.)

> g_main_loop_quit(sw->main_loop);
> + g_main_loop_unref(sw->main_loop);

The unref must be after g_main_loop_run() instead of g_main_loop_quit(). Actually I had unref there, but it made problems under Win~1 in some earlier versions... which might have been, hopefully, a result of some other bug. Should retest.

> Only one detail: we prefer commit messages following the "kernel" form:
>
>> One line summarizing the changes without punctuation
>
>> And as many paragraphs as you like after a blank line, to mention
>> anything worth mentioning.

OK, I'll have that in mind.

**Comment by b4n** [comment]
> (Unlike realloc(3), g_new() does not state explicitly that the memory will be preserved, but any other implementation simply does not make sense.)

Yeah I noticed (but though like you stated that it wouldn't make any sense for it not to do it).
If you're worried about it, you can instead just `g_free(cl_argv)` (and of course not `g_strfreev()` it as we keep the pointers themselves).

> The unref must be after g_main_loop_run() instead of g_main_loop_quit(). Actually I had unref there, but it made problems under Win~1 in some earlier versions... which might have been, hopefully, a result of some other bug. Should retest.

Is it a problem for the `unref()` to be in the callback?  I didn't see a problem and Valgrind didn't either.
The thing is it can't be done after `run()` returned because `spawn_finalize()` will have freed the `SpawnWatcherData` that contains the pointer to the main loop (probably the reasons of your crashes).
But we could also just have a local pointer to the main loop outside of `SpawnWatcherData` in the caller:

```diff
@@ -904,9 +903,12 @@ gboolean spawn_with_callbacks(const gchar *working_directory, const gchar *comma
 
                if (spawn_flags & SPAWN_SYNC)
                {
-                       sw->main_loop = g_main_loop_new(sw->main_context, FALSE);
+                       GMainLoop *loop;
+
+                       loop = sw->main_loop = g_main_loop_new(sw->main_context, FALSE);
                        g_main_context_unref(sw->main_context);
-                       g_main_loop_run(sw->main_loop);
+                       g_main_loop_run(loop);
+                       g_main_loop_unref(loop);
                }
 
                return TRUE;
```

**Comment by zhekov** [comment]
> If you're worried about it, you can instead just g_free(cl_argv) (and of course not g_strfreev() it as we keep the pointers themselves).

I don't think it's necessary.

> Is it a problem for the unref() to be in the callback? I didn't see a problem and Valgrind didn't either.

It's not a problem. While glib does not say that run() will not access the loop fields after quit(), looking at the source shows that run() refs the loop while using it, and unrefs it after - which is to be expected, actually.

So then, should I revert the initial commit, and do a fixed one, with a long description of what spawn does and why it's required? Mostly the text from the heading of spawn.c.

**Comment by b4n** [comment]
> So then, should I revert the initial commit, and do a fixed one, with a long description of what spawn does and why it's required? Mostly the text from the heading of spawn.c.

You can simply ammend this one instead or undo and redo (GitHub is OK with pushing new versions of commits just fine), but yeah, that'd be ideal :)

**Comment by b4n** [comment]
as said, you could simply have changed your branch and then force-pushed it here ;)

**Comment by zhekov** [comment]
> as said, you could simply have changed your branch and then force-pushed it here ;)

I'm not a master in git(hub)... well, the new PR is #441.

(Of course, I'm not a fan of reverting pushes either, but for *this* exact commit it'll do).

**Pull request closed without merging**
