### PR TITLE
WIP: Add some more Windows dependencies

### LINKED ISSUE #4084: Bug in latest Geany Nightly for Windows
I installed both Geany Nightly and Geany Plugins Nightly.

geany-2.1_git_20241127021509_22a8a1f55_setup.exe

geany-plugins-2.1_git_20241127022112_8d924fd1_setup.exe

Geany will fail to run because missing of these dlls: `libjpeg-8.dll`, `libtiff-6.dll`, `libdeflate.dll`, `libjbig-0.dll`, `libLerc.dll`, `libwebp-7.dll`, and `libsharpyuv-0.dll`.

My educated guess: new dependencies being introduced but the old packaging script is not updated to copy them.

### PR DESCRIPTION
**Pull request by techee**
This is an attempt to fix #4084 by adding some extra dependencies to #4088.

Notably, `libtiff`

https://packages.msys2.org/packages/mingw-w64-x86_64-libtiff

also depends on `jbigkit, libwebp` and `zstd`. In addition, `libwebp`

https://packages.msys2.org/packages/mingw-w64-x86_64-libwebp

has an additional dependency on `giflib`.

I'll try the resulting artifact and update this PR if any extra dependencies are still needed.

### CODE REVIEW

**Comment by techee** [comment]
No more dependency problems but I still get

Screenshot 2024-12-02 at 23 33 36

From some stackoverflow pages, it seems like some libstdc++ symbol that is missing. But libstdc++ is installed.

**Comment by techee** [comment]
@eht16 Just wondering, doesn't the Windows CI get libstdc++ from somewhere else? In the image below, you can see libstdc++ as installed from the artifact of this PR and below is what is inside msys.

Screenshot 2024-12-04 at 14 02 43

They have different sizes. When I try to replace the version in Program Files with the msys one, I get

Screenshot 2024-12-04 at 14 05 55

To me it seems that msys is built against one version of libstdc++ and Geany uses some other from somewhere else.

**Comment by techee** [comment]
> To me it seems that msys is built against one version of libstdc++ and Geany uses some other from somewhere else.

Exactly this happens because of

https://github.com/geany/geany/pull/4094/commits/110c7b492e8595851131eeb5c381418799e8ae34

I think it would be best if Geany was compiled against the msys version of libstdc++ if possible so both the dependencies and geany are linked against the same library.

**Comment by techee** [comment]
OK, one thing that works is to build libLerc

https://github.com/Esri/lerc/tree/master

 (which is the one throwing the error) manually and link the official msys libstdc++ statically to it and ship this library in the Geany installer instead of the msys one. I tried this manually without modifying the build scripts and Geany launches. So if there's not a better way, this could be one way forward.

**Comment by techee** [comment]
But I see red squares instead of some UI elements - this used to happen because of missing librsvg because these are SVG images but librsvg seems to be present.

Screenshot 2024-12-07 at 11 32 03

**Comment by techee** [comment]
There's this error message when bundling - possibly just missing some more dependencies for librsvg:
```
002a:err:module:import_dll Library bcryptprimitives.dll (which is needed by L"Z:\\build\\gtk-bundle\\bin\\librsvg-2-2.dll") not found
002a:err:module:import_dll Library librsvg-2-2.dll (which is needed by L"Z:\\build\\gtk-bundle\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders\\pixbufloader_svg.dll") not found
002a:err:module:import_dll Library bcryptprimitives.dll (which is needed by L"Z:\\build\\gtk-bundle\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders\\pixbufloader_svg.dll") not found
g_module_open() failed for Z:\build\gtk-bundle\lib\gdk-pixbuf-2.0\2.10.0\loaders\pixbufloader_svg.dll: 'Z:\build\gtk-bundle\lib\gdk-pixbuf-2.0\2.10.0\loaders\pixbufloader_svg.dll': Module not found.
```

**Comment by eht16** [comment]
> OK, one thing that works is to build libLerc
> 
> https://github.com/Esri/lerc/tree/master
> 
> (which is the one throwing the error) manually and link the official msys libstdc++ statically to it and ship this library in the Geany installer instead of the msys one. I tried this manually without modifying the build scripts and Geany launches. So if there's not a better way, this could be one way forward.

Just to clarify my confusion: using the original libstdc++ (https://github.com/geany/geany/commit/110c7b492e8595851131eeb5c381418799e8ae34) the Lerc error still persisted?
Even if and the rest still works, I'm happy to remove this hack. Maybe the toolchain changed since I added it a year ago.

I'm wondering why I don't see these errors, I think the only difference is that I'm on oldish Windows 7.

Regarding librsvg: I see the red boxes as well, not sure why. librsvg is included and at least its direct dependencies as well. I'll try to have a deeper look but this might take some days.

**Comment by techee** [comment]
> Just to clarify my confusion: using the original libstdc++ (https://github.com/geany/geany/commit/110c7b492e8595851131eeb5c381418799e8ae34) the Lerc error still persisted?

No, it was gone, but instead I got the error in libgeany as described in https://github.com/geany/geany/pull/4094#issuecomment-2517303194

> Even if and the rest still works, I'm happy to remove this hack. Maybe the toolchain changed since I added it a year ago.

I'm afraid that depending on which libstdc++ version you use, you either get the libgeany error or the libLerc error.

So what I did is that I compiled libLerc myself, statically linking the msys libstdc++ with which it works, so even when Geany is distributed with the other libstdc++, libLerc doesn't need it at the runtime. It would be possible to perform this as part of the CI build if there's no other way to get Geany running (it's just a few files to compile so not much more extra time, it just needs `cmake` and for static linking I used something like ` CXXFLAGS="-static-libstdc++" cmake ..`).

Just wondering, what is this "posix" libstdc++ version? Is it something that is provided officially by the msys project? If so, we could maybe report the problem there. I also noticed that the libLerc msys binary

https://packages.msys2.org/packages/mingw-w64-x86_64-lerc

was built more than 2 years ago and maybe rebuilding it against the current msys libstdc++ will fix the problem.

> I'm wondering why I don't see these errors, I think the only difference is that I'm on oldish Windows 7.

No idea :-/

**Comment by techee** [comment]
@eht16 I'm closing this PR in favor of #4088 as I don't plan to work on this myself (I just needed some working build so I could test the LSP plugin). You can grab the extra dependencies from the patch from this PR.

**Pull request closed without merging**
