### PR TITLE
Force disk status document check in some specific cases

### PR DESCRIPTION
**Pull request by techee**
The disk status change check behaves sometimes a bit magically in Geany and it takes some time for Geany to realize the document has changed. Of course there are performance reasons for it (it's probably not a good idea to do the full check for every character written) but there are several cases where we can do a force check and show the notification immediately:

1. When switching tabs - the current code doesn't do a force-check but IMO it's a good idea to perform it to make sure the document is up-to-date (we do a force-check for the final document when switching documents using Ctrl+Tab and this is a similar case).

   Moreover, the part doing the check on idle is obsoleted by

   https://github.com/geany/geany/commit/5cc8a96d440274c15f50228ee55461fb557cee3e

   and can be removed.

   (now looking at the linked patch maybe it would be possible to remove the switch_in_progress check from document_check_disk_status() and rather put it into on_notebook1_switch_page_after(). Then on_notebook1_switch_page_after() could be moved to notebook.c where it would have direct access to the switch_in_progress variable and we could eliminate the accessor method. Let me know if you prefer this way.)

2. When Geany main window becomes active - the most common case is that the document is modified by the user from the outside by editing it in a different editor or running some script in the terminal. This was already done for OS X and the osx-specific part can be removed now.

3. After building/running because the open document can be some generated output resulting from build/run.

It would be nice to do something similar for VTE too but I don't see a way how to tell if the executed command finished (doing it when user presses enter is too early because the command can still be running).

### CODE REVIEW

**Comment by elextr** [comment]
I like the ideas, checking the final destination tab when its displayed is a good idea, that way workflows like:

1. edit source file
2. generate output file
3. switch to output file tab

will work.  The other two items add belts and braces to that.  

Now if only the output file tab could be set to autoreload, but thats another PR.

About VTE, you are right, the interface to it is terminally (tish boom :) broken because Geany can't tell if there is still something running there, so probably less done there the better.

**Comment by techee** [comment]
I resolved merge conflicts and added a patch to perform the check also on scintilla editor focus in - this should help the VTE modification case but I can imagine also plugins if they do some modification from other widget (e.g. if we added some file operations like deletion, rename to the file browser plugin). For this reason it's better to use the focus-in of the editor rather than focus-out of VTE.

**Comment by techee** [comment]
With the recent discussion about remote file editing I realized some of the proposed checks might be too aggressive and could cause unnecessary delays. I kept just the one checking the switched tab's document and checking current document when Geany made active.

**Comment by techee** [comment]
Repushed with the re-added check inside the file open.

**Pull request merged**
