### PR TITLE
autotools: Avoid building non-shared versions of the object files

### PR DESCRIPTION
**Pull request by b4n**
libtool apparently builds every object twice by default when shared and
static objects need to be build differently.  As we never use the
statically linked objects, avoid building them at all.

Re #468 @techee @elextr does this fix it for you?  seems to do for me.

### CODE REVIEW

**Comment by techee** [comment]
Good catch! Yes, this fixes the issue on linux for me.

However, on OS X it just improves the performance (from 50s to 37s) but originally the build took just 16s. But this might also be libtool using some of the Apple's outdated (possibly slow) commandline tools and because I use waf for development, I don't care much. So consider this issue fixed.

**Comment by b4n** [comment]
@techee thank @elextr for the catch, I merely tried to fix what he found :)

Though… `50 - 37 = 13` if I'm not mistaken, which would mean only 13s seconds are saved not building everything twice?  Which would suggest the actual compilation is now around 13s, and we have `37 - 13 = 24`s lost in doing nothing?  (ok, this is biased as there is at least the link step missing, but it shouldn't be much more than about 1s at worse)

Another possibility for some slowness would be spawning as many libtool scripts wrappers as there are objects to build, as I could imagine running a 11KLOC shell script in addition to everything else could cause some visible overhead.

Last thing, how are you measuring?  because by default autotools will try to build documentation (Doxygen, rst2html and rst2pdf if you have them -- and some are crazy slow), while I think Waf only does rst2html.

**Comment by techee** [comment]
@b4n If you consider the original build time was 15s (including linking, documentation build, etc.), 13s for the compilation itself seems right.

I tried to run system trace to see better what happens and per a single file compiled I get something like this (note that this is very rough, it really depends on what file is compiled, whether it's C or C++, etc. - these numbers are for the beginning of the compilation which is ctags and which compile relatively fast):

sh: 135ms
perl: 90ms
clang: 70ms

So most time is now spent by sh and perl. I tried the pre-libgeany state and the amount of time spent by sh/perl is marginal (3ms for sh and no perl at all). So it really looks libtool does something which is cheap on linux but expensive on OS X.

**Comment by codebrainz** [comment]
LGTM.

This is the exact patch I was gonna make last night, but you beat me to it :) IMO, it's a bit sneaky of libtool to do a whole compilation stage of many files, piping it to `/dev/null` so nobody knows what the heck is going on. If it had shown the redundant compilations in the build output, this never would've slipped by even the first linkage-cleanup PR, let alone both.

**Comment by b4n** [comment]
Just one thing that come to mind afterward: maybe we want to switch from `disable-static` to `disable-shared` when building with plugin support disabled (`--disable-plugins`).  But I guess nobody does that and can then use the appropriate configure flags to do it, or ask us when they come into it :)

**Pull request merged**
