### PR TITLE
Changed pt_BR.po

### PR DESCRIPTION
**Pull request by wsalmeida**
Hi, I made some changes to the Brazilian Portuguese translation file.

### CODE REVIEW

**Comment by elextr** [comment]
Hmmm, #2881 and #2880 both changing the same translation, @wsalmeida and @math-ac to avoid duelling translations, could you guys co-ordinate amongst yourselves?

**Comment by wsalmeida** [comment]
> Hmmm, [# 2881](https://github.com/geany/geany/pull/2881) e [# 2880](https://github.com/geany/geany/pull/2880) mudando a mesma tradução, @wsalmeida e @math-ac para evitar duelos de traduções, vocês poderiam se coordenar?

Sorry, what would a translation duel be?

**Comment by elextr** [comment]
"Duelling translations" - Where two people make differing changes to the same translation file such that merging them both makes the final translation incorrect.  :grin:

**Comment by math-ac** [comment]
What would be the best way to deal with this @elextr ? To be quite honest, my pull request have some minor adjustments in comparison to the one from @wsalmeida .

**Comment by wsalmeida** [comment]
> "Duelo de traduções" - quando duas pessoas fazem alterações diferentes no mesmo arquivo de tradução, de modo que a fusão de ambas torna a tradução final incorreta.
Não me atentei ao detalhe que havia outro fazendo as mesmas alterações se vocês estiverem de acordo posso tentar reverter removendo o pull request já que @math-ac iniciou primeiro.

**Comment by elextr** [comment]
What triggered me to point it out is that both of you changed `desktop.in.h:3`, but in different ways.  Both changes may be valid, I don't know Portuguese so I can't say.  There may be other places as well, I stopped at that point.  

If the changes by @wsalmeida are larger probably best if you agree what should happen on his Github fork and then update this PR and withdraw #2880.

**Comment by math-ac** [comment]
That makes sense, i will withdraw my pr and help @wsalmeida with the translation afterwards.

**Comment by elextr** [comment]
Note that if you discuss it on someones personal Github fork you can do it in any language, but please keep issues here in English.

**Comment by wsalmeida** [comment]
> Faz sentido, retirarei meu pr e ajudarei @wsalmeida com a tradução depois.

I will keep the changes made to the file as they are and I will be very grateful if there are revisions and I am open to suggestions.

**Pull request merged**
