### PR TITLE
Keywords

### PR DESCRIPTION
**Pull request by Yanpas**
Added keywords for c#(https://msdn.microsoft.com/en-us/library/x53a06bb.aspx) and cmake( deprecated commands in the end of list). PR consists of 2 commits, but github allows to squash commits

### CODE REVIEW

**Comment by elextr** [comment]
Hmmm, this seems to have fallen through the cracks.  I note you said you ordered cmake to put deprecated commands at the end.  There is some sense in that,  however all other filetypes files are alphabetical and since the whole lot has to be a loooooong line, its too easy to miss things at the end, since they are expected to be alphabetical locations.  So please keep alphabetical ordering.

**Comment by Yanpas** [comment]
updated

**Comment by Yanpas** [comment]
ping

**Comment by eht16** [comment]
In an ideal world, this could have been two seperate PRs for C# and CMake.
@Yanpas it'd be fine if you could add the source of the keywords as comment above the respective setting in the config. That would help to remember where the keywords were taken from.
Thanks.

Apart from that, I think this is fine to merge.

**Comment by Yanpas** [comment]
Here are C# keywords: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
(Note that C# 7 was released recently)

CMake keywords may be obtained via executing `cmake --help-command-list`

**Comment by elextr** [comment]
@Yanpas could you add those as comments in the config files as suggested by @eht16, thanks.

**Comment by eht16** [comment]
LGTM, @elextr if you agree, let's merge.

**Comment by elextr** [comment]
@eht16 consider the merge as agreement ;-)

Ran out of time to try to cleanly separate the two languages to separate commits.

@Yanpas have to emphasise that next time make different languages different pull requests, if one language needs to be reverted both will be.

**Comment by Yanpas** [comment]
Ok :)

**Pull request merged**
