### PR TITLE
Sync ctags parsers with small changes with Geany

### PR DESCRIPTION
**Pull request by techee**
This pull request removes the geany_ prefix from parsers we can sync easily with ctags and which contain only small changes and copies over these parsers from uctags (the versions from tag p5.9.20211031.0 like in #2984). More details can be found in the commit messages.

I plan to do the same with other parsers too, this pull request just includes those that didn't contain many changes to make this pull request easy to review. This pull request compiles fine independently of whether #2984 is applied or not.

### CODE REVIEW

**Comment by kugel-** [comment]
I haven't looked at update-ctags.py in detail but I assume it attempts to preserve our small changes?

**Comment by techee** [comment]
> I haven't looked at update-ctags.py in detail but I assume it attempts to preserve our small changes?

The only small change in ctags `main` is what `ctags_changes.patch` does - the script just copies over the files from ctags main and applies this patch.

Another story are the parsers where changes are rather big apart from parsers in this pull request. The script ignores parsers starting with `geany_` (those will have to be maintained by us) and only replaces parsers without this prefix. This is something this pull request does too - removes the `geany_` prefix so the next time we run `update-ctags.py`, the upstream versions of these parsers will be copied automatically and we won't have to worry about them any more.

**Comment by elextr** [comment]
Agree with @techee the aim is to be able to simply update changes from ctags automatically.  For those parsers where we have a worthwhile change we should push it upstream, thats a nice thing to do anyway, and it then allows us to import the parsers automatically.

`c.c` and others that have big changes are more or a problem and the `geany_` prefix will protect them until such time as they can be synchronised (or replaced with new upstream in the case of C/C++).

**Comment by elextr** [comment]
See https://github.com/geany/geany/pull/2991#issuecomment-980814999

**Comment by techee** [comment]
Just to clarify what I did in the last few commits - first I got a bit confused about the reason why the various text file format parsers are mentioned in `tm_parser_context_separator()` even though they don't report nested scope and the context separator never appears in the context. The only reason for them to be here is to report some invalid context separator so `tm_parser_context_separator()` doesn't report false positive scope separators (e.g. imagine `1.1 My subsection` where `.` would be detected as a scope separator).

The situation with these languages is - txt2tags now reports full context with `""` as its context separator. Asciidoc, conf, rest don't use context separator and use `\x3` as the improbable-to-appear-in-text character.

I went through all the languages in this pull request and everything seems to be good from my perspective so as far as I can tell, this pull request is ready to be merged.

**Comment by elextr** [comment]
> this pull request is ready to be merged.

Done!!!

**Pull request merged**
