### PR TITLE
Update Pascal filedef and extension mappings

### PR DESCRIPTION
**Pull request by rdipardo**
#### filetypes.pascal

  - add line comments

  - pair the 'fpc' compile command with another common Free Pascal utility [^1], 'instantfpc', to build and run the current file in a single step

  #### filetype_extensions.conf

  - add Lazarus project files (*.lpr)

[^1]: https://wiki.freepascal.org/InstantFPC

### CODE REVIEW

**Comment by elextr** [comment]
If the compile command is generating an executable there is no way of running it, instead of removing the run command add a second one. See [this](https://wiki.geany.org/howtos/configurebuildmenu).

**Comment by rdipardo** [comment]
Check 9ca281b02 to see if I have the right idea.

Since Pascal compilers are single-pass, the nearest equivalent to a strict compile command seems to be [the option to skip the linker](https://www.freepascal.org/docs-html/user/userap1.html) (`-s`).

A new side-effect will be the generation of a linker script and a `link<PID>.res` artifact, in additional to objects, if the target is a program or library. A `unit` will only generate an object as before, no matter if "Compile" or "Build" is run.

**Comment by elextr** [comment]
LGBI and makes sense given the pecularities of the Pascal compilers.

And finally another filetype file converted to the "new" build, its only been 13 years, maybe I shouldn't have made backward compatibility so good ;-)

**Comment by rdipardo** [comment]
> Finally another filetype file converted to the "new" build, its only been 13 years

Mass migrations to a new spec are seldom worth the effort, and there's always somebody who prefers the old way.

As for the long neglect of Pascal, it's no surprise when the Lazarus IDE has been free and cross-platform for as long as Geany's been around, and it [still supports GTK2](https://wiki.lazarus.freepascal.org/Roadmap#General_status_of_LCL_interfaces), even if that's only thanks to inertia.

**Comment by elextr** [comment]
Couldn't be bothered with inertia. ;-)

**Comment by elextr** [comment]
Thanks, although I don't have pascal to test it, since nobody objected, so I overcame the inertia and merged ;-)

**Pull request merged**
