### PR TITLE
Add `.mjs` extension for JavaScript

### PR DESCRIPTION
**Pull request by TheDcoder**
The `.mjs` extension is used by Node.js and others to denote JavaScript module files, unlike normal `.js` files these files are treated like ES6 modules by default.

### CODE REVIEW

**Comment by elextr** [comment]
Looks ok to me.

**Comment by TheDcoder** [comment]
@elextr Great, when can we merge this?

**Comment by elextr** [comment]
Nobody is full time on this project, its always polite to leave some time for objections.

**Comment by elextr** [comment]
@creatxrgithub that is not relevant to this PR, please do not hijack existing issues or pull requests, create your own.

**Review by b4n — APPROVED** [review]
LGTM, works and seems a commonly accepted extension

**Comment by b4n** [comment]
@elextr is right that your request is fairly irrelevant to the support of `.mjs` extensions by default, and that you should open your own question on the subject.  However, it's trivial enough to warrant answering here *as well*: you can [configure this](https://geany.org/manual/#filetype-extensions) yourself.

**Pull request merged**
