### PR TITLE
autotools: Detect GTK version to use automatically

### PR DESCRIPTION
**Pull request by b4n**
This makes GTK3 version first class citizen (well, almost, it still defaults to gtk2 when available).

Related to #452.

Yes, the tests are a bit subtle, but we want to respect the `--enable-gtk3` value, but yet default to gtk2 if nothing is passed and it's found, but also if nothing is passed and no GTK version is found.
- [x] Autotools
- [x] Waf

### CODE REVIEW

**Comment by kugel-** [comment]
I guess this won't land 1.25 anymore?

**Comment by b4n** [comment]
It could, it doesn't break Waf, it's just missing from it.

**Comment by kugel-** [comment]
What's the official guideline on the build systems anyway? Is everybody really expected to implement things twice (or thrice, makefile.win32) before anything can be merged?

**Comment by b4n** [comment]
Basically, yes.  Though actually I think plugins don't work with GTK3 and Waf, so…
Anyway, IMO so long as it doesn't break something adding a new feature to one of the buildsys is fine.

**Comment by kugel-** [comment]
This PR would be a good first step, so that can perhaps make GTK3 default by 1.26 or 1.27

**Comment by codebrainz** [comment]
>  Is everybody really expected to implement things twice (or thrice, makefile.win32)

Sort of 5 times, if you count keeping Geany-Plugins' two build systems in sync with Geany's :)

On this PR, we should be careful about changing build system stuff last minute. It could affect many users depending on how it ends up packaged and might cause grief with the Geany-Plugins build system and with plugins not all supporting GTK3 yet.

IMO, we should not mess with this until after the release, and then at that point just actually change to true first class GTK+ 3 and make GTK+2 support optional by some `--enable-legacy-gtk` or by just removing support altogether or something.

**Comment by eht16** [comment]
I agree with @codebrainz regarding not changing build system stuff so close to the release.
I can do the Waf part after the release.

**Comment by kugel-** [comment]
@eht16 did you progress on this?

**Comment by eht16** [comment]
Not yet. Thanks for the reminder. Following the first implementation attempt:
- use GTK3 if --enable-gtk3 is given and fail hard if GTK3 is not available
- use GTK2 if available
- use GTK3 if available but GTK2 is not available

```diff
From 52c5cf8b494075e7ddce0d315e056001e91e2679 Mon Sep 17 00:00:00 2001
From: Froscon 2015 <demo@endor.l8failed.net>
Date: Sat, 22 Aug 2015 17:22:22 +0200
Subject: [PATCH] Waf: Detect GTK version to use automatically

---
 wscript | 36 ++++++++++++++++++++++++++++++------
 1 file changed, 30 insertions(+), 6 deletions(-)

diff --git a/wscript b/wscript
index b66af42..b1dd0ec 100644
--- a/wscript
+++ b/wscript
@@ -45,7 +45,7 @@ import tempfile
 from waflib import Logs, Options, Scripting, Utils
 from waflib.Build import BuildContext
 from waflib.Configure import ConfigurationContext
-from waflib.Errors import WafError
+from waflib.Errors import ConfigurationError, WafError
 from waflib.TaskGen import feature, before_method
 from waflib.Tools.compiler_c import c_compiler
 from waflib.Tools.compiler_cxx import cxx_compiler
@@ -222,10 +222,7 @@ def configure(conf):
     _load_intltool_if_available(conf)
 
     # GTK / GIO version check
-    gtk_package_name = 'gtk+-3.0' if conf.options.use_gtk3 else 'gtk+-2.0'
-    minimum_gtk_version = MINIMUM_GTK3_VERSION if conf.options.use_gtk3 else MINIMUM_GTK_VERSION
-    conf.check_cfg(package=gtk_package_name, atleast_version=minimum_gtk_version, uselib_store='GTK',
-        mandatory=True, args='--cflags --libs')
+    gtk_package_name, minimum_gtk_version = _check_for_gtk2_and_gtk3(conf)
     conf.check_cfg(package='glib-2.0', atleast_version=MINIMUM_GLIB_VERSION, uselib_store='GLIB',
         mandatory=True, args='--cflags --libs')
     conf.check_cfg(package='gmodule-2.0', uselib_store='GMODULE',
@@ -350,6 +347,33 @@ but you then may not have a local copy of the HTML manual.'''
         conf.msg('Compiling Git revision', revision)
 
 
+def _check_for_gtk2_and_gtk3(conf):
+    gtk_package_name = 'gtk+-2.0'
+    minimum_gtk_version = MINIMUM_GTK_VERSION
+    if not conf.options.use_gtk3:
+        try:
+            _check_for_gtk_package(conf, gtk_package_name, minimum_gtk_version)
+        except ConfigurationError:
+            pass  # fall through to check for GTK3 below
+        else:
+            return gtk_package_name, minimum_gtk_version
+        
+    # fallback to GTK3
+    gtk_package_name = 'gtk+-3.0'
+    minimum_gtk_version = MINIMUM_GTK3_VERSION
+    _check_for_gtk_package(conf, gtk_package_name, minimum_gtk_version)
+    return gtk_package_name, minimum_gtk_version
+          
+
+def _check_for_gtk_package(conf, gtk_package_name, minimum_gtk_version):
+    conf.check_cfg(
+        package=gtk_package_name, 
+        atleast_version=minimum_gtk_version, 
+        uselib_store='GTK',
+        mandatory=True, 
+        args='--cflags --libs')
+    
+
 def options(opt):
     # Disable MSVC detection on win32: building Geany with MSVC is currently not supported
     # If anyone wants to add support for building with MSVC, this hack should be removed.
@@ -373,7 +397,7 @@ def options(opt):
         help='compile without support for an embedded virtual terminal [[default: No]',
         dest='no_vte')
     opt.add_option('--enable-gtk3', action='store_true', default=False,
-        help='compile with GTK3 support (experimental) [[default: No]',
+        help='compile against GTK3 [[default: No]',
         dest='use_gtk3')
     opt.add_option('--enable-mac-integration', action='store_true', default=False,
         help='use gtk-mac-integration to enable improved OS X integration [[default: No]',
-- 
2.5.0
```

**Comment by eht16** [comment]
P.S.: please ignore the From: address in the above patch. Right now I'm at a conference and used a demonstration account to write the patch :).

**Comment by kugel-** [comment]
Didn't we plan to consider dropping waf fir post-1.25?

Am 22. August 2015 17:24:32 MESZ, schrieb "Enrico Tröger" <notifications@github.com>:

**Comment by eht16** [comment]
I'm confused, didn't you ask for progress just before?
Anyway, if we want, we can drop Waf. My only concern are the Windows builds but if MSYS2 works properly and can be used to produce releases, it's OK by me.

**Comment by kugel-** [comment]
Am 23. August 2015 09:37:20 MESZ, schrieb "Enrico Tröger" <notifications@github.com>:
>I'm confused, didn't you ask for progress just before?
>Anyway, if we want, we can drop Waf. My only concern are the Windows
>builds but if MSYS2 works properly and can be used to produce releases,
>it's OK by me.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geany/geany/pull/524#issuecomment-133797515

Yes, I didn't remember that when I asked, sorry for the confusion.

IMO msys2 is fine for release builds, both gtk 2&3. I just need to finish the script for scraping package dependencies, I was almost done

**Comment by eht16** [comment]
As discussed in #679, we will keep Waf support for 1.26 and so with my patch above, this should be ready to merge?

**Comment by b4n** [comment]
@eht16 I added your commit that looks sensible, thanks.

Though, we're again close to a release (my bad) and I spotted a refresh issue on the current tab label color on GTK3, which is probably a GTK3 bug, so I'm a little more reluctant to enable GTK3 by default… err.  Similarly, @elextr seems to have issue with certain corner cases on certain GTK3 versions as in https://github.com/geany/geany/issues/702#issuecomment-150986086 (although admittedly it was also broken on GTK2)

**Comment by kugel-** [comment]
The default is still gtk2 isn't it? I don't understand why gtk3 issues hold this back (I also see the tab refresh issue, but only after upgrading to gtk 3.18)

**Comment by b4n** [comment]
@kugel- well, this PR selects GTK3 automatically if GTK2 isn't found, which effectively means that it *can* be selected by default without explicit choice from the user.  So issues with it worries me a little more than if it's an explicit, manual choice.

**Pull request closed without merging**
