### PR TITLE
autotools: use autoreconf and gettext

### PR DESCRIPTION
**Pull request by kugel-**
autoreconf is much more convinient over calling the autotools programs
individually.

Standard gettext should be used over glib's glue these days.
AM_GLIB_GNU_GETTEXT and glib-gettextize are deprecrecated. This helps
the meson build as well as working with intltool is harder over there.

Inspired by:
https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration
https://gitlab.gnome.org/GNOME/gedit/-/commit/0b4d03017fe7ba2e5c7d33d364de49c611a6e6e9

### CODE REVIEW

**Comment by kugel-** [comment]
@b4n @eht16 any opinion?

**Comment by eht16** [comment]
LGTM now!

**Comment by kugel-** [comment]
@eht16 any idea about the mingw build failure? I cannot reproduce it on my system. `./scripts/cross-build-mingw.sh` runs fine for me.

**Comment by eht16** [comment]
> @eht16 any idea about the mingw build failure? I cannot reproduce it on my system. `./scripts/cross-build-mingw.sh` runs fine for me.

According to https://www.linuxquestions.org/questions/slackware-14/undefined-reference-to-libiconv-341284/#post3353338 (just searched for the error as it was also not obvious to me), adding `-liconv` to CFLAGS fixes the error. However, I don't know what's going on behind the scenes and why it works without for the Linux builds.

Another question: is it on purpose that all the `po/*.po` files are updated?

**Comment by eht16** [comment]
Ah, and to reproduce start a `docker:18.04` Docker image and replay the build steps from the CI script.

**Comment by kugel-** [comment]
> Another question: is it on purpose that all the po/*.po files are updated?

No. I reverted that part.

**Comment by kugel-** [comment]
Merging since @eht16 approved it earlier and it blocks the meson PR.

**Pull request merged**
