### PR TITLE
License Templates

### PR DESCRIPTION
**Pull request by DevynCJohnson**
[ci skip]

* Added AGPLv2 (GNU Affero General Public License v2)
* Added AGPLv3 (GNU Affero General Public License v3)
* Renamed ./data/templates/gpl to ./data/templates/gpl2
    * This makes it clear that the license is version 2
* Added GPLv3 (GNU General Public License v3)
    * Many developers prefer GPLv3 over GPLv2
* Added LGPLv2 license (GNU Lesser General Public License v2)
* Added LGPLv3 license (GNU Lesser General Public License v3)
    * The LGPL licenses are commonly used in libraries and other code
* Added BSD 2-Clause License
* Renamed ./data/templates/bsd to ./data/templates/bsd-3-clause (BSD 3-Clause License)
    * This makes it clear that the license is 3-Clause
* Updated ./data/templates/bsd-3-clause (BSD 3-Clause License)
    * Ensured that this license matches the official BSD 3-Clause License
* Variety is the spice of life; Some other commonly used licenses should be added
    * Added Apache License v2.0
    * Added cc0 (CC0 1.0 Universal (CC0 1.0))
    * Added the MIT License (MIT)
    * Added MPLv2 (Mozilla Public License v2.0)
    * Added zib/libpng License
    * I plan to add more licenses in the future (perhaps WTFPL)

The functions "editor_insert_snippet" and "editor_find_snippet" in ./src/editor.c dynamically find and add license templates to the "Edit > Insert Comments" sub-menu during compilation.

### CODE REVIEW

**Comment by elextr** [comment]
Nice try to sneak #305 in again, but ... :)

1) these break the build
2) templates are for creating a file, that is they are language specific and the license text is in a comment, so creating a file from just the license text isn't the way to go either.

**Comment by DevynCJohnson** [comment]
@elextr , you remembered me (^u^).

Why do these break the build? Why is it that the "gpl" and "bsd" license in the mainstream Geany release not break the build? What code could I (or someone else) add or fix to make this work?

These additional templates (like the "gpl" and "bsd" licenses) can be inserted in a block-comment of the code the developer has open. For instance, in C, I could uses C's multi-line comments and then insert a license template between the opening and closing comment-syntax. Thus, these license templates are "universal", just like the "gpl" and "bsd" licenses in the "Edit > Insert Comments" sub-menu.

**Comment by DevynCJohnson** [comment]
I explained this license feature in more detail on the ML. However, I would love to help fix this "broken build" issue.

**Comment by codebrainz** [comment]
@DevynCJohnson at the bottom of pull requests it shows whether it would break the build system on the build server. There's a "Details" link that shows the results. In this case, the relevant error is around here:

https://travis-ci.org/geany/geany/jobs/90350084#L1041

Probably the new files weren't added to the relevant Makefile.am file properly.

**Comment by codebrainz** [comment]
For maximum likelihood of getting this PR merged quickly, your best bet is to reproduce the kind of changes in [this Gist](https://gist.github.com/codebrainz/2353163) for the current Geany master branch and with your additional licenses. (Note: I manually edited the Gist patch, compared to the version I linked on the mailing list, to remove all the noise in the GUI XML builder file).

Of course it would be better to make the licenses more easily user-extensible, but unless you want to re-do the related code in Geany, just hard-coding more licenses would probably be accepted.

**Comment by codebrainz** [comment]
Regarding:

>  Why is it that the "gpl" and "bsd" license in the mainstream Geany release not break the build?

I think it's because you renamed the files but did not update the build system to reflect the new names.

**Comment by elextr** [comment]
@DevynCJohnson the big red message below "all checks have failed" is a giveaway :)

As @codebrainz said, just adding the template to the directory won't do anything, the associated menu items need to be created.

The template area of Geany has grown rather than being designed, so maybe its confusing.  Let me summarise.

There are two sorts of [templates](http://www.geany.org/manual/current/index.html#templates), those that paste into comments using `Menu->Edit->Insert Comments` and those that are a template for creating new files (usually called file templates).

The comment templates include a couple of licenses and are "hard coded" because they need menu entries to be added inside `Menu->Edit->Insert Comments` to copy and manipulate the appropriate template file in `data/templates`.  Just adding files to `data/templates` will not do anything unless the menu items are added.  The user can customise the template file in their config, but cannot add new ones.  This is not very extendible, and as @codebrainz said would be better if it picked up files and added them to the menu automagically like file templates below (pull requests are welcome).

The file templates are used to create new files and show in the `Menu->File->New (with template)` list, and in this case the elements in the list are the files in `data/templates/files`.  Adding new files will automatically show up in the list (Geany restart may be needed). The user can customise the template file in their user config and can add new ones.  The filetype and extension of the newly created file is taken from the extension of the template file.

So it doesn't make adding new licenses easy the way it works at the moment.  Which is why the list is so limited.  The best solution is to make the `Insert Comment` list extensible and allow those to be included in the file templates, just needs "somebody" to do it.

**Comment by DevynCJohnson** [comment]
@codebrainz , thanks! I was not aware that I had to add license templates to Makefile.am. I will try that.

**Comment by DevynCJohnson** [comment]
I will make a new pull-request that has the new modifications.

**Comment by codebrainz** [comment]
New PR #752

**Pull request closed without merging**
