### PR TITLE
Update Scintilla to version 3.10.2

### LINKED ISSUE #971: Markdown syntax: bad link recognition after pressing return
This is probably a bug in scintilla / ctags / whatever.  Please forward appropriately.

Save the following as a normal file:

```
Hello [lovely
world](http://example.com/with/very/long/URL/that/cant/be/wrapped/reasonably.php)

Asdf
```

Note that the line breaks are important.  `Asdf` should be on the forth line.

Open this file in geany, move the cursor to the end of the line (right after the closing parenthesis that closes the link) and press 'return'.  ('Enter' has the same effect.)

Expected behavior: a new line appears. Duh. (Nothing else should change.)

Actual behavior: a new line appears … and everything afterwards is also part of that link. At least that's what the syntax highlighting suddenly indicates. The whole rest of the file is affected; it doesn't reset at paragraph boundaries or any other sane "well no kind of formatting can cross this point anyway" border.

Manual workaround: find the "link" that caused all this, insert a character before it and delete it again. This seems to cause re-parsing of the link, and this time it works.

```
$ geany --version
geany 1.27 (git >= d1fcd9f) (kompiliert am 2016-01-03 mit GTK 2.24.29, GLib 2.46.2)
```

### LINKED ISSUE #1947: Markdown: Bad recognition of link end for some unicode chars
Minimal reproducing example:

    This is displayed as normal text.
    [ク](https://google.com)
    This isn't.!

Steps to reproduce: Save it as `foo.md`, and open it in geany.  Then delete the last exclamation mark to get around #971.

Expected behavior: Both normal text lines are displayed using the "normal text" style.

Actual behavior: The last line's style indicates that it is somehow still part of the link.  Not visible in the short example: This affects the entire rest of the document.

Screenshot:
Screenshot of the faulty behavior

Note that even before this "remove the last exclamation mark" step, one can see faulty behavior.  Specifically, the `T` is styled wrong.

### PR DESCRIPTION
**Pull request by b4n**
Closes #971, closes #1947.

### CODE REVIEW

**Comment by b4n** [comment]
@BenWiederhake could you test this and see if it indeed fixes the 2 markdown issues mentioned above?

**Comment by elextr** [comment]
@b4n, That was fast, well done. WFM so far.

Hope it didn't stop you from reviewing @techee's ctags PR :grin:

**Comment by BenWiederhake** [comment]
## Before

geany 1.33 (built on 2018-04-16 with GTK 3.22.29, GLib 2.56.1)
#971: Yes, can reproduce it, but file must be recognized as Markdown (e.g., save as "blahblah.md")
#1947: Yes, can reproduce it, exactly as described.

## After

(I checked that at least "scintilla/include/Platform.h" contains the changes.
`cat scintilla/version.txt` says 3102.
The Debian patches seem mostly cosmetic for my purpose.
Building with "auto" fails, wants gtk2-dev libs, complains about symbols and version mixing.
`./configure --disable-html-docs --enable-gtk3 && make -j4 && sudo make install`
Success.)
geany 1.35 (git >= ecf98b1e) (built on 2019-01-13 with GTK 3.24.2, GLib 2.58.2)
#971: No, can't reproduce it: Correct (fixed) initial state, and correct (fixed) behavior when pressing enter.  *Looks fixed to me.*
#1947: No, can't reproduce it: Correct (fixed) initial state, and correct (fixed) behavior when deleting a character.  *Looks fixed to me.*

Less than 24 hours after the scintilla version appeared!
Thank you for your quick work! :)

**Comment by b4n** [comment]
@BenWiederhake thanks for the detailed check :)

**Pull request merged**
