### PR TITLE
Update Scintilla to version 3.10.0

### PR DESCRIPTION
**Pull request by b4n**
@elextr @codebrainz what do you think about the ABI break?

TODO: check which bugs (if any) are fixed by this update.

### CODE REVIEW

**Comment by elextr** [comment]
WFM (at least with C++) will continue to test

@b4n why do you suggest an ABI change?  Clearly if any Scintilla enums or offsets visible to plugins might have changed (other than at the end) then yeah ABI change needed to avoid risk.

**Comment by b4n** [comment]
@elextr see the message in https://github.com/geany/geany/pull/1914/commits/3fa7576e13e129900a6e0acbd5460237f9a1b614
To have those, one needs to define `INCLUDE_DEPRECATED_FEATURES` when including `Scintilla.h` *and* when building Scintilla so it knows these messages.

**Comment by elextr** [comment]
Ok, so ABI change to force re-compile, which will then fail without a specially built Geany is fine to handle removal.

**Comment by Skif-off** [comment]
I have some questions, with numbers for a more conveniently answer:
1) Is this PR for version 1.34?
2) Maybe approximate release time of 1.34 is already known?
3) Is [PR #1752](https://github.com/geany/geany/pull/1752) has a chance? Or hardly? (I update it from time to time and this PR will require a little more work, but, perhaps, in vain?)

P.S. And as I see ```Scintilla.h``` and ```Scintilla.iface ``` were updated and it may require to update the list of supported ```SCI_*``` message for GeanyLua plugin (for ```geany.scintilla()```).

**Comment by elextr** [comment]
@Skif-off 1.34 is due https://github.com/geany/geany/milestone/12 ... oh wait, missed it :)

Since its been several releases since Scintilla has been updated probably this indeed should be included in 1.34, not sure what else is likely to make it, depends on peoples time availability.

If anybody notices plugins that need changing to match this Scintilla then they should ping the maintainer I guess.

**Comment by Skif-off** [comment]
About ABI and API... I checked Geany, all default plugins and third-party plugins from https://plugins.geany.org and [Peasy](https://github.com/kugel-/peasy), I found ```SCI_*STYLEBITS*``` in:
1) ```geanylua/glspi_sci.h```, but GeanyLua don't use these messages, this file just have the list of available messages for ```geany.scintilla()``` (sends a ```SCI_*``` message directly to the Scintilla widget of the active document), we just need to update ```geanylua/glspi_sci.h``` and it will disappear.
Well, this file needs to be updated after each update of Scintilla.
2) ```peasy/api/geany-scintilla-tmp-1.0.vapì```: as I understood this file can be regenerated too.

I also checked Geany and default plugins by numeric values of messages ```SCI_*STYLEBITS*``` (2090, 2091, 4011).

I.e. changes of ABI and API are not required. Or I'm wrong, because I can not check custom Python and Lua scripts too?


P.S. GeanyLua currently has no maintainer, but I like it easy plugin, my last change is [adding support command "Strip Trailing Spaces"](https://github.com/geany/geany-plugins/pull/759) and I think I can update the```geanylua/glspi_sci.h``` and make PR after updating the Scintilla (also Scintilla 3.10.0 has new ```SCI_*``` messages and other changes, that require update ```glspi_sci.h```).

**Comment by elextr** [comment]
@b4n, whats holding this up from simply being committed?

**Comment by b4n** [comment]
@elextr no, I just got sidetracked by life.

@Skif-off while in practice it might be ok-ish to just drop the messages and modify those users, it's not really a good thing to rely on because we can't be sure we caught all cases (what about unknown third party plugins?), and is more generally not a safe approach to compatibility break where the safe path is usually the best one.  And here the "problem" it causes is that plugins have to be recompiled, which usually isn't much of a big deal.

**Comment by elextr** [comment]
>  I just got sidetracked by life.

ditto

@b4n, Just to be sure, your TODO in the OP is outside this PR? So I can just commit as is?

**Comment by b4n** [comment]
@elextr ideally the merge commit (or the update commit itself) would reference issues this fixes, but it can be done later on too I guess.

**Comment by elextr** [comment]
You mean your bash script doesn't have AI capabilities to work it out? :grin:

Ummm, actually how do you find out what it fixes, for all the languages you don't use?

**Comment by b4n** [comment]
@elextr I usually either check the Scintilla history to see what changed or simply look for open issues that could have been fixed.
Usually it's not so hard because there's not a huge delta, this time it's a little trickier -- and I only found 1 to close.

**Pull request merged**
