### PR TITLE
PowerShell: Update keywords

### PR DESCRIPTION
**Pull request by b4n**
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-7.4

I have no idea about that, but I saw we didn't have `class` when I worked on the uctags fixes, so here it is.  Do with it what you may; I'm not sure if the removals are a good thing as it might depend on the PS version or something?  No clue :)

### CODE REVIEW

**Comment by elextr** [comment]
From the link above, also missing "clean".  What about the workflow keywords? (He says knowing nothing about what a workflow is).

**Comment by eht16** [comment]
To the removed ones:
- "default" - no idea
- "where" - according to http://xahlee.info/powershell/powershell_aliases.html and https://superuser.com/a/1397265, "where" is an alias

So, we could add "where" to the aliases list. I checked the aliases in PowerShell on my Windows 7 machine, there are "foreach" and "where" listed which are missing in the current list.
As far as I remember, the defined aliases on my system should be default, I don't think I ever messed with them (until now I didn't even know PowerShell knows aliases :D).

Agree with @elextr about "clean". The rest looks fine to me, remember I don't have a clue about PowerShell as well :).

**Comment by b4n** [comment]
@eht16 you're the de-facto expert here, remember you did some work on it, now you're doomed 😁

I'll try and update this, but feel also free to take this PR over fixing whatever you think makes sense. Again, all I did was looking at (possibly an older version of) the link and came up with this just seeing missing keywords from examples.

**Comment by b4n** [comment]
LGTM given the comments you guys made. We should just squash those commits together when merging.

**Pull request merged**
