### PR TITLE
Add a README.rst link for GitHub to know the format and render it

### PR DESCRIPTION
**Pull request by b4n**
This will make GitHub show a [nicely rendered](/b4n/geany/tree/readme-rst#readme) version of our README, without all the implications of removing the *README* name (see 5762981165db403a6e2552d05f05a11f8f5235c0)

This uses a symlink.  It's great for non-Windows, and apparently Git for Windows is [clever enough](https://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows) nowadays to do the Right Thing with a symlink there.

### CODE REVIEW

**Comment by codebrainz** [comment]
This is what happens for me (from the link given):

> This makes e.g. symlinks created under Linux to be created as plain text files that contain the link text under Windows

When I `cat` the README.rst file, it just says `README` with no newline. Ubuntu 15.10, repo on NTFS filesystem shared between Linux and Windows.

**Comment by b4n** [comment]
Looks like what Git shows in a diff, but well.  Anyway, unless it actually breaks the cloning or local dirty state, I don't think the actual file's contents matters much so long as GitHub understands it.  It's not here to be edited but to give GitHub a hint.

Also using weird NTFS features from Linux (which has a way sub-optimal handling of it) doesn't sound like the best test case ever :)  Though, nice to see it doesn't break stuff at least.

**Comment by codebrainz** [comment]
It doesn't seem to break when I edit `README` and push it: https://github.com/codebrainz/geany/tree/b4n/readme-rst

BTW, I noticed the copyright stuff at the bottom of the README is kind of mangled on Github.

**Comment by b4n** [comment]
> It doesn't seem to break when I edit `README` and push it

Good :)  But that's kinda expected as `README` didn't change a bit

> BTW, I noticed the copyright stuff at the bottom of the README is kind of mangled on Github.

Yeah that file has broken reSt syntax in some places, I'll fix it (some of it is fixed in #1087)

**Comment by codebrainz** [comment]
> But that's kinda expected as README didn't change a bit

I added "Oh nooooo" after the top title.

**Comment by b4n** [comment]
no I mean this patch doesn't touch `README`  -- and your patch doesn't touch `README.rst`.

**Comment by codebrainz** [comment]
Yeah, I just wanted to make sure that pushing from an FS that doesn't support symlinks preserves the symlink and not break it.

Looks good to me.

**Comment by codebrainz** [comment]
Out of curiosity, couldn't we also just add `foreign` to `AM_INIT_AUTOMAKE()` to prevent it from complaining about missing the boilerplate files like `README`, `INSTALL`, `ChangeLog`, etc? I do this on some personal projects and it seems to work fine when I have a `README.md` file instead of `README`.

**Comment by b4n** [comment]
That's what we initially did (see the commit linked and which commits it reverts).  But IIRC there was more problems because we install the README in some places, so we'd have to alter those too.

**Comment by codebrainz** [comment]
At least here would also need to be updated: https://github.com/geany/geany/blob/master/Makefile.am#L50

**Comment by eht16** [comment]
Just tested on native Windows using git in a cmd.exe and also using git in a MSYS2 shell. Both work fine and create a README.rst with the content README, as expected.

LGTM.

**Comment by eht16** [comment]
Oh, MacOSX? But I guess either GIT as on Windows or MaxOSX itself can handle symlinks there as well.

**Comment by b4n** [comment]
@eht16 thanks for testing on real windows, that's great!

But I wouldn't worry about OSX, it should handle symlinks just fine so I don't expect any issue there.  And anyway, Git should do whatever is needed if it's not supported properly, as it does on Windows.

**Pull request merged**
