### PR TITLE
Highlight fix 2

### PR DESCRIPTION
**Pull request by techee**
Alright, here's yet another fix of the colorization problem. I reverted the partial colorization patch completely and perform (full) recolorization when the typename list changes. I decided to detect the change of the typename list based on the string hash value - I believe it's sufficient and saves some memory per tab. The performance seems to be OK too (only when changing name of some type things get slower but there's no performance problem for normal code editing).

@elextr Could you test please?
@b4n Does it look OK to you?

### CODE REVIEW

**Comment by elextr** [comment]
Works for me, will keep using it until @b4n approves and merges.

**Comment by b4n** [comment]
LGBI, and the hash idea seems reasonable.

**Comment by elextr** [comment]
@techee if you are worried about performance why use a hash?  Calculating it is likely to be slower than a string compare since the compare will use cache hardware and the hash is a char by char [loop](https://github.com/GNOME/glib/blob/master/glib/gstring.c#L306).

**Comment by codebrainz** [comment]
@elextr I think it's mentioned in the commit comments; it's not for performance, it's to avoid storing duplicate copies of the huge typenames string. I don't think Scintilla has a getter counterpart to `SCI_SETKEYWORDS` in order to compare to previous typenames string.

**Comment by techee** [comment]
Yes, it's true the hash computation will be a bit slower but this isn't the part I was trying to optimize - the slow part is when the typename string differs and when scintilla needs to perform recolorization.

**Comment by elextr** [comment]
@codebrainz is the string really that big? Compared to the scintilla source buffer it came from, with its style info and line info and its map containing the names from the previous string.  Also there is tagmangler and the symbols pane GTK treeview containing the same info in greatly expanded form.  The string will be considerably smaller than all of the preceeding.

@techee, np, just asking, since the hash time is incurred each time the parser runs, not just when there is a change.  This patch is still working fine for me, though on files of a sane size :)

**Comment by techee** [comment]
> @codebrainz is the string really that big? Compared to the scintilla source buffer it came from, with its style info and line info and its map containing the names from the previous string. Also there is tagmangler and the symbols pane GTK treeview containing the same info in greatly expanded form. The string will be considerably smaller than all of the preceeding.

I'm not @codebrainz but I have an answer :-). The string contains typenames from all open files or, when using ProjectOrganizer, the complete project (compared to the tree view which contains it for a single file only). If I remember correctly, it's about 1MB string for the Linux kernel sources.

The fact is that this string is passed to Scintilla anyway so it already consumes 1MB per open file and I guess having it stored once more and taking up 2MB per open file wouldn't be such a disaster so we could store it too if this is the preferred variant - I don't care much.

> @techee, np, just asking, since the hash time is incurred each time the parser runs, not just when there is a change. This patch is still working fine for me, though on files of a sane size :)

Yes, but we already do this every time the parsing happens:

https://github.com/geany/geany/blob/master/src/symbols.c#L200

i.e. creating the huge string by concatenating the typename array, comparing values and removing duplicates (and when getting the tag names, we have to dereference pointers so this won't be cached easily by the processor). My guess is doing the hash is much cheaper than the above so if we wanted to speed up this part, we'd first have eliminate the concatenation.

**Pull request merged**
