### PR TITLE
splitwindow: Fix document selection popup on GTK >= 3.15.9 && <= 3.21.4

### LINKED ISSUE #1149: Split window file selector does not work
Geany 1.29, en_AU.UTF-8  GTK 3.18.9, GLib 2.48.1

Nothing happens when a file is selected from the file selector on the split window. 

@codebrainz has confirmed with gtk3, doesn't happen with gtk2.

Suspect [this](https://github.com/geany/geany/commit/1a36eeaf4d6a5cab39d2cfd2c69a1a2f6e2bce70) from @techee which changes the splitwindow widget tree, but it doesn't revert cleanly to try easily.

### PR DESCRIPTION
**Pull request by b4n**
Works around GTK bug https://bugzilla.gnome.org/show_bug.cgi?id=769287.
Stop emission of the `::show-menu` signal if it was first emitted from an
inactive toggle button, which happens only in the buggy case.
This workaround tries to not negatively affect a correctly behaving GTK
version in the unlikely case some distributions patched their version.

Fixes #1149.

### CODE REVIEW

**Comment by elextr** [comment]
Works for me, GTK 3.18.9 but with the messages

```
(geany:32192): Gtk-CRITICAL **: gtk_widget_unmap: assertion 'GTK_IS_WIDGET (widget)' failed

(geany:32192): Gtk-CRITICAL **: gtk_widget_unmap: assertion 'GTK_IS_WIDGET (widget)' failed

(geany:32192): Gtk-CRITICAL **: gtk_widget_unrealize: assertion 'GTK_IS_WIDGET (widget)' failed

(geany:32192): Gtk-CRITICAL **: gtk_widget_unrealize: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by b4n** [comment]
> but with the messages […]

Ah right, that's Scintilla.  I even had a fix somewhere, I'll find it back.  But it's not *so* bad, it's "simply" that the widgets (scrollbars) in question are NULLs at this point, not plain invalid memory.

**Comment by b4n** [comment]
@elextr https://sourceforge.net/p/scintilla/bugs/1873/

**Comment by elextr** [comment]
Ok, hopefully that will be in Scintilla 3.7.1 which will probably not be in 1.29, so this should also wait.

**Comment by b4n** [comment]
@elextr why wait?  It's totally unrelated to the fix, and it can happen a number of other ways.  Also, the linked patch is totally trivial, it just guards 4 calls not to happen on NULL values, I'm confident you can review it for typos (like not guarding the right variable or something) in 5 minutes and we'll be sure it won't be a problem backporting it.

**Comment by elextr** [comment]
Ok, if you want to do that.

**Comment by elextr** [comment]
Works for me :+1:

**Pull request merged**
