### PR TITLE
.gitignore:ignore the _build dir

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by elextr** [comment]
Where does "_build" come from?

**Comment by andy5995** [comment]
> Where does "_build" come from?

I thought I saw somewhere in the docs where _build is suggested as a separate build directory. That's what I use anyway.

I guess it's only used for in travis.yml and maybe the mingw build?

Ah, just close this if you don't think it's relevant.

**Comment by elextr** [comment]
I think it might have meant an out-of-tree directory, I don't think you gain much if its in-tree :)  

I couldn't find any reference in the docs, but maybe @codebrainz will, he seems to be a better googler than me :)

I don't know about the mingw builds (@eht16 ?), but since Travis will never push changes back to the repo it doesn't matter there.

**Comment by codebrainz** [comment]
@andy5995 if this is the directory you use to build in (good idea to build "out of tree"), you can use:

```bash
$ echo "/_build/" >> .git/info/exclude
```
And it will ignore it for you locally. I do this sometimes with a `.misc` and `.build` for random files I don't want to check in and for building "out of tree".

**Comment by andy5995** [comment]
> @andy5995 if this is the directory you use to build in (good idea to build "out of tree"), you can use:
> 
> ```shell
> $ echo "/_build/" >> .git/info/exclude
> ```
> 
> And it will ignore it for you locally. I do this sometimes with a `.misc` and `.build` for random files I don't want to check in and for building "out of tree".

Great, thanks @codebrainz

**Pull request closed without merging**
