### PR TITLE
Rust: Update keyword list

### PR DESCRIPTION
**Pull request by crumblingstatue**
Source: http://doc.rust-lang.org/reference.html#keywords

### CODE REVIEW

**Comment by b4n** [comment]
We keep suck keyword lists sorted alphabetically, could you please fix this?

Also, IIUC `once` and `proc` used to be keywords, right?  Do we want to remove them already, or are they still in a stable/spread/whataver version of the compiler?
Also, looking at http://stackoverflow.com/questions/25132467/found-once-in-ident-position it seems at least in last August at least `one` still was some kind of confusing thing.

@SiegeLord as you worked on the Rust support, do you have an opinion on this?

**Comment by crumblingstatue** [comment]
`once` was removed a while ago, and it's not in any stable/widespread version.
However, it turns out `proc` is still treated by the compiler as a keyword.
I am currently investigating this, I'll post an update here when I sorted it out.

**Comment by crumblingstatue** [comment]
I have submitted an [RFC](https://github.com/rust-lang/rfcs/pull/584) for removing the proc keyword, which will need to undergo review and discussion.

We can either put the proc keyword back or wait with this PR until the decision about the fate of the keyword is made.

**Comment by SiegeLord** [comment]
I always derived the keyword list from the list in the compiler: https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/token.rs#L522 rather than the reference which was not always up to date.

**Comment by crumblingstatue** [comment]
Closing this PR, as I'm not interested in working on it anymore.

**Pull request closed without merging**
