### PR TITLE
Added an option to save/reload either window position or size, but optionally not both.

### PR DESCRIPTION
**Pull request by delt01**
Added an option to save/reload either window position or size, but optionally not both.

### CODE REVIEW

**Comment by delt01** [comment]
Hoping to see this in a future version of geany :D Thanks for an amazing text editor btw!!!

**Comment by elextr** [comment]
LGBI, not yet tested.

**Comment by kugel-** [comment]
One could argue that GeanyPrefs is part of the  ABI, and new fields should be appended.

**Comment by elextr** [comment]
@kugel- good catch 

yeah should be at the end or the ABI needs incrementing, and no point in doing that unless we need to.

**Comment by codebrainz** [comment]
Closed in 38147b2590f6d4e695c3637dd360631a1b7cc7f5

**Comment by codebrainz** [comment]
Forgot to update the manual to reflect the switch to two separate preferences.

**Comment by elextr** [comment]
Make an issue so its not hidden in a closed PR (or fix it :)

**Pull request closed without merging**
