### PR TITLE
Concatenate ChangeLog.pre-0-17 and ChangeLog.pre-1-22

### PR DESCRIPTION
**Pull request by techee**
These files aren't updated (and probably read by anyone) any more and
it's better to have less "garbage" files in the root.

### CODE REVIEW

**Comment by techee** [comment]
A cheesy way to improve my diffstats ;-)

**Comment by elextr** [comment]
Can't we just delete them?  They will still be in git, just go back to 1.26.

**Comment by techee** [comment]
@elextr  Yeah, maybe. But it could still be useful when looking at some old commit to understand what it does and when the old SVN commit message isn't sufficient (haven't really checked if the old commit messages contain the same info but sometimes even just rephrased description may help).

**Comment by elextr** [comment]
@techee if you checkout an old commit the changelogs will come back :)

**Comment by techee** [comment]
@elextr Yeah, but if there's still some possibility it could be useful, I think we shouldn't hide it this way. 

What about "rm -rf *"ing everything in the geany directory, committing it and saying "just checkout an older commit to get the Geany code"? ;-)

**Comment by elextr** [comment]
​myeh, do whatever, its not worth arguing about :)​

**Comment by b4n** [comment]
Why not, and LGTM

**Comment by b4n** [comment]
(here go your diffstats :))

**Pull request merged**
