### PR TITLE
Bump GTK2 min. version to 2.24

### PR DESCRIPTION
**Pull request by codebrainz**
Bump the minimum GTK2 dependency version to 2.24, last supported GTK2 version.

TODO:
- [x] Do we want to use `2.24.0` or some later more stable version? (use: 2.24)
- [x] Should we use exact GLib version from the GTK+ `configure.in` version? (use next even version)
- [x] Test Waf build system.
- [x] Update or remove version checks from nightly build setup.
- [x] Create and test new GTK bundle for Win32 and fresh installers.
- [x] Do we need to care about Geany-Plugins stuff such as [this](https://github.com/geany/geany-plugins/blob/87f4b402965a079da1c1b2aac793c517a221518e/wscript#L84)?
- [ ] Remove or update [archived GTK+ reference manuals](http://www.geany.org/manual/gtk/), 2.24 documentation is [still available upstream](https://developer.gnome.org/gtk2/2.24/), so we probably don't need to host it ourselves yet, but we might want to remove the [reference in the HACKING file](https://github.com/codebrainz/geany/commit/11c67aa7a89572bbffbbb2db70a84ddef988a6ca#diff-884b897f0b13c2d7044127cda8920c82L162) if we don't update.

### CODE REVIEW

**Comment by eht16** [comment]
To resurrect this one:
about the last open item: API docs reference in HACKING: I'd agree to remove the paragraph about the self-hosted API docs and also remove the hosted docs on geany.org once this one is merged.
I guess the GTK folks will keep the 2.24 docs online in the long-term because it just will be used.

**Comment by codebrainz** [comment]
I updated to latest master branch. Is everyone OK if I start to integrate this?

**Comment by elextr** [comment]
:+1:

**Comment by b4n** [comment]
LGTM

**Comment by codebrainz** [comment]
Merged in bdc082cb7782828bd3be5992ca2e6006f2330890 and d0a431e071fa09165abacbde1dad33a24fac1cf1.

**Comment by codebrainz** [comment]
@eht16 if you remember, the last checkbox about gtk docs, but it probably doesn't matter much

**Comment by eht16** [comment]
@codebrainz done. I will keep the self-hosted API docs on the server for some time in case someone still uses an old HACKING file. I guess some time after the 1.25 release, we can remove the docs from our server.

**Pull request closed without merging**
