### PR TITLE
Python: Don't highlight sub-identifiers as keywords

### LINKED ISSUE #1542: lexer.python.keywords2.no.sub.identifiers should default to 1
Scintilla’s Python lexer has a property `lexer.python.keywords2.no.sub.identifiers` which, when set to 1, prevents it from highlighting attributes as builtins.

In other words, with this property set to 1, a bare `file` is highlighted, because it’s a Python builtin, but the word `file` in `obj.file` is not highlighted, because it’s an unknown attribute of `obj`.

This is almost always the desired behavior and it should be the default. If someone has a peculiar codebase where `obj.file` is the same as the builtin `file`, they can flip the switch back in their `filetypes.python`.

### PR DESCRIPTION
**Pull request by b4n**
For example, highlight `file` as a builtin when appearing by itself, but not in a construct like `obj.file`.

Fixes #1542.

### CODE REVIEW

**Comment by vfaronov** [comment]
Should be done in `filetypes.Cython` as well.

**Comment by b4n** [comment]
@vfaronov sounds reasonable indeed.  Actually, I just changed the Cython filetype to inherit Python properties, which includes folding of string literals.

@codebrainz @elextr thanks for the review :)  Could you give a look at the 2 new commits too please?

**Comment by eht16** [comment]
LG(reat)TM

**Comment by elextr** [comment]
Extended version LGBI

**Pull request merged**
