### PR TITLE
Add Arduino file to c++ type.

### PR DESCRIPTION
**Pull request by guiguid**
Add Arduino file *.ino and *.pde  to c++ type.

### CODE REVIEW

**Comment by b4n** [comment]
I don't know those filetypes, but LGBI.  Those extensions don't seem to be used commonly by anything else, and if highlighting is good with C++ filetype, sounds good.

**Comment by elextr** [comment]
LGBI

@b4n both files are actually C++ files so they should work as (well/badly) as normal C++ files.

@guiguid you might look at making a custom filetype so you can set the proper compile and link commands for Arduino.

**Comment by SukkoPera** [comment]
Isn't this the same as #715 and even the same as https://sourceforge.net/p/geany/feature-requests/597/? Why are you so unwilling to add this upstream? A lot of people use Geany as their main Arduino editor!

**Comment by elextr** [comment]
@SukkoPera there is no problem with Arduino.

In respect of this PR, it is less than two weeks old and a suggestion has been made to the OP but no reply has been received yet.  Label added to emphasise.

That suggestion is in line with #715, but that is not a pull request, it is an issue that a custom filetype does not work.  Nobody has submitted a PR based on it, despite the fix being provided in one of the comments, so the assumption is that nobody used Geany for Arduino much.

**Comment by SukkoPera** [comment]
OK, sorry if I sounded a bit arrogant, but seeing that this had got put off a few times kinda upset me.

I've been working on fixing the custom filetype, I am going to submit it.

**Comment by codebrainz** [comment]
Closed in 21b37f553fdcaa37463465bd24d9ca5537800f0a

**Pull request closed without merging**
